import ConfigurationSet_ from './configurationSet';
import ConfigurationSetEventDestination_ from './configurationSetEventDestination';
import ContactList_ from './contactList';
import DedicatedIpPool_ from './dedicatedIpPool';
import EmailIdentity_ from './emailIdentity';
import MailManagerAddonInstance_ from './mailManagerAddonInstance';
import MailManagerAddonSubscription_ from './mailManagerAddonSubscription';
import MailManagerAddressList_ from './mailManagerAddressList';
import MailManagerArchive_ from './mailManagerArchive';
import MailManagerIngressPoint_ from './mailManagerIngressPoint';
import MailManagerRelay_ from './mailManagerRelay';
import MailManagerRuleSet_ from './mailManagerRuleSet';
import MailManagerTrafficPolicy_ from './mailManagerTrafficPolicy';
import ReceiptFilter_ from './receiptFilter';
import ReceiptRule_ from './receiptRule';
import ReceiptRuleSet_ from './receiptRuleSet';
import Template_ from './template';
import VdmAttributes_ from './vdmAttributes';
export namespace SES {
  export const ConfigurationSet = ConfigurationSet_;
  export const ConfigurationSetEventDestination = ConfigurationSetEventDestination_;
  export const ContactList = ContactList_;
  export const DedicatedIpPool = DedicatedIpPool_;
  export const EmailIdentity = EmailIdentity_;
  export const MailManagerAddonInstance = MailManagerAddonInstance_;
  export const MailManagerAddonSubscription = MailManagerAddonSubscription_;
  export const MailManagerAddressList = MailManagerAddressList_;
  export const MailManagerArchive = MailManagerArchive_;
  export const MailManagerIngressPoint = MailManagerIngressPoint_;
  export const MailManagerRelay = MailManagerRelay_;
  export const MailManagerRuleSet = MailManagerRuleSet_;
  export const MailManagerTrafficPolicy = MailManagerTrafficPolicy_;
  export const ReceiptFilter = ReceiptFilter_;
  export const ReceiptRule = ReceiptRule_;
  export const ReceiptRuleSet = ReceiptRuleSet_;
  export const Template = Template_;
  export const VdmAttributes = VdmAttributes_;
  export type ConfigurationSet = ConfigurationSet_;
  export type ConfigurationSetEventDestination = ConfigurationSetEventDestination_;
  export type ContactList = ContactList_;
  export type DedicatedIpPool = DedicatedIpPool_;
  export type EmailIdentity = EmailIdentity_;
  export type MailManagerAddonInstance = MailManagerAddonInstance_;
  export type MailManagerAddonSubscription = MailManagerAddonSubscription_;
  export type MailManagerAddressList = MailManagerAddressList_;
  export type MailManagerArchive = MailManagerArchive_;
  export type MailManagerIngressPoint = MailManagerIngressPoint_;
  export type MailManagerRelay = MailManagerRelay_;
  export type MailManagerRuleSet = MailManagerRuleSet_;
  export type MailManagerTrafficPolicy = MailManagerTrafficPolicy_;
  export type ReceiptFilter = ReceiptFilter_;
  export type ReceiptRule = ReceiptRule_;
  export type ReceiptRuleSet = ReceiptRuleSet_;
  export type Template = Template_;
  export type VdmAttributes = VdmAttributes_;
}
