import Alarm_ from './alarm';
import Bucket_ from './bucket';
import Certificate_ from './certificate';
import Container_ from './container';
import Database_ from './database';
import Disk_ from './disk';
import DiskSnapshot_ from './diskSnapshot';
import Instance_ from './instance';
import InstanceSnapshot_ from './instanceSnapshot';
import LoadBalancer_ from './loadBalancer';
import LoadBalancerTlsCertificate_ from './loadBalancerTlsCertificate';
import StaticIp_ from './staticIp';
import Distribution_ from './distribution';
import Domain_ from './domain';
export namespace Lightsail {
  export const Alarm = Alarm_;
  export const Bucket = Bucket_;
  export const Certificate = Certificate_;
  export const Container = Container_;
  export const Database = Database_;
  export const Disk = Disk_;
  export const DiskSnapshot = DiskSnapshot_;
  export const Instance = Instance_;
  export const InstanceSnapshot = InstanceSnapshot_;
  export const LoadBalancer = LoadBalancer_;
  export const LoadBalancerTlsCertificate = LoadBalancerTlsCertificate_;
  export const StaticIp = StaticIp_;
  export const Distribution = Distribution_;
  export const Domain = Domain_;
  export type Alarm = Alarm_;
  export type Bucket = Bucket_;
  export type Certificate = Certificate_;
  export type Container = Container_;
  export type Database = Database_;
  export type Disk = Disk_;
  export type DiskSnapshot = DiskSnapshot_;
  export type Instance = Instance_;
  export type InstanceSnapshot = InstanceSnapshot_;
  export type LoadBalancer = LoadBalancer_;
  export type LoadBalancerTlsCertificate = LoadBalancerTlsCertificate_;
  export type StaticIp = StaticIp_;
  export type Distribution = Distribution_;
  export type Domain = Domain_;
}
