import IdentityPool_ from './identityPool';
import IdentityPoolPrincipalTag_ from './identityPoolPrincipalTag';
import IdentityPoolRoleAttachment_ from './identityPoolRoleAttachment';
import LogDeliveryConfiguration_ from './logDeliveryConfiguration';
import ManagedLoginBranding_ from './managedLoginBranding';
import UserPool_ from './userPool';
import UserPoolClient_ from './userPoolClient';
import UserPoolDomain_ from './userPoolDomain';
import UserPoolGroup_ from './userPoolGroup';
import UserPoolIdentityProvider_ from './userPoolIdentityProvider';
import UserPoolResourceServer_ from './userPoolResourceServer';
import UserPoolRiskConfigurationAttachment_ from './userPoolRiskConfigurationAttachment';
import UserPoolUICustomizationAttachment_ from './userPoolUiCustomizationAttachment';
import UserPoolUser_ from './userPoolUser';
import UserPoolUserToGroupAttachment_ from './userPoolUserToGroupAttachment';
export namespace Cognito {
  export const IdentityPool = IdentityPool_;
  export const IdentityPoolPrincipalTag = IdentityPoolPrincipalTag_;
  export const IdentityPoolRoleAttachment = IdentityPoolRoleAttachment_;
  export const LogDeliveryConfiguration = LogDeliveryConfiguration_;
  export const ManagedLoginBranding = ManagedLoginBranding_;
  export const UserPool = UserPool_;
  export const UserPoolClient = UserPoolClient_;
  export const UserPoolDomain = UserPoolDomain_;
  export const UserPoolGroup = UserPoolGroup_;
  export const UserPoolIdentityProvider = UserPoolIdentityProvider_;
  export const UserPoolResourceServer = UserPoolResourceServer_;
  export const UserPoolRiskConfigurationAttachment = UserPoolRiskConfigurationAttachment_;
  export const UserPoolUICustomizationAttachment = UserPoolUICustomizationAttachment_;
  export const UserPoolUser = UserPoolUser_;
  export const UserPoolUserToGroupAttachment = UserPoolUserToGroupAttachment_;
  export type IdentityPool = IdentityPool_;
  export type IdentityPoolPrincipalTag = IdentityPoolPrincipalTag_;
  export type IdentityPoolRoleAttachment = IdentityPoolRoleAttachment_;
  export type LogDeliveryConfiguration = LogDeliveryConfiguration_;
  export type ManagedLoginBranding = ManagedLoginBranding_;
  export type UserPool = UserPool_;
  export type UserPoolClient = UserPoolClient_;
  export type UserPoolDomain = UserPoolDomain_;
  export type UserPoolGroup = UserPoolGroup_;
  export type UserPoolIdentityProvider = UserPoolIdentityProvider_;
  export type UserPoolResourceServer = UserPoolResourceServer_;
  export type UserPoolRiskConfigurationAttachment = UserPoolRiskConfigurationAttachment_;
  export type UserPoolUICustomizationAttachment = UserPoolUICustomizationAttachment_;
  export type UserPoolUser = UserPoolUser_;
  export type UserPoolUserToGroupAttachment = UserPoolUserToGroupAttachment_;
}
