import CapacityManagerDataExport_ from './capacityManagerDataExport';
import CapacityReservation_ from './capacityReservation';
import CapacityReservationFleet_ from './capacityReservationFleet';
import CarrierGateway_ from './carrierGateway';
import ClientVpnAuthorizationRule_ from './clientVpnAuthorizationRule';
import ClientVpnEndpoint_ from './clientVpnEndpoint';
import ClientVpnRoute_ from './clientVpnRoute';
import ClientVpnTargetNetworkAssociation_ from './clientVpnTargetNetworkAssociation';
import CustomerGateway_ from './customerGateway';
import DHCPOptions_ from './dhcpOptions';
import EC2Fleet_ from './ec2Fleet';
import EIP_ from './eip';
import EIPAssociation_ from './eipAssociation';
import EgressOnlyInternetGateway_ from './egressOnlyInternetGateway';
import EnclaveCertificateIamRoleAssociation_ from './enclaveCertificateIamRoleAssociation';
import FlowLog_ from './flowLog';
import GatewayRouteTableAssociation_ from './gatewayRouteTableAssociation';
import Host_ from './host';
import IPAM_ from './ipam';
import IPAMAllocation_ from './ipamAllocation';
import IPAMPool_ from './ipamPool';
import IPAMPoolCidr_ from './ipamPoolCidr';
import IPAMResourceDiscovery_ from './ipamResourceDiscovery';
import IPAMResourceDiscoveryAssociation_ from './ipamResourceDiscoveryAssociation';
import IPAMScope_ from './ipamScope';
import Instance_ from './instance';
import InstanceConnectEndpoint_ from './instanceConnectEndpoint';
import InternetGateway_ from './internetGateway';
import IpPoolRouteTableAssociation_ from './ipPoolRouteTableAssociation';
import KeyPair_ from './keyPair';
import LaunchTemplate_ from './launchTemplate';
import LocalGatewayRoute_ from './localGatewayRoute';
import LocalGatewayRouteTable_ from './localGatewayRouteTable';
import LocalGatewayRouteTableVPCAssociation_ from './localGatewayRouteTableVpcAssociation';
import LocalGatewayRouteTableVirtualInterfaceGroupAssociation_ from './localGatewayRouteTableVirtualInterfaceGroupAssociation';
import LocalGatewayVirtualInterface_ from './localGatewayVirtualInterface';
import LocalGatewayVirtualInterfaceGroup_ from './localGatewayVirtualInterfaceGroup';
import NatGateway_ from './natGateway';
import NetworkAcl_ from './networkAcl';
import NetworkAclEntry_ from './networkAclEntry';
import NetworkInsightsAccessScope_ from './networkInsightsAccessScope';
import NetworkInsightsAccessScopeAnalysis_ from './networkInsightsAccessScopeAnalysis';
import NetworkInsightsAnalysis_ from './networkInsightsAnalysis';
import NetworkInsightsPath_ from './networkInsightsPath';
import NetworkInterface_ from './networkInterface';
import NetworkInterfaceAttachment_ from './networkInterfaceAttachment';
import NetworkInterfacePermission_ from './networkInterfacePermission';
import NetworkPerformanceMetricSubscription_ from './networkPerformanceMetricSubscription';
import PlacementGroup_ from './placementGroup';
import PrefixList_ from './prefixList';
import Route_ from './route';
import RouteServer_ from './routeServer';
import RouteServerAssociation_ from './routeServerAssociation';
import RouteServerEndpoint_ from './routeServerEndpoint';
import RouteServerPeer_ from './routeServerPeer';
import RouteServerPropagation_ from './routeServerPropagation';
import RouteTable_ from './routeTable';
import SecurityGroup_ from './securityGroup';
import SecurityGroupEgress_ from './securityGroupEgress';
import SecurityGroupIngress_ from './securityGroupIngress';
import SecurityGroupVpcAssociation_ from './securityGroupVpcAssociation';
import SnapshotBlockPublicAccess_ from './snapshotBlockPublicAccess';
import SpotFleet_ from './spotFleet';
import Subnet_ from './subnet';
import SubnetCidrBlock_ from './subnetCidrBlock';
import SubnetNetworkAclAssociation_ from './subnetNetworkAclAssociation';
import SubnetRouteTableAssociation_ from './subnetRouteTableAssociation';
import TrafficMirrorFilter_ from './trafficMirrorFilter';
import TrafficMirrorFilterRule_ from './trafficMirrorFilterRule';
import TrafficMirrorSession_ from './trafficMirrorSession';
import TrafficMirrorTarget_ from './trafficMirrorTarget';
import TransitGateway_ from './transitGateway';
import TransitGatewayAttachment_ from './transitGatewayAttachment';
import TransitGatewayConnect_ from './transitGatewayConnect';
import TransitGatewayConnectPeer_ from './transitGatewayConnectPeer';
import TransitGatewayMulticastDomain_ from './transitGatewayMulticastDomain';
import TransitGatewayMulticastDomainAssociation_ from './transitGatewayMulticastDomainAssociation';
import TransitGatewayMulticastGroupMember_ from './transitGatewayMulticastGroupMember';
import TransitGatewayMulticastGroupSource_ from './transitGatewayMulticastGroupSource';
import TransitGatewayPeeringAttachment_ from './transitGatewayPeeringAttachment';
import TransitGatewayRoute_ from './transitGatewayRoute';
import TransitGatewayRouteTable_ from './transitGatewayRouteTable';
import TransitGatewayRouteTableAssociation_ from './transitGatewayRouteTableAssociation';
import TransitGatewayRouteTablePropagation_ from './transitGatewayRouteTablePropagation';
import TransitGatewayVpcAttachment_ from './transitGatewayVpcAttachment';
import VPC_ from './vpc';
import VPCBlockPublicAccessExclusion_ from './vpcBlockPublicAccessExclusion';
import VPCBlockPublicAccessOptions_ from './vpcBlockPublicAccessOptions';
import VPCCidrBlock_ from './vpcCidrBlock';
import VPCDHCPOptionsAssociation_ from './vpcdhcpOptionsAssociation';
import VPCEndpoint_ from './vpcEndpoint';
import VPCEndpointConnectionNotification_ from './vpcEndpointConnectionNotification';
import VPCEndpointService_ from './vpcEndpointService';
import VPCEndpointServicePermissions_ from './vpcEndpointServicePermissions';
import VPCGatewayAttachment_ from './vpcGatewayAttachment';
import VPCPeeringConnection_ from './vpcPeeringConnection';
import VPNConnection_ from './vpnConnection';
import VPNConnectionRoute_ from './vpnConnectionRoute';
import VPNGateway_ from './vpnGateway';
import VPNGatewayRoutePropagation_ from './vpnGatewayRoutePropagation';
import VerifiedAccessEndpoint_ from './verifiedAccessEndpoint';
import VerifiedAccessGroup_ from './verifiedAccessGroup';
import VerifiedAccessInstance_ from './verifiedAccessInstance';
import VerifiedAccessTrustProvider_ from './verifiedAccessTrustProvider';
import Volume_ from './volume';
import VolumeAttachment_ from './volumeAttachment';
export namespace EC2 {
  export const CapacityManagerDataExport = CapacityManagerDataExport_;
  export const CapacityReservation = CapacityReservation_;
  export const CapacityReservationFleet = CapacityReservationFleet_;
  export const CarrierGateway = CarrierGateway_;
  export const ClientVpnAuthorizationRule = ClientVpnAuthorizationRule_;
  export const ClientVpnEndpoint = ClientVpnEndpoint_;
  export const ClientVpnRoute = ClientVpnRoute_;
  export const ClientVpnTargetNetworkAssociation = ClientVpnTargetNetworkAssociation_;
  export const CustomerGateway = CustomerGateway_;
  export const DHCPOptions = DHCPOptions_;
  export const EC2Fleet = EC2Fleet_;
  export const EIP = EIP_;
  export const EIPAssociation = EIPAssociation_;
  export const EgressOnlyInternetGateway = EgressOnlyInternetGateway_;
  export const EnclaveCertificateIamRoleAssociation = EnclaveCertificateIamRoleAssociation_;
  export const FlowLog = FlowLog_;
  export const GatewayRouteTableAssociation = GatewayRouteTableAssociation_;
  export const Host = Host_;
  export const IPAM = IPAM_;
  export const IPAMAllocation = IPAMAllocation_;
  export const IPAMPool = IPAMPool_;
  export const IPAMPoolCidr = IPAMPoolCidr_;
  export const IPAMResourceDiscovery = IPAMResourceDiscovery_;
  export const IPAMResourceDiscoveryAssociation = IPAMResourceDiscoveryAssociation_;
  export const IPAMScope = IPAMScope_;
  export const Instance = Instance_;
  export const InstanceConnectEndpoint = InstanceConnectEndpoint_;
  export const InternetGateway = InternetGateway_;
  export const IpPoolRouteTableAssociation = IpPoolRouteTableAssociation_;
  export const KeyPair = KeyPair_;
  export const LaunchTemplate = LaunchTemplate_;
  export const LocalGatewayRoute = LocalGatewayRoute_;
  export const LocalGatewayRouteTable = LocalGatewayRouteTable_;
  export const LocalGatewayRouteTableVPCAssociation = LocalGatewayRouteTableVPCAssociation_;
  export const LocalGatewayRouteTableVirtualInterfaceGroupAssociation =
    LocalGatewayRouteTableVirtualInterfaceGroupAssociation_;
  export const LocalGatewayVirtualInterface = LocalGatewayVirtualInterface_;
  export const LocalGatewayVirtualInterfaceGroup = LocalGatewayVirtualInterfaceGroup_;
  export const NatGateway = NatGateway_;
  export const NetworkAcl = NetworkAcl_;
  export const NetworkAclEntry = NetworkAclEntry_;
  export const NetworkInsightsAccessScope = NetworkInsightsAccessScope_;
  export const NetworkInsightsAccessScopeAnalysis = NetworkInsightsAccessScopeAnalysis_;
  export const NetworkInsightsAnalysis = NetworkInsightsAnalysis_;
  export const NetworkInsightsPath = NetworkInsightsPath_;
  export const NetworkInterface = NetworkInterface_;
  export const NetworkInterfaceAttachment = NetworkInterfaceAttachment_;
  export const NetworkInterfacePermission = NetworkInterfacePermission_;
  export const NetworkPerformanceMetricSubscription = NetworkPerformanceMetricSubscription_;
  export const PlacementGroup = PlacementGroup_;
  export const PrefixList = PrefixList_;
  export const Route = Route_;
  export const RouteServer = RouteServer_;
  export const RouteServerAssociation = RouteServerAssociation_;
  export const RouteServerEndpoint = RouteServerEndpoint_;
  export const RouteServerPeer = RouteServerPeer_;
  export const RouteServerPropagation = RouteServerPropagation_;
  export const RouteTable = RouteTable_;
  export const SecurityGroup = SecurityGroup_;
  export const SecurityGroupEgress = SecurityGroupEgress_;
  export const SecurityGroupIngress = SecurityGroupIngress_;
  export const SecurityGroupVpcAssociation = SecurityGroupVpcAssociation_;
  export const SnapshotBlockPublicAccess = SnapshotBlockPublicAccess_;
  export const SpotFleet = SpotFleet_;
  export const Subnet = Subnet_;
  export const SubnetCidrBlock = SubnetCidrBlock_;
  export const SubnetNetworkAclAssociation = SubnetNetworkAclAssociation_;
  export const SubnetRouteTableAssociation = SubnetRouteTableAssociation_;
  export const TrafficMirrorFilter = TrafficMirrorFilter_;
  export const TrafficMirrorFilterRule = TrafficMirrorFilterRule_;
  export const TrafficMirrorSession = TrafficMirrorSession_;
  export const TrafficMirrorTarget = TrafficMirrorTarget_;
  export const TransitGateway = TransitGateway_;
  export const TransitGatewayAttachment = TransitGatewayAttachment_;
  export const TransitGatewayConnect = TransitGatewayConnect_;
  export const TransitGatewayConnectPeer = TransitGatewayConnectPeer_;
  export const TransitGatewayMulticastDomain = TransitGatewayMulticastDomain_;
  export const TransitGatewayMulticastDomainAssociation = TransitGatewayMulticastDomainAssociation_;
  export const TransitGatewayMulticastGroupMember = TransitGatewayMulticastGroupMember_;
  export const TransitGatewayMulticastGroupSource = TransitGatewayMulticastGroupSource_;
  export const TransitGatewayPeeringAttachment = TransitGatewayPeeringAttachment_;
  export const TransitGatewayRoute = TransitGatewayRoute_;
  export const TransitGatewayRouteTable = TransitGatewayRouteTable_;
  export const TransitGatewayRouteTableAssociation = TransitGatewayRouteTableAssociation_;
  export const TransitGatewayRouteTablePropagation = TransitGatewayRouteTablePropagation_;
  export const TransitGatewayVpcAttachment = TransitGatewayVpcAttachment_;
  export const VPC = VPC_;
  export const VPCBlockPublicAccessExclusion = VPCBlockPublicAccessExclusion_;
  export const VPCBlockPublicAccessOptions = VPCBlockPublicAccessOptions_;
  export const VPCCidrBlock = VPCCidrBlock_;
  export const VPCDHCPOptionsAssociation = VPCDHCPOptionsAssociation_;
  export const VPCEndpoint = VPCEndpoint_;
  export const VPCEndpointConnectionNotification = VPCEndpointConnectionNotification_;
  export const VPCEndpointService = VPCEndpointService_;
  export const VPCEndpointServicePermissions = VPCEndpointServicePermissions_;
  export const VPCGatewayAttachment = VPCGatewayAttachment_;
  export const VPCPeeringConnection = VPCPeeringConnection_;
  export const VPNConnection = VPNConnection_;
  export const VPNConnectionRoute = VPNConnectionRoute_;
  export const VPNGateway = VPNGateway_;
  export const VPNGatewayRoutePropagation = VPNGatewayRoutePropagation_;
  export const VerifiedAccessEndpoint = VerifiedAccessEndpoint_;
  export const VerifiedAccessGroup = VerifiedAccessGroup_;
  export const VerifiedAccessInstance = VerifiedAccessInstance_;
  export const VerifiedAccessTrustProvider = VerifiedAccessTrustProvider_;
  export const Volume = Volume_;
  export const VolumeAttachment = VolumeAttachment_;
  export type CapacityManagerDataExport = CapacityManagerDataExport_;
  export type CapacityReservation = CapacityReservation_;
  export type CapacityReservationFleet = CapacityReservationFleet_;
  export type CarrierGateway = CarrierGateway_;
  export type ClientVpnAuthorizationRule = ClientVpnAuthorizationRule_;
  export type ClientVpnEndpoint = ClientVpnEndpoint_;
  export type ClientVpnRoute = ClientVpnRoute_;
  export type ClientVpnTargetNetworkAssociation = ClientVpnTargetNetworkAssociation_;
  export type CustomerGateway = CustomerGateway_;
  export type DHCPOptions = DHCPOptions_;
  export type EC2Fleet = EC2Fleet_;
  export type EIP = EIP_;
  export type EIPAssociation = EIPAssociation_;
  export type EgressOnlyInternetGateway = EgressOnlyInternetGateway_;
  export type EnclaveCertificateIamRoleAssociation = EnclaveCertificateIamRoleAssociation_;
  export type FlowLog = FlowLog_;
  export type GatewayRouteTableAssociation = GatewayRouteTableAssociation_;
  export type Host = Host_;
  export type IPAM = IPAM_;
  export type IPAMAllocation = IPAMAllocation_;
  export type IPAMPool = IPAMPool_;
  export type IPAMPoolCidr = IPAMPoolCidr_;
  export type IPAMResourceDiscovery = IPAMResourceDiscovery_;
  export type IPAMResourceDiscoveryAssociation = IPAMResourceDiscoveryAssociation_;
  export type IPAMScope = IPAMScope_;
  export type Instance = Instance_;
  export type InstanceConnectEndpoint = InstanceConnectEndpoint_;
  export type InternetGateway = InternetGateway_;
  export type IpPoolRouteTableAssociation = IpPoolRouteTableAssociation_;
  export type KeyPair = KeyPair_;
  export type LaunchTemplate = LaunchTemplate_;
  export type LocalGatewayRoute = LocalGatewayRoute_;
  export type LocalGatewayRouteTable = LocalGatewayRouteTable_;
  export type LocalGatewayRouteTableVPCAssociation = LocalGatewayRouteTableVPCAssociation_;
  export type LocalGatewayRouteTableVirtualInterfaceGroupAssociation =
    LocalGatewayRouteTableVirtualInterfaceGroupAssociation_;
  export type LocalGatewayVirtualInterface = LocalGatewayVirtualInterface_;
  export type LocalGatewayVirtualInterfaceGroup = LocalGatewayVirtualInterfaceGroup_;
  export type NatGateway = NatGateway_;
  export type NetworkAcl = NetworkAcl_;
  export type NetworkAclEntry = NetworkAclEntry_;
  export type NetworkInsightsAccessScope = NetworkInsightsAccessScope_;
  export type NetworkInsightsAccessScopeAnalysis = NetworkInsightsAccessScopeAnalysis_;
  export type NetworkInsightsAnalysis = NetworkInsightsAnalysis_;
  export type NetworkInsightsPath = NetworkInsightsPath_;
  export type NetworkInterface = NetworkInterface_;
  export type NetworkInterfaceAttachment = NetworkInterfaceAttachment_;
  export type NetworkInterfacePermission = NetworkInterfacePermission_;
  export type NetworkPerformanceMetricSubscription = NetworkPerformanceMetricSubscription_;
  export type PlacementGroup = PlacementGroup_;
  export type PrefixList = PrefixList_;
  export type Route = Route_;
  export type RouteServer = RouteServer_;
  export type RouteServerAssociation = RouteServerAssociation_;
  export type RouteServerEndpoint = RouteServerEndpoint_;
  export type RouteServerPeer = RouteServerPeer_;
  export type RouteServerPropagation = RouteServerPropagation_;
  export type RouteTable = RouteTable_;
  export type SecurityGroup = SecurityGroup_;
  export type SecurityGroupEgress = SecurityGroupEgress_;
  export type SecurityGroupIngress = SecurityGroupIngress_;
  export type SecurityGroupVpcAssociation = SecurityGroupVpcAssociation_;
  export type SnapshotBlockPublicAccess = SnapshotBlockPublicAccess_;
  export type SpotFleet = SpotFleet_;
  export type Subnet = Subnet_;
  export type SubnetCidrBlock = SubnetCidrBlock_;
  export type SubnetNetworkAclAssociation = SubnetNetworkAclAssociation_;
  export type SubnetRouteTableAssociation = SubnetRouteTableAssociation_;
  export type TrafficMirrorFilter = TrafficMirrorFilter_;
  export type TrafficMirrorFilterRule = TrafficMirrorFilterRule_;
  export type TrafficMirrorSession = TrafficMirrorSession_;
  export type TrafficMirrorTarget = TrafficMirrorTarget_;
  export type TransitGateway = TransitGateway_;
  export type TransitGatewayAttachment = TransitGatewayAttachment_;
  export type TransitGatewayConnect = TransitGatewayConnect_;
  export type TransitGatewayConnectPeer = TransitGatewayConnectPeer_;
  export type TransitGatewayMulticastDomain = TransitGatewayMulticastDomain_;
  export type TransitGatewayMulticastDomainAssociation = TransitGatewayMulticastDomainAssociation_;
  export type TransitGatewayMulticastGroupMember = TransitGatewayMulticastGroupMember_;
  export type TransitGatewayMulticastGroupSource = TransitGatewayMulticastGroupSource_;
  export type TransitGatewayPeeringAttachment = TransitGatewayPeeringAttachment_;
  export type TransitGatewayRoute = TransitGatewayRoute_;
  export type TransitGatewayRouteTable = TransitGatewayRouteTable_;
  export type TransitGatewayRouteTableAssociation = TransitGatewayRouteTableAssociation_;
  export type TransitGatewayRouteTablePropagation = TransitGatewayRouteTablePropagation_;
  export type TransitGatewayVpcAttachment = TransitGatewayVpcAttachment_;
  export type VPC = VPC_;
  export type VPCBlockPublicAccessExclusion = VPCBlockPublicAccessExclusion_;
  export type VPCBlockPublicAccessOptions = VPCBlockPublicAccessOptions_;
  export type VPCCidrBlock = VPCCidrBlock_;
  export type VPCDHCPOptionsAssociation = VPCDHCPOptionsAssociation_;
  export type VPCEndpoint = VPCEndpoint_;
  export type VPCEndpointConnectionNotification = VPCEndpointConnectionNotification_;
  export type VPCEndpointService = VPCEndpointService_;
  export type VPCEndpointServicePermissions = VPCEndpointServicePermissions_;
  export type VPCGatewayAttachment = VPCGatewayAttachment_;
  export type VPCPeeringConnection = VPCPeeringConnection_;
  export type VPNConnection = VPNConnection_;
  export type VPNConnectionRoute = VPNConnectionRoute_;
  export type VPNGateway = VPNGateway_;
  export type VPNGatewayRoutePropagation = VPNGatewayRoutePropagation_;
  export type VerifiedAccessEndpoint = VerifiedAccessEndpoint_;
  export type VerifiedAccessGroup = VerifiedAccessGroup_;
  export type VerifiedAccessInstance = VerifiedAccessInstance_;
  export type VerifiedAccessTrustProvider = VerifiedAccessTrustProvider_;
  export type Volume = Volume_;
  export type VolumeAttachment = VolumeAttachment_;
}
