import AggregatorV2_ from './aggregatorV2';
import AutomationRule_ from './automationRule';
import AutomationRuleV2_ from './automationRuleV2';
import ConfigurationPolicy_ from './configurationPolicy';
import DelegatedAdmin_ from './delegatedAdmin';
import FindingAggregator_ from './findingAggregator';
import Hub_ from './hub';
import HubV2_ from './hubV2';
import Insight_ from './insight';
import OrganizationConfiguration_ from './organizationConfiguration';
import PolicyAssociation_ from './policyAssociation';
import ProductSubscription_ from './productSubscription';
import SecurityControl_ from './securityControl';
import Standard_ from './standard';
export namespace SecurityHub {
  export const AggregatorV2 = AggregatorV2_;
  export const AutomationRule = AutomationRule_;
  export const AutomationRuleV2 = AutomationRuleV2_;
  export const ConfigurationPolicy = ConfigurationPolicy_;
  export const DelegatedAdmin = DelegatedAdmin_;
  export const FindingAggregator = FindingAggregator_;
  export const Hub = Hub_;
  export const HubV2 = HubV2_;
  export const Insight = Insight_;
  export const OrganizationConfiguration = OrganizationConfiguration_;
  export const PolicyAssociation = PolicyAssociation_;
  export const ProductSubscription = ProductSubscription_;
  export const SecurityControl = SecurityControl_;
  export const Standard = Standard_;
  export type AggregatorV2 = AggregatorV2_;
  export type AutomationRule = AutomationRule_;
  export type AutomationRuleV2 = AutomationRuleV2_;
  export type ConfigurationPolicy = ConfigurationPolicy_;
  export type DelegatedAdmin = DelegatedAdmin_;
  export type FindingAggregator = FindingAggregator_;
  export type Hub = Hub_;
  export type HubV2 = HubV2_;
  export type Insight = Insight_;
  export type OrganizationConfiguration = OrganizationConfiguration_;
  export type PolicyAssociation = PolicyAssociation_;
  export type ProductSubscription = ProductSubscription_;
  export type SecurityControl = SecurityControl_;
  export type Standard = Standard_;
}
