// Long-running section batch generator with adaptive concurrency and
// rate-limit-aware retries.
//
// Pass one --anchor per scope you want to process. Each anchor must already be
// passed (review it first via `--onlyPage <route>` in the main pipeline). The
// scope is derived from the anchor route. For resource pages, that means the
// resource category, e.g. resources/compute. Scopes are processed in anchor order.
//
// Concurrency is adaptive — starts at 2, halves on rate-limit (floor 1), and
// increments by 1 after 3 consecutive successes (cap 4).
//
// Usage:
//   bun run scripts/generate-docs/generate-section-batch.ts \
//     --anchor resources/compute/web-service \
//     --anchor packaging/overview \
//     [--scope resources] [--maxIterations 3] [--maxHours 24] [--dryRun]

import { appendFile, ensureDir, pathExists, readFile } from 'fs-extra';
import { join } from 'node:path';
import { buildAgentModelConfigFromArgv, formatAgentModelConfigForLog } from './agent-models';
import { getAllArgValues, getArgValue, getNumberArg, getPositiveIntegerArg, hasFlag } from './cli-args';
import { detectPageStatus } from './page-status';
import { pageDefinitions } from './pages';
import { runPagePipeline } from './run-page';
import { detectStaleness } from './staleness';
import { loadState } from './state';
import type { PageDefinition } from './types';

const STATE_DIR = join(import.meta.dir, '.state');

// Patterns that trigger backoff + concurrency-down. Broadened after the second long batch
// run hung silently — the Claude CLI returned an error that didn't match any of these and
// the page-level retry never fired. Better to over-match (more retries) than to miss
// throttling signals and stall.
const RATE_LIMIT_PATTERNS = [
  'usage limit',
  'hit your limit',
  'upgrade to pro',
  'purchase more credits',
  'rate limit',
  'rate_limit',
  'ratelimit',
  'quota',
  '429',
  'too many requests',
  'limit reached',
  'limit exceeded',
  'reached your',
  'approaching',
  'reset at',
  'reset in',
  'resets ',
  'try again later',
  'retry after',
  'cli timeout', // our own timeout signal from providers.runCommand
  'killed subprocess',
  'overloaded',
  'capacity'
];

const isRateLimitError = (err: unknown): boolean => {
  const m = (err instanceof Error ? err.message : String(err)).toLowerCase();
  return RATE_LIMIT_PATTERNS.some((p) => m.includes(p));
};

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

const getBatchScope = (page: PageDefinition) => {
  const [topLevel, secondLevel] = page.route.split('/');
  if (topLevel === 'resources') {
    return secondLevel ? `${topLevel}/${secondLevel}` : topLevel;
  }
  if (topLevel === 'packaging' && secondLevel && secondLevel !== 'overview') {
    return `${topLevel}/${secondLevel}`;
  }
  if (topLevel === 'configuration' && secondLevel === 'triggers') {
    return `${topLevel}/${secondLevel}`;
  }
  return topLevel || 'root';
};

const isRouteInScope = (route: string, scope: string) => route === scope || route.startsWith(`${scope}/`);

const hasPassedOutput = async (page: PageDefinition): Promise<boolean> => {
  if (!(await pathExists(page.outputPath))) return false;
  const body = await readFile(page.outputPath, 'utf8');
  if (body.includes('{/* Placeholder generated by docs pipeline. */}')) return false;
  if (/^pipelineStatus:\s*'?did-not-pass'?/m.test(body)) return false;
  const state = await loadState({ pageId: page.id });
  return Boolean(state?.completedAt);
};

const isFreshPassedPage = async (page: PageDefinition) =>
  (await hasPassedOutput(page)) && (await detectPageStatus(page, { checkStaleness: true })) === 'passed';

const isStyleGuideOnlyStalePassedPage = async (page: PageDefinition) => {
  if (!(await hasPassedOutput(page))) return false;
  const report = await detectStaleness({ page });
  return (
    report.status === 'stale' &&
    report.styleGuideChanged &&
    report.changedFiles.length === 0 &&
    report.removedFiles.length === 0 &&
    report.newFiles.length === 0
  );
};

const isUsableAnchorPage = async (page: PageDefinition) =>
  (await isFreshPassedPage(page)) || (await isStyleGuideOnlyStalePassedPage(page));

const isGeneratedOutputToSkip = async (page: PageDefinition) => {
  const status = await detectPageStatus(page, { checkStaleness: true });
  return status === 'passed' || status === 'needs-human-review' || (await isStyleGuideOnlyStalePassedPage(page));
};

// Adaptive concurrency controller. AIMD: additive +1 increase, multiplicative
// halve on a rate-limit signal. Floor 1, cap 4. Concurrency higher than 4 has
// not been useful in practice — each page already fires 4 reviewers + 2
// verifiers in parallel internally, so 4 pages × ~5 concurrent CLI calls is
// already a lot of pressure on the Claude/Codex windows.
class AdaptiveConcurrency {
  private value: number;
  private consecutiveSuccesses = 0;
  constructor(
    public readonly min: number,
    public readonly max: number,
    initial: number
  ) {
    this.value = initial;
  }
  current() {
    return this.value;
  }
  onPageSuccess(): { changed: boolean; newValue: number } {
    this.consecutiveSuccesses++;
    if (this.consecutiveSuccesses >= 3 && this.value < this.max) {
      this.consecutiveSuccesses = 0;
      this.value += 1;
      return { changed: true, newValue: this.value };
    }
    return { changed: false, newValue: this.value };
  }
  onRateLimit(): { changed: boolean; newValue: number } {
    this.consecutiveSuccesses = 0;
    const next = Math.max(this.min, Math.floor(this.value / 2));
    if (next !== this.value) {
      this.value = next;
      return { changed: true, newValue: this.value };
    }
    return { changed: false, newValue: this.value };
  }
  onPageFailure() {
    this.consecutiveSuccesses = 0;
  }
}

const main = async () => {
  const argv = process.argv;
  const anchorRoutes = getAllArgValues(argv, '--anchor');
  const explicitScope = getArgValue(argv, '--scope');
  const maxIterations = getPositiveIntegerArg(argv, '--maxIterations', 3);
  const maxHours = getNumberArg(argv, '--maxHours', 24);
  if (maxHours <= 0) {
    throw new Error(`--maxHours must be greater than 0, got "${maxHours}".`);
  }
  // Optional hard cap on number of pages this run will attempt. Useful for short evals
  // ("try 3 pages with the new settings") without committing to the full section.
  const maxPages = hasFlag(argv, '--maxPages') ? getPositiveIntegerArg(argv, '--maxPages', 1) : Infinity;
  // Starting concurrency. AIMD scaling still applies (halve on rate-limit, +1 after 3 successes).
  // Defaults to 2; capped by AdaptiveConcurrency at 4.
  const initialConcurrency = getPositiveIntegerArg(argv, '--concurrency', 2);
  // Model overrides per agent role. Defaults: writer/verifiers use their CLI defaults, reviewers
  // default to Sonnet. See agent-models.ts for supported flags.
  const agentModels = buildAgentModelConfigFromArgv(argv);
  const dryRun = hasFlag(argv, '--dryRun');

  if (anchorRoutes.length === 0) {
    throw new Error(
      'At least one --anchor is required. Each anchor is the route of an already-passed page; ' +
      'its generation scope will be batched. Use --scope <route-prefix> to intentionally widen or narrow the scope. ' +
      'Example: --anchor resources/compute/web-service --scope resources'
    );
  }
  if (explicitScope && anchorRoutes.length > 1) {
    throw new Error('--scope can only be used with one --anchor. Run separate batches for multiple explicit scopes.');
  }

  // Build per-scope plans, preserving anchor order.
  type ScopePlan = { scope: string; anchorPage: PageDefinition; queue: PageDefinition[] };
  const scopePlans: ScopePlan[] = [];
  const seenScopes = new Set<string>();
  for (const anchorRoute of anchorRoutes) {
    const anchorPage = pageDefinitions.find((p) => p.route === anchorRoute);
    if (!anchorPage) throw new Error(`--anchor route "${anchorRoute}" not in pageDefinitions.`);
    const scope = explicitScope || getBatchScope(anchorPage);
    if (explicitScope && !isRouteInScope(anchorPage.route, explicitScope)) {
      throw new Error(`--scope ${explicitScope} does not contain anchor route ${anchorRoute}.`);
    }
    if (seenScopes.has(scope)) {
      throw new Error(`Scope "${scope}" specified twice (anchors ${anchorRoute} and an earlier one).`);
    }
    const anchorStatus = await detectPageStatus(anchorPage, { checkStaleness: true });
    if (!(await isUsableAnchorPage(anchorPage))) {
      throw new Error(
        `Anchor ${anchorRoute} must be passed and fresh before section batch generation; current status is ${anchorStatus}. ` +
        `Generate it first: bun run scripts/generate-docs/generate-pages.ts --onlyPage ${anchorRoute}`
      );
    }
    if (anchorStatus === 'passed-stale') {
      console.warn(`Anchor ${anchorRoute} is stale only because the style guide changed; using it as the batch example.`);
    }
    const pagesInScope = pageDefinitions.filter((p) =>
      (explicitScope ? isRouteInScope(p.route, explicitScope) : getBatchScope(p) === scope) && p.route !== anchorRoute
    );
    const queue: PageDefinition[] = [];
    for (const page of pagesInScope) {
      if (!(await isGeneratedOutputToSkip(page))) queue.push(page);
    }
    scopePlans.push({ scope, anchorPage, queue });
    seenScopes.add(scope);
  }

  const startedAt = Date.now();
  const hardStopMs = maxHours * 3600_000;

  await ensureDir(STATE_DIR);
  const runId = new Date().toISOString().replace(/[:.]/g, '-');
  const logSlug = scopePlans.map((p) => p.scope.replaceAll('/', '-')).join('+');
  const logPath = join(STATE_DIR, `section-batch-${logSlug}-${runId}.log`);
  const log = async (line: string) => {
    const ts = new Date().toISOString();
    const entry = `[${ts}] ${line}\n`;
    process.stdout.write(entry);
    await appendFile(logPath, entry);
  };

  await log(
    `runId=${runId} maxIterations=${maxIterations} maxHours=${maxHours} maxPages=${
      Number.isFinite(maxPages) ? maxPages : '∞'
    } initialConcurrency=${initialConcurrency} scopes=${scopePlans.length} ${formatAgentModelConfigForLog(agentModels)}`
  );
  for (const plan of scopePlans) {
    await log(`  scope=${plan.scope} anchor=/${plan.anchorPage.route} queueSize=${plan.queue.length}`);
    for (const p of plan.queue) await log(`    queued /${p.route}`);
  }

  if (dryRun) {
    await log('dry-run, exiting without generating.');
    return;
  }

  const maxInitial = Math.max(1, Math.min(4, initialConcurrency));
  const concurrency = new AdaptiveConcurrency(1, Math.max(4, maxInitial), maxInitial);
  let consecutiveFailures = 0;
  const MAX_CONSECUTIVE_FAILURES = 5;
  let halted = false;
  let haltReason = '';
  // Counts every page that produced a result (passed or failed). Used to enforce --maxPages.
  let attemptedCount = 0;

  const allResults: Array<{
    scope: string;
    route: string;
    outcome: 'passed' | 'needs-human-review' | 'failed';
    iterations: number;
    error?: string;
  }> = [];

  // One processPage that closes over the current scope's anchorPath. Recreated
  // per scope so each scope's pages use that scope's anchor as the example.
  const makeProcessPage = (anchorPath: string, scope: string) => async (page: PageDefinition) => {
    let attempt = 0;
    // 15min → 1h → 4h → 8h. The deepest wait covers "resets at 5am" style
    // account windows without abandoning the batch before the reset.
    const backoffsMs = [15 * 60_000, 60 * 60_000, 4 * 3600_000, 8 * 3600_000];
    while (true) {
      attempt++;
      try {
        await log(`>>> START /${page.route} (attempt ${attempt}, concurrency=${concurrency.current()})`);
        const result = await runPagePipeline({
          page,
          maxIterations,
          examplePath: anchorPath,
          force: true,
          agentModels
        });
        const label = result.outcome === 'passed' ? 'PASS' : result.outcome === 'needs-human-review' ? 'REVIEW' : 'FAIL';
        await log(`<<< ${label} /${page.route} (${result.iterations} iter)`);
        allResults.push({ scope, route: page.route, outcome: result.outcome, iterations: result.iterations });
        attemptedCount += 1;
        if (result.outcome === 'passed') {
          consecutiveFailures = 0;
          const change = concurrency.onPageSuccess();
          if (change.changed) await log(`    concurrency ↑ → ${change.newValue} (3 consecutive successes)`);
        } else if (result.outcome === 'needs-human-review') {
          consecutiveFailures = 0;
          concurrency.onPageFailure();
        } else {
          consecutiveFailures++;
          concurrency.onPageFailure();
        }
        return;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (isRateLimitError(err)) {
          const change = concurrency.onRateLimit();
          if (change.changed) await log(`    concurrency ↓ → ${change.newValue} (rate-limit signal)`);
          if (attempt <= backoffsMs.length) {
            const waitMs = backoffsMs[attempt - 1];
            await log(`!!! RATE-LIMIT /${page.route} attempt ${attempt}: ${msg.slice(0, 200)} — sleeping ${Math.round(waitMs / 60_000)}min`);
            if (Date.now() + waitMs > startedAt + hardStopMs) {
              await log(`!!! /${page.route} would resume after maxHours; aborting page.`);
              allResults.push({
                scope,
                route: page.route,
                outcome: 'failed',
                iterations: 0,
                error: 'rate-limit, would resume after maxHours'
              });
              consecutiveFailures++;
              return;
            }
            await sleep(waitMs);
            continue;
          }
        }
        await log(`!!! ERROR /${page.route}: ${msg.slice(0, 400)}`);
        allResults.push({ scope, route: page.route, outcome: 'failed', iterations: 0, error: msg.slice(0, 200) });
        attemptedCount += 1;
        consecutiveFailures++;
        concurrency.onPageFailure();
        return;
      }
    }
  };

  for (const plan of scopePlans) {
    if (halted) break;
    if (plan.queue.length === 0) {
      await log(`Scope ${plan.scope}: nothing to do, all pages already passed or waiting for human review.`);
      continue;
    }
    await log(`=== Scope ${plan.scope}: starting ${plan.queue.length} page(s), anchor=/${plan.anchorPage.route} ===`);

    const queue = plan.queue;
    let nextIdx = 0;
    let inFlight = 0;
    const processPage = makeProcessPage(plan.anchorPage.outputPath, plan.scope);

    await new Promise<void>((resolveSection) => {
      const tryLaunch = () => {
        if (halted) {
          if (inFlight === 0) resolveSection();
          return;
        }
        if (Date.now() - startedAt >= hardStopMs) {
          halted = true;
          haltReason = `maxHours (${maxHours}h)`;
          log(`*** STOP — ${haltReason}`).catch(() => {});
          if (inFlight === 0) resolveSection();
          return;
        }
        if (consecutiveFailures >= MAX_CONSECUTIVE_FAILURES) {
          halted = true;
          haltReason = `${MAX_CONSECUTIVE_FAILURES} consecutive failures`;
          log(`*** STOP — ${haltReason}`).catch(() => {});
          if (inFlight === 0) resolveSection();
          return;
        }
        // --maxPages cap: count attempted + currently-in-flight. Stops launching once we'd
        // exceed the cap, but lets in-flight pages finish so we get a clean accounting.
        if (attemptedCount + inFlight >= maxPages) {
          if (inFlight === 0) {
            halted = true;
            haltReason = `maxPages (${maxPages}) reached`;
            log(`*** STOP — ${haltReason}`).catch(() => {});
            resolveSection();
            return;
          }
          // Still pages in flight — wait for them, no new launches.
          return;
        }
        while (inFlight < concurrency.current() && nextIdx < queue.length && !halted && attemptedCount + inFlight < maxPages) {
          const page = queue[nextIdx++];
          inFlight++;
          processPage(page).finally(() => {
            inFlight--;
            tryLaunch();
          });
        }
        if (nextIdx >= queue.length && inFlight === 0) resolveSection();
      };
      tryLaunch();
    });
  }

  const passed = allResults.filter((r) => r.outcome === 'passed').length;
  const review = allResults.filter((r) => r.outcome === 'needs-human-review').length;
  const failed = allResults.filter((r) => r.outcome === 'failed').length;
  const totalQueued = scopePlans.reduce((sum, p) => sum + p.queue.length, 0);
  const skipped = totalQueued - allResults.length;
  await log(
    `SUMMARY ran=${allResults.length}/${totalQueued} passed=${passed} review=${review} failed=${failed} skipped=${skipped} elapsedMin=${Math.round((Date.now() - startedAt) / 60_000)} finalConcurrency=${concurrency.current()}${haltReason ? ` halt=${haltReason}` : ''}`
  );
  for (const r of allResults) {
    const label = r.outcome === 'passed' ? 'PASS' : r.outcome === 'needs-human-review' ? 'REVIEW' : 'FAIL';
    await log(`  ${label} [${r.scope}] /${r.route} (${r.iterations} iter)${r.error ? ` — ${r.error}` : ''}`);
  }
  await log(`Log written to ${logPath}`);
};

if (import.meta.main) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
