import { pathExists, readFile, remove } from 'fs-extra';
import { isAbsolute, relative, resolve } from 'node:path';
import { ensurePlaceholderPage } from './placeholders';
import { pageDefinitions, getPageByRoute } from './pages';
import { runPagePipeline } from './run-page';
import { detectStaleness } from './staleness';
import { getStatePath, loadState } from './state';
import type { PageDefinition } from './types';

const getArgValue = ({ flag }: { flag: string }) => {
  const index = process.argv.indexOf(flag);
  if (index === -1) {
    return null;
  }
  return process.argv[index + 1] || null;
};

const hasFlag = ({ flag }: { flag: string }) => process.argv.includes(flag);

const docsContentRoot = resolve(import.meta.dir, '..', '..', 'docs');

const getPageSection = (route: string) => route.split('/')[0] || 'index';

const getExampleRoute = (examplePath: string) => {
  const relativeExamplePath = relative(docsContentRoot, examplePath);
  if (relativeExamplePath.startsWith('..') || isAbsolute(relativeExamplePath) || !relativeExamplePath.endsWith('.mdx')) {
    return undefined;
  }
  return relativeExamplePath.replace(/\\/g, '/').replace(/\.mdx$/, '');
};

const runBatch = async <T, R>(items: T[], concurrency: number, fn: (item: T) => Promise<R>): Promise<R[]> => {
  const results: R[] = [];
  for (let i = 0; i < items.length; i += concurrency) {
    const batch = items.slice(i, i + concurrency);
    const batchResults = await Promise.all(batch.map(fn));
    results.push(...batchResults);
  }
  return results;
};

type PageStatus = 'passed' | 'passed-stale' | 'failed' | 'placeholder' | 'missing';

const detectPageStatus = async (
  page: PageDefinition,
  options: { checkStaleness?: boolean } = {}
): Promise<PageStatus> => {
  if (!(await pathExists(page.outputPath))) {
    return 'missing';
  }
  const content = await readFile(page.outputPath, 'utf8');
  if (content.includes('{/* Placeholder generated by docs pipeline. */}')) {
    return 'placeholder';
  }
  if (/^pipelineStatus:\s*'?did-not-pass'?\s*$/m.test(content)) {
    return 'failed';
  }
  const state = await loadState({ pageId: page.id });
  if (state?.completedAt) {
    if (options.checkStaleness) {
      const report = await detectStaleness({ page });
      if (report.status === 'stale' || report.status === 'no-baseline') {
        return 'passed-stale';
      }
    }
    return 'passed';
  }
  if (state?.iterations.length) {
    return 'failed';
  }
  // Output exists but no pipeline state — page was authored outside the pipeline.
  // Surface as "passed-stale" when staleness checks are on so it still gets pulled
  // into --onlyPending / --onlyStale runs.
  if (options.checkStaleness) {
    return 'passed-stale';
  }
  return 'passed';
};

// Patterns that indicate the page violates the canonical Stacktape config style.
// If any of these match the body of an output page, we treat the page as failed regardless of state.
const stacktapeConfigYamlBlock = /```ya?ml[\s\S]*?\nresources:\s*\n[\s\S]*?```/;
const stacktapeConfigPlainObject = /\bStacktapeConfig\b/;
const stacktapeConfigFencedTs = /```(?:typescript|ts)[\s\S]*?(?:defineConfig\s*\(|new\s+(?:Lambda|Web|Worker|Private|Multi|Batch|Edge|Static|Nextjs|Astro|Nuxt|SvelteKit|SolidStart|TanStack|Remix|Relational|DynamoDb|Redis|MongoDb|Upstash|OpenSearch|Bucket|Hosting|Efs|HttpApi|Application|Network|Cdn|EventBus|SqsQueue|SnsTopic|Kinesis|StateMachine|UserAuth|WebApp|Bastion|Custom|Deployment|AwsCdk)[A-Za-z]*\s*\([\s\S]*?{)/;

const detectStyleViolations = (body: string): string[] => {
  const violations: string[] = [];
  if (stacktapeConfigYamlBlock.test(body)) {
    violations.push('YAML Stacktape config block (forbidden — use TypeScript class-based <CodeBlock intellisense ... />)');
  }
  if (stacktapeConfigPlainObject.test(body)) {
    violations.push('plain-object StacktapeConfig style (forbidden — use defineConfig + class-based resources)');
  }
  if (stacktapeConfigFencedTs.test(body)) {
    violations.push('Stacktape config in a fenced ```typescript block (forbidden — use <CodeBlock intellisense ... />)');
  }
  return violations;
};

const invalidatePassedPages = async ({ pages, dryRun }: { pages: PageDefinition[]; dryRun: boolean }) => {
  let matched = 0;
  for (const page of pages) {
    if (!(await pathExists(page.outputPath))) continue;
    const body = await readFile(page.outputPath, 'utf8');
    const violations = detectStyleViolations(body);
    if (violations.length === 0) continue;
    matched += 1;
    if (dryRun) {
      console.info(`  Would invalidate /${page.route}: ${violations.join('; ')}`);
      continue;
    }
    const statePath = getStatePath({ pageId: page.id });
    if (await pathExists(statePath)) {
      await remove(statePath);
    }
    await remove(page.outputPath);
    await ensurePlaceholderPage({ page });
    console.info(`  Invalidated /${page.route}: ${violations.join('; ')}`);
  }
  if (dryRun) {
    console.info(`\nDry run: ${matched} page(s) would be invalidated. Re-run with --invalidatePassed (no --dryRun) to actually invalidate.`);
  } else {
    console.info(`\nInvalidated ${matched} page(s). Re-run the pipeline (e.g. --onlyPending) to regenerate them.`);
  }
};

const printStatusReport = async ({
  pages,
  filter,
  checkStaleness
}: {
  pages: PageDefinition[];
  filter?: 'failed' | 'pending' | 'stale';
  checkStaleness?: boolean;
}) => {
  const rows = await Promise.all(
    pages.map(async (page) => ({ page, status: await detectPageStatus(page, { checkStaleness }) }))
  );
  const counts = rows.reduce(
    (acc, row) => {
      acc[row.status] = (acc[row.status] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );

  const filtered = filter
    ? rows.filter((row) => {
        if (filter === 'failed') return row.status === 'failed';
        if (filter === 'stale') return row.status === 'passed-stale';
        return row.status === 'placeholder' || row.status === 'missing';
      })
    : rows;

  console.info(`\n--- Status (${rows.length} pages) ---`);
  console.info(`  passed: ${counts.passed || 0}`);
  if (checkStaleness) {
    console.info(`  passed (stale): ${counts['passed-stale'] || 0}`);
  }
  console.info(`  failed: ${counts.failed || 0}`);
  console.info(`  placeholder: ${counts.placeholder || 0}`);
  console.info(`  missing: ${counts.missing || 0}`);

  if (filtered.length > 0) {
    console.info('');
    for (const row of filtered) {
      console.info(`  [${row.status}] /${row.page.route}`);
    }
  }
};

const main = async () => {
  const onlyPage = getArgValue({ flag: '--onlyPage' });
  const maxIterations = Number(getArgValue({ flag: '--maxIterations' }) || '3');
  const concurrency = Number(getArgValue({ flag: '--concurrency' }) || '1');
  const prepareOnly = hasFlag({ flag: '--prepareOnly' });
  const listFailed = hasFlag({ flag: '--listFailed' });
  const listPending = hasFlag({ flag: '--listPending' });
  const listStale = hasFlag({ flag: '--listStale' });
  const showStatus = hasFlag({ flag: '--status' });
  const showStatusWithStaleness = hasFlag({ flag: '--statusWithStaleness' });
  const onlyFailed = hasFlag({ flag: '--onlyFailed' });
  const onlyPending = hasFlag({ flag: '--onlyPending' });
  const onlyStale = hasFlag({ flag: '--onlyStale' });
  const invalidatePassed = hasFlag({ flag: '--invalidatePassed' });
  const dryRun = hasFlag({ flag: '--dryRun' });
  const exampleArg = getArgValue({ flag: '--example' });
  const examplePath = exampleArg ? resolve(process.cwd(), exampleArg) : undefined;

  if (showStatus || showStatusWithStaleness || listFailed || listPending || listStale) {
    await printStatusReport({
      pages: pageDefinitions,
      filter: listFailed ? 'failed' : listPending ? 'pending' : listStale ? 'stale' : undefined,
      checkStaleness: showStatusWithStaleness || listStale
    });
    return;
  }

  if (invalidatePassed) {
    await invalidatePassedPages({ pages: pageDefinitions, dryRun });
    return;
  }

  if (examplePath && !(await pathExists(examplePath))) {
    throw new Error(`--example path does not exist: ${exampleArg} (resolved to ${examplePath})`);
  }

  const exampleRoute = examplePath ? getExampleRoute(examplePath) : undefined;
  const exampleSection = exampleRoute ? getPageSection(exampleRoute) : undefined;
  let pages = onlyPage ? [getPageByRoute(onlyPage)].filter(Boolean) : pageDefinitions;
  if (examplePath && !onlyPage && exampleSection) {
    pages = pages.filter((page) => getPageSection(page.route) === exampleSection && page.route !== exampleRoute);
  } else if (examplePath && !onlyPage && !exampleSection) {
    console.warn(`Could not infer docs section from --example path; generating all selected pages with the example.`);
  }

  if (onlyFailed || onlyPending || onlyStale) {
    const checkStaleness = onlyPending || onlyStale;
    const statusRows = await Promise.all(
      (pages.filter(Boolean) as PageDefinition[]).map(async (page) => ({
        page,
        status: await detectPageStatus(page, { checkStaleness })
      }))
    );
    pages = statusRows
      .filter((row) => {
        if (onlyFailed) return row.status === 'failed';
        if (onlyStale) return row.status === 'passed-stale';
        // onlyPending: anything that needs work — placeholder, missing, failed, or stale.
        return (
          row.status === 'placeholder' ||
          row.status === 'missing' ||
          row.status === 'failed' ||
          row.status === 'passed-stale'
        );
      })
      .map((row) => row.page);
    const filterLabel = onlyFailed ? 'failed' : onlyStale ? 'stale' : 'pending';
    console.info(`Filtered to ${pages.length} ${filterLabel} page(s).`);
  }

  if (pages.length === 0) {
    throw new Error(
      onlyPage
        ? `No docs page matched --onlyPage ${onlyPage}`
        : onlyFailed
          ? 'No failed pages to retry.'
          : onlyStale
            ? 'No stale pages to regenerate.'
            : onlyPending
              ? 'No pending pages to generate.'
              : `No docs pages matched the section inferred from --example ${exampleArg}`
    );
  }

  console.info(
    `Docs pipeline: ${pages.length} page(s), maxIterations=${maxIterations}, concurrency=${concurrency}${
      examplePath ? `, example=${examplePath}` : ''
    }${exampleSection && !onlyPage ? `, section=${exampleSection}, excludingExample=${exampleRoute}` : ''}`
  );

  for (const page of pages) {
    await ensurePlaceholderPage({ page: page! });
  }

  if (prepareOnly) {
    console.info(`Prepared ${pages.length} page placeholders.`);
    return;
  }

  const results = await runBatch(
    pages.filter(Boolean) as NonNullable<(typeof pages)[number]>[],
    concurrency,
    async (page) => {
      console.info(`\nGenerating /${page.route} (${page.kind}, ${page.template})`);
      // Bypass the "already completed" short-circuit in runPagePipeline whenever the user
      // explicitly asked for regeneration: --onlyStale (sources drifted) or --onlyPage (named
      // a specific route). For --onlyFailed / --onlyPending, prior state has no completedAt
      // and no force is needed.
      const force = onlyStale || Boolean(onlyPage);
      const result = await runPagePipeline({ page, maxIterations, examplePath, force });
      console.info(
        result.passed
          ? `  PASSED /${page.route} in ${result.iterations} iteration(s).`
          : `  DID NOT PASS /${page.route} after ${result.iterations} iteration(s). Best draft written to output.`
      );
      return { route: page.route, passed: result.passed, iterations: result.iterations };
    }
  );

  console.info('\n--- Summary ---');
  for (const r of results) {
    console.info(`  ${r.passed ? 'PASS' : 'FAIL'} /${r.route} (${r.iterations} iterations)`);
  }
  console.info(`  ${results.filter((r) => r.passed).length}/${results.length} pages passed.`);
};

if (import.meta.main) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
