import { pathExists, readFile } from 'fs-extra';
import { detectStaleness } from './staleness';
import { loadState } from './state';
import type { PageDefinition } from './types';

export type PageStatus = 'passed' | 'passed-stale' | 'needs-human-review' | 'failed' | 'placeholder' | 'missing';

export const detectPageStatus = async (
  page: PageDefinition,
  options: { checkStaleness?: boolean } = {}
): Promise<PageStatus> => {
  if (!(await pathExists(page.outputPath))) {
    return 'missing';
  }
  const content = await readFile(page.outputPath, 'utf8');
  if (content.includes('{/* Placeholder generated by docs pipeline. */}')) {
    return 'placeholder';
  }
  if (/^pipelineStatus:\s*'?did-not-pass'?\s*$/m.test(content)) {
    return 'failed';
  }
  if (/^pipelineStatus:\s*'?needs-human-review'?\s*$/m.test(content)) {
    return 'needs-human-review';
  }
  const state = await loadState({ pageId: page.id });
  if (state?.completedAt) {
    if (options.checkStaleness) {
      const report = await detectStaleness({ page });
      if (report.status === 'stale' || report.status === 'no-baseline') {
        return 'passed-stale';
      }
    }
    return 'passed';
  }
  if (state?.iterations.length) {
    return 'failed';
  }
  // Output exists but no pipeline state. Treat it as needing generation when the caller asks
  // for staleness-aware status so batch runs do not silently skip hand-authored or legacy pages.
  return options.checkStaleness ? 'passed-stale' : 'passed';
};

export const isPendingStatus = (status: PageStatus) =>
  status === 'placeholder' || status === 'missing' || status === 'failed' || status === 'passed-stale';
