import { ensureDir, pathExists, readFile, writeFile } from 'fs-extra';
import { dirname } from 'node:path';
import type { PageDefinition } from './types';

const PLACEHOLDER_MARKER = '{/* Placeholder generated by docs pipeline. */}';

const createPlaceholderContent = ({ page }: { page: PageDefinition }) => `---
title: '${page.title.replaceAll("'", "''")}'
order: ${page.order}
---

# ${page.title}

${PLACEHOLDER_MARKER}

This page is coming soon.
`;

export const ensurePlaceholderPage = async ({ page }: { page: PageDefinition }) => {
  await ensureDir(dirname(page.outputPath));
  if (await pathExists(page.outputPath)) {
    // If the existing file IS a placeholder, refresh it so frontmatter (title, order) tracks
    // the current pages.ts. Real generated content is left alone.
    const existing = await readFile(page.outputPath, 'utf8');
    if (existing.includes(PLACEHOLDER_MARKER)) {
      await writeFile(page.outputPath, createPlaceholderContent({ page }));
    }
    return;
  }
  await writeFile(page.outputPath, createPlaceholderContent({ page }));
};
