import { ensureDir, pathExists, writeFile } from 'fs-extra';
import { dirname } from 'node:path';
import type { PageDefinition } from './types';

const createPlaceholderContent = ({ page }: { page: PageDefinition }) => `---
title: '${page.title.replaceAll("'", "''")}'
order: ${page.order}
---

# ${page.title}

{/* Placeholder generated by docs pipeline. */}

This page is coming soon.
`;

export const ensurePlaceholderPage = async ({ page }: { page: PageDefinition }) => {
  await ensureDir(dirname(page.outputPath));
  if (await pathExists(page.outputPath)) {
    return;
  }
  await writeFile(page.outputPath, createPlaceholderContent({ page }));
};
