import ConnectAttachment_ from './connectAttachment';
import ConnectPeer_ from './connectPeer';
import CoreNetwork_ from './coreNetwork';
import CustomerGatewayAssociation_ from './customerGatewayAssociation';
import Device_ from './device';
import DirectConnectGatewayAttachment_ from './directConnectGatewayAttachment';
import GlobalNetwork_ from './globalNetwork';
import Link_ from './link';
import LinkAssociation_ from './linkAssociation';
import Site_ from './site';
import SiteToSiteVpnAttachment_ from './siteToSiteVpnAttachment';
import TransitGatewayPeering_ from './transitGatewayPeering';
import TransitGatewayRegistration_ from './transitGatewayRegistration';
import TransitGatewayRouteTableAttachment_ from './transitGatewayRouteTableAttachment';
import VpcAttachment_ from './vpcAttachment';
export namespace NetworkManager {
  export const ConnectAttachment = ConnectAttachment_;
  export const ConnectPeer = ConnectPeer_;
  export const CoreNetwork = CoreNetwork_;
  export const CustomerGatewayAssociation = CustomerGatewayAssociation_;
  export const Device = Device_;
  export const DirectConnectGatewayAttachment = DirectConnectGatewayAttachment_;
  export const GlobalNetwork = GlobalNetwork_;
  export const Link = Link_;
  export const LinkAssociation = LinkAssociation_;
  export const Site = Site_;
  export const SiteToSiteVpnAttachment = SiteToSiteVpnAttachment_;
  export const TransitGatewayPeering = TransitGatewayPeering_;
  export const TransitGatewayRegistration = TransitGatewayRegistration_;
  export const TransitGatewayRouteTableAttachment = TransitGatewayRouteTableAttachment_;
  export const VpcAttachment = VpcAttachment_;
  export type ConnectAttachment = ConnectAttachment_;
  export type ConnectPeer = ConnectPeer_;
  export type CoreNetwork = CoreNetwork_;
  export type CustomerGatewayAssociation = CustomerGatewayAssociation_;
  export type Device = Device_;
  export type DirectConnectGatewayAttachment = DirectConnectGatewayAttachment_;
  export type GlobalNetwork = GlobalNetwork_;
  export type Link = Link_;
  export type LinkAssociation = LinkAssociation_;
  export type Site = Site_;
  export type SiteToSiteVpnAttachment = SiteToSiteVpnAttachment_;
  export type TransitGatewayPeering = TransitGatewayPeering_;
  export type TransitGatewayRegistration = TransitGatewayRegistration_;
  export type TransitGatewayRouteTableAttachment = TransitGatewayRouteTableAttachment_;
  export type VpcAttachment = VpcAttachment_;
}
