import App_ from './app';
import AppImageConfig_ from './appImageConfig';
import Cluster_ from './cluster';
import CodeRepository_ from './codeRepository';
import DataQualityJobDefinition_ from './dataQualityJobDefinition';
import Device_ from './device';
import DeviceFleet_ from './deviceFleet';
import Domain_ from './domain';
import Endpoint_ from './endpoint';
import EndpointConfig_ from './endpointConfig';
import FeatureGroup_ from './featureGroup';
import Image_ from './image';
import ImageVersion_ from './imageVersion';
import InferenceComponent_ from './inferenceComponent';
import InferenceExperiment_ from './inferenceExperiment';
import MlflowTrackingServer_ from './mlflowTrackingServer';
import Model_ from './model';
import ModelBiasJobDefinition_ from './modelBiasJobDefinition';
import ModelCard_ from './modelCard';
import ModelExplainabilityJobDefinition_ from './modelExplainabilityJobDefinition';
import ModelPackage_ from './modelPackage';
import ModelPackageGroup_ from './modelPackageGroup';
import ModelQualityJobDefinition_ from './modelQualityJobDefinition';
import MonitoringSchedule_ from './monitoringSchedule';
import NotebookInstance_ from './notebookInstance';
import NotebookInstanceLifecycleConfig_ from './notebookInstanceLifecycleConfig';
import PartnerApp_ from './partnerApp';
import Pipeline_ from './pipeline';
import ProcessingJob_ from './processingJob';
import Project_ from './project';
import Space_ from './space';
import StudioLifecycleConfig_ from './studioLifecycleConfig';
import UserProfile_ from './userProfile';
import Workteam_ from './workteam';
export namespace SageMaker {
  export const App = App_;
  export const AppImageConfig = AppImageConfig_;
  export const Cluster = Cluster_;
  export const CodeRepository = CodeRepository_;
  export const DataQualityJobDefinition = DataQualityJobDefinition_;
  export const Device = Device_;
  export const DeviceFleet = DeviceFleet_;
  export const Domain = Domain_;
  export const Endpoint = Endpoint_;
  export const EndpointConfig = EndpointConfig_;
  export const FeatureGroup = FeatureGroup_;
  export const Image = Image_;
  export const ImageVersion = ImageVersion_;
  export const InferenceComponent = InferenceComponent_;
  export const InferenceExperiment = InferenceExperiment_;
  export const MlflowTrackingServer = MlflowTrackingServer_;
  export const Model = Model_;
  export const ModelBiasJobDefinition = ModelBiasJobDefinition_;
  export const ModelCard = ModelCard_;
  export const ModelExplainabilityJobDefinition = ModelExplainabilityJobDefinition_;
  export const ModelPackage = ModelPackage_;
  export const ModelPackageGroup = ModelPackageGroup_;
  export const ModelQualityJobDefinition = ModelQualityJobDefinition_;
  export const MonitoringSchedule = MonitoringSchedule_;
  export const NotebookInstance = NotebookInstance_;
  export const NotebookInstanceLifecycleConfig = NotebookInstanceLifecycleConfig_;
  export const PartnerApp = PartnerApp_;
  export const Pipeline = Pipeline_;
  export const ProcessingJob = ProcessingJob_;
  export const Project = Project_;
  export const Space = Space_;
  export const StudioLifecycleConfig = StudioLifecycleConfig_;
  export const UserProfile = UserProfile_;
  export const Workteam = Workteam_;
  export type App = App_;
  export type AppImageConfig = AppImageConfig_;
  export type Cluster = Cluster_;
  export type CodeRepository = CodeRepository_;
  export type DataQualityJobDefinition = DataQualityJobDefinition_;
  export type Device = Device_;
  export type DeviceFleet = DeviceFleet_;
  export type Domain = Domain_;
  export type Endpoint = Endpoint_;
  export type EndpointConfig = EndpointConfig_;
  export type FeatureGroup = FeatureGroup_;
  export type Image = Image_;
  export type ImageVersion = ImageVersion_;
  export type InferenceComponent = InferenceComponent_;
  export type InferenceExperiment = InferenceExperiment_;
  export type MlflowTrackingServer = MlflowTrackingServer_;
  export type Model = Model_;
  export type ModelBiasJobDefinition = ModelBiasJobDefinition_;
  export type ModelCard = ModelCard_;
  export type ModelExplainabilityJobDefinition = ModelExplainabilityJobDefinition_;
  export type ModelPackage = ModelPackage_;
  export type ModelPackageGroup = ModelPackageGroup_;
  export type ModelQualityJobDefinition = ModelQualityJobDefinition_;
  export type MonitoringSchedule = MonitoringSchedule_;
  export type NotebookInstance = NotebookInstance_;
  export type NotebookInstanceLifecycleConfig = NotebookInstanceLifecycleConfig_;
  export type PartnerApp = PartnerApp_;
  export type Pipeline = Pipeline_;
  export type ProcessingJob = ProcessingJob_;
  export type Project = Project_;
  export type Space = Space_;
  export type StudioLifecycleConfig = StudioLifecycleConfig_;
  export type UserProfile = UserProfile_;
  export type Workteam = Workteam_;
}
