import Agent_ from './agent';
import LocationAzureBlob_ from './locationAzureBlob';
import LocationEFS_ from './locationEfs';
import LocationFSxLustre_ from './locationFSxLustre';
import LocationFSxONTAP_ from './locationFSxOntap';
import LocationFSxOpenZFS_ from './locationFSxOpenZfs';
import LocationFSxWindows_ from './locationFSxWindows';
import LocationHDFS_ from './locationHdfs';
import LocationNFS_ from './locationNfs';
import LocationObjectStorage_ from './locationObjectStorage';
import LocationS3_ from './locationS3';
import LocationSMB_ from './locationSmb';
import Task_ from './task';
export namespace DataSync {
  export const Agent = Agent_;
  export const LocationAzureBlob = LocationAzureBlob_;
  export const LocationEFS = LocationEFS_;
  export const LocationFSxLustre = LocationFSxLustre_;
  export const LocationFSxONTAP = LocationFSxONTAP_;
  export const LocationFSxOpenZFS = LocationFSxOpenZFS_;
  export const LocationFSxWindows = LocationFSxWindows_;
  export const LocationHDFS = LocationHDFS_;
  export const LocationNFS = LocationNFS_;
  export const LocationObjectStorage = LocationObjectStorage_;
  export const LocationS3 = LocationS3_;
  export const LocationSMB = LocationSMB_;
  export const Task = Task_;
  export type Agent = Agent_;
  export type LocationAzureBlob = LocationAzureBlob_;
  export type LocationEFS = LocationEFS_;
  export type LocationFSxLustre = LocationFSxLustre_;
  export type LocationFSxONTAP = LocationFSxONTAP_;
  export type LocationFSxOpenZFS = LocationFSxOpenZFS_;
  export type LocationFSxWindows = LocationFSxWindows_;
  export type LocationHDFS = LocationHDFS_;
  export type LocationNFS = LocationNFS_;
  export type LocationObjectStorage = LocationObjectStorage_;
  export type LocationS3 = LocationS3_;
  export type LocationSMB = LocationSMB_;
  export type Task = Task_;
}
