/**
 * #### Bastion Host
 *
 * ---
 *
 * A bastion host instance that helps you access resources in your stack that are protected within a private network.
 * It leverages keyless SSH connections and tunnels for maximum security.
 */
interface Bastion {
  type: 'bastion';
  properties?: BastionProps;
  overrides?: ResourceOverrides;
}

interface BastionProps {
  /**
   * #### The instance size for the bastion host.
   *
   * ---
   *
   * @default t3.micro
   */
  instanceSize?: string;
  /**
   * #### Commands to be run on the launch of the bastion instance.
   *
   * ---
   *
   * - Commands are run as the `root` user (do not use `sudo`).
   * - Modifying this list after the bastion host has been created will force a replacement of the instance, meaning any manually created data on the old instance will be lost.
   * - Use this to install dependencies and packages that may be required for your bastion scripts.
   */
  runCommandsAtLaunch?: string[];
  /**
   * #### Configures logging for the bastion host.
   *
   * ---
   *
   * Multiple log types are collected from the bastion host, and you can specify the logging behavior for each type.
   */
  logging?: BastionLoggingConfig;
}

interface BastionLoggingConfig {
  /**
   * #### Configures logging for `/var/log/messages`.
   *
   * ---
   *
   * This log group collects global system messages, including those logged during system startup.
   * By default, these logs are retained for 30 days.
   */
  messages?: BastionLogging;
  /**
   * #### Configures logging for `/var/log/secure`.
   *
   * ---
   *
   * This log group collects information related to authentication and authorization, such as SSH login attempts.
   * By default, these logs are retained for 180 days.
   */
  secure?: BastionLogging;
  /**
   * #### Configures logging for `/var/log/audit/audit.log`.
   *
   * ---
   *
   * This log group contains a detailed record of security-related events generated by the Linux audit system.
   * By default, these logs are retained for 365 days.
   */
  audit?: BastionLogging;
}

interface BastionLogging extends LogForwardingBase {
  /**
   * #### Disables the collection of logs to CloudWatch.
   *
   * ---
   *
   * @default false
   */
  disabled?: boolean;
  /**
   * #### The number of days to retain logs in the CloudWatch log group.
   */
  retentionDays?: 1 | 3 | 5 | 7 | 14 | 30 | 60 | 90 | 120 | 150 | 180 | 365 | 400 | 545 | 731 | 1827 | 3653;
}

type StpBastion = Bastion['properties'] & {
  name: string;
  type: Bastion['type'];
  configParentResourceType: Bastion['type'];
  nameChain: string[];
};
