// Generated by `apps/cli`'s `generate` task and committed there. Read as data — `apps/docs` never
// imports CLI implementation. `src/build/cli-generated-inputs.ts` lists every artifact this
// application consumes from the CLI.
import allStarterProjects from '../../../cli/starter-projects-metadata.json';

export type StarterProject = (typeof allStarterProjects)[number];

// These starters exist in the monorepo but do not have public GitHub repositories yet. Keep them out
// of the public catalogue so the docs never advertise broken GitHub and one-click deployment links.
// Remove an ID when its repository is published.
const unpublishedStarterProjectIds = new Set([
  'agentcore-customer-support-agent',
  'agentcore-data-analyst',
  'agentcore-research-assistant',
  's3files-dataset-reporting',
  's3files-model-inference-api'
]);

export const publicStarterProjects = allStarterProjects.filter(
  (project) => !unpublishedStarterProjectIds.has(project.starterProjectId)
);
