import { useEffect, useRef } from 'react';
import { useRouter } from 'next/router';

export function useHotReload() {
  const router = useRouter();
  const lastMaxTimestampRef = useRef<number | null>(null);
  const isFirstCheckRef = useRef(true);

  useEffect(() => {
    // Only run in development
    if (process.env.NODE_ENV !== 'development') return;

    let timeoutId: NodeJS.Timeout;
    let isMounted = true;

    const checkForChanges = async () => {
      if (!isMounted) return;

      try {
        // Fetch the static timestamps file (generated by watch-content.ts)
        const response = await fetch(`/_timestamps.json?t=${Date.now()}`);

        if (response.ok) {
          const data = await response.json();
          const currentMaxTimestamp = data.maxTimestamp;

          // On first check, just store the timestamp
          if (isFirstCheckRef.current) {
            lastMaxTimestampRef.current = currentMaxTimestamp;
            isFirstCheckRef.current = false;
          } else if (lastMaxTimestampRef.current !== null && currentMaxTimestamp > lastMaxTimestampRef.current) {
            // File changed, refresh the page
            console.log('📝 Content changed, refreshing page...');
            lastMaxTimestampRef.current = currentMaxTimestamp;
            router.replace(router.asPath);
            return; // Don't schedule next check, page will reload
          }
        }
      } catch {
        // Ignore errors (file might not exist yet)
      }

      // Schedule next check
      if (isMounted) {
        timeoutId = setTimeout(checkForChanges, 500);
      }
    };

    // Start checking after a short delay
    timeoutId = setTimeout(checkForChanges, 500);

    return () => {
      isMounted = false;
      if (timeoutId) {
        clearTimeout(timeoutId);
      }
    };
  }, [router]);
}
