type StacktapePrerequisite = 'docker' | 'node' | 'java' | 'ruby' | 'python' | 'go' | 'php' | 'dotnet';

type SupportedAutogeneratedConfigType =
  | 'web-service-apigw'
  | 'web-service-alb'
  | 'cron-job'
  | 'spa-website'
  | 'static-website'
  | 'nextjs-website';

type RawStarterProjectMetadata = {
  tags: string[];
  name: string;
  prerequisites: StacktapePrerequisite[];
  disableLintingOption?: boolean;
  hasOwnTsConfig?: boolean;
  priority?: number;
};

type UsedResourceData = {
  name: string;
  type: StpResourceType;
  containerNames: string[];
};

type StarterProjectMetadata = RawStarterProjectMetadata & {
  projectType: 'es' | 'python' | 'ruby' | 'java' | 'go' | 'php' | 'dotnet';
  usedResourceTypes: StpResourceType[];
  usedResources: UsedResourceData[];
  githubLink: string;
  isRestApi: boolean;
  hasReact: boolean;
  hasPrisma: boolean;
  monthlyAwsCosts: number;
  hasTypescript: boolean;
  hasCognito: boolean;
  hasNextJs: boolean;
  isWebsite: boolean;
  isSpaWebsite: boolean;
  isServerSideRenderedWebsite: boolean;
  isStaticWebsite: boolean;
  starterProjectId: string;
  description: string;
};
