import Channel_ from './channel';
import ChannelPlacementGroup_ from './channelPlacementGroup';
import CloudWatchAlarmTemplate_ from './cloudWatchAlarmTemplate';
import CloudWatchAlarmTemplateGroup_ from './cloudWatchAlarmTemplateGroup';
import Cluster_ from './cluster';
import EventBridgeRuleTemplate_ from './eventBridgeRuleTemplate';
import EventBridgeRuleTemplateGroup_ from './eventBridgeRuleTemplateGroup';
import Input_ from './input';
import InputSecurityGroup_ from './inputSecurityGroup';
import Multiplex_ from './multiplex';
import Multiplexprogram_ from './multiplexprogram';
import Network_ from './network';
import SdiSource_ from './sdiSource';
import SignalMap_ from './signalMap';
export namespace MediaLive {
  export const Channel = Channel_;
  export const ChannelPlacementGroup = ChannelPlacementGroup_;
  export const CloudWatchAlarmTemplate = CloudWatchAlarmTemplate_;
  export const CloudWatchAlarmTemplateGroup = CloudWatchAlarmTemplateGroup_;
  export const Cluster = Cluster_;
  export const EventBridgeRuleTemplate = EventBridgeRuleTemplate_;
  export const EventBridgeRuleTemplateGroup = EventBridgeRuleTemplateGroup_;
  export const Input = Input_;
  export const InputSecurityGroup = InputSecurityGroup_;
  export const Multiplex = Multiplex_;
  export const Multiplexprogram = Multiplexprogram_;
  export const Network = Network_;
  export const SdiSource = SdiSource_;
  export const SignalMap = SignalMap_;
  export type Channel = Channel_;
  export type ChannelPlacementGroup = ChannelPlacementGroup_;
  export type CloudWatchAlarmTemplate = CloudWatchAlarmTemplate_;
  export type CloudWatchAlarmTemplateGroup = CloudWatchAlarmTemplateGroup_;
  export type Cluster = Cluster_;
  export type EventBridgeRuleTemplate = EventBridgeRuleTemplate_;
  export type EventBridgeRuleTemplateGroup = EventBridgeRuleTemplateGroup_;
  export type Input = Input_;
  export type InputSecurityGroup = InputSecurityGroup_;
  export type Multiplex = Multiplex_;
  export type Multiplexprogram = Multiplexprogram_;
  export type Network = Network_;
  export type SdiSource = SdiSource_;
  export type SignalMap = SignalMap_;
}
