// This file is auto-generated. Do not edit manually.
// Source: aws-codepipeline-webhook.json

/** Resource Type definition for AWS::CodePipeline::Webhook */
export type AwsCodepipelineWebhook = {
  /** Properties that configure the authentication applied to incoming webhook trigger requests */
  AuthenticationConfiguration: {
    /**
     * The property used to configure acceptance of webhooks in an IP address range. For IP, only the
     * AllowedIPRange property must be set. This property must be set to a valid CIDR range.
     * @minLength 1
     * @maxLength 100
     */
    AllowedIPRange?: string;
    /**
     * The property used to configure GitHub authentication. For GITHUB_HMAC, only the SecretToken
     * property must be set.
     * @minLength 1
     * @maxLength 100
     */
    SecretToken?: string;
  };
  /**
   * A list of rules applied to the body/payload sent in the POST request to a webhook URL
   * @uniqueItems false
   */
  Filters: {
    /**
     * A JsonPath expression that is applied to the body/payload of the webhook. The value selected by the
     * JsonPath expression must match the value specified in the MatchEquals field. Otherwise, the request
     * is ignored.
     * @minLength 1
     * @maxLength 150
     */
    JsonPath: string;
    /**
     * The value selected by the JsonPath expression must match what is supplied in the MatchEquals field.
     * Otherwise, the request is ignored.
     * @minLength 1
     * @maxLength 150
     */
    MatchEquals?: string;
  }[];
  /**
   * Supported options are GITHUB_HMAC, IP, and UNAUTHENTICATED.
   * @enum ["GITHUB_HMAC","IP","UNAUTHENTICATED"]
   */
  Authentication: "GITHUB_HMAC" | "IP" | "UNAUTHENTICATED";
  /**
   * The name of the pipeline you want to connect to the webhook.
   * @minLength 1
   * @maxLength 100
   * @pattern [A-Za-z0-9.@\-_]+
   */
  TargetPipeline: string;
  /**
   * The name of the action in a pipeline you want to connect to the webhook.
   * @minLength 1
   * @maxLength 100
   * @pattern [A-Za-z0-9.@\-_]+
   */
  TargetAction: string;
  /** logical id of the webhook */
  Id?: string;
  /** The webhook URL generated by AWS CodePipeline */
  Url?: string;
  /**
   * The name of the webhook
   * @minLength 1
   * @maxLength 100
   * @pattern [A-Za-z0-9.@\-_]+
   */
  Name?: string;
  /** The version number of the pipeline to be connected to the trigger request. */
  TargetPipelineVersion?: number;
  /**
   * Configures a connection between the webhook that was created and the external tool with events to
   * be detected.
   */
  RegisterWithThirdParty?: boolean;
};
