// This file is auto-generated. Do not edit manually.
// Source: aws-ec2-vpcendpoint.json

/**
 * Specifies a VPC endpoint. A VPC endpoint provides a private connection between your VPC and an
 * endpoint service. You can use an endpoint service provided by AWS, an MKT Partner, or another AWS
 * accounts in your organization. For more information, see the [User
 * Guide](https://docs.aws.amazon.com/vpc/latest/privatelink/).
 * An endpoint of type ``Interface`` establishes connections between the subnets in your VPC and an
 * AWS-service, your own service, or a service hosted by another AWS-account. With an interface VPC
 * endpoint, you specify the subnets in which to create the endpoint and the security groups to
 * associate with the endpoint network interfaces.
 * An endpoint of type ``gateway`` serves as a target for a route in your route table for traffic
 * destined for S3 or DDB. You can specify an endpoint policy for the endpoint, which controls access
 * to the service from your VPC. You can also specify the VPC route tables that use the endpoint. For
 * more information about connectivity to S3, see [Why can't I connect to an S3 bucket using a gateway
 * VPC endpoint?](https://docs.aws.amazon.com/premiumsupport/knowledge-center/connect-s3-vpc-endpoint)
 * An endpoint of type ``GatewayLoadBalancer`` provides private connectivity between your VPC and
 * virtual appliances from a service provider.
 */
export type AwsEc2Vpcendpoint = {
  /**
   * Indicate whether to associate a private hosted zone with the specified VPC. The private hosted zone
   * contains a record set for the default public DNS name for the service for the Region (for example,
   * ``kinesis.us-east-1.amazonaws.com``), which resolves to the private IP addresses of the endpoint
   * network interfaces in the VPC. This enables you to make requests to the default public DNS name for
   * the service instead of the public DNS names that are automatically generated by the VPC endpoint
   * service.
   * To use a private hosted zone, you must set the following VPC attributes to ``true``:
   * ``enableDnsHostnames`` and ``enableDnsSupport``.
   * This property is supported only for interface endpoints.
   * Default: ``false``
   */
  PrivateDnsEnabled?: boolean;
  /**
   * The supported IP address types.
   * @enum ["ipv4","ipv6","dualstack","not-specified"]
   */
  IpAddressType?: "ipv4" | "ipv6" | "dualstack" | "not-specified";
  /** Describes a Region. */
  ServiceRegion?: string;
  CreationTimestamp?: string;
  /** Describes the DNS options for an endpoint. */
  DnsOptions?: {
    /**
     * Indicates whether to enable private DNS only for inbound endpoints. This option is available only
     * for services that support both gateway and interface endpoints. It routes traffic that originates
     * from the VPC to the gateway endpoint and traffic that originates from on-premises to the interface
     * endpoint.
     * @enum ["OnlyInboundResolver","AllResolvers","NotSpecified"]
     */
    PrivateDnsOnlyForInboundResolverEndpoint?: "OnlyInboundResolver" | "AllResolvers" | "NotSpecified";
    /**
     * @minItems 1
     * @maxItems 10
     */
    PrivateDnsSpecifiedDomains?: string[];
    /**
     * The DNS records created for the endpoint.
     * @enum ["ipv4","ipv6","dualstack","service-defined","not-specified"]
     */
    DnsRecordIpType?: "ipv4" | "ipv6" | "dualstack" | "service-defined" | "not-specified";
    /** @enum ["VERIFIED_DOMAINS_ONLY","ALL_DOMAINS","VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS","SPECIFIED_DOMAINS_ONLY"] */
    PrivateDnsPreference?: "VERIFIED_DOMAINS_ONLY" | "ALL_DOMAINS" | "VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS" | "SPECIFIED_DOMAINS_ONLY";
  };
  /** @uniqueItems false */
  NetworkInterfaceIds?: string[];
  /** @uniqueItems false */
  DnsEntries?: string[];
  /** The Amazon Resource Name (ARN) of the resource configuration. */
  ResourceConfigurationArn?: string;
  /**
   * The IDs of the security groups to associate with the endpoint network interfaces. If this parameter
   * is not specified, we use the default security group for the VPC. Security groups are supported only
   * for interface endpoints.
   * @uniqueItems true
   */
  SecurityGroupIds?: (unknown | unknown | unknown)[];
  /**
   * The IDs of the subnets in which to create endpoint network interfaces. You must specify this
   * property for an interface endpoint or a Gateway Load Balancer endpoint. You can't specify this
   * property for a gateway endpoint. For a Gateway Load Balancer endpoint, you can specify only one
   * subnet.
   * @uniqueItems true
   */
  SubnetIds?: string[];
  /** The Amazon Resource Name (ARN) of the service network. */
  ServiceNetworkArn?: string;
  /** The ID of the VPC. */
  VpcId: string;
  /**
   * The IDs of the route tables. Routing is supported only for gateway endpoints.
   * @uniqueItems true
   */
  RouteTableIds?: string[];
  /** The name of the endpoint service. */
  ServiceName?: string;
  /**
   * An endpoint policy, which controls access to the service from the VPC. The default endpoint policy
   * allows full access to the service. Endpoint policies are supported only for gateway and interface
   * endpoints.
   * For CloudFormation templates in YAML, you can provide the policy in JSON or YAML format. For
   * example, if you have a JSON policy, you can convert it to YAML before including it in the YAML
   * template, and CFNlong converts the policy to JSON format before calling the API actions for
   * privatelink. Alternatively, you can include the JSON directly in the YAML, as shown in the
   * following ``Properties`` section:
   * ``Properties: VpcEndpointType: 'Interface' ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
   * PolicyDocument: '{ "Version":"2012-10-17", "Statement": [{ "Effect":"Allow", "Principal":"*",
   * "Action":["logs:Describe*","logs:Get*","logs:List*","logs:FilterLogEvents"], "Resource":"*" }] }'``
   */
  PolicyDocument?: string | Record<string, unknown>;
  /**
   * The type of endpoint.
   * Default: Gateway
   * @enum ["Interface","Gateway","GatewayLoadBalancer","ServiceNetwork","Resource"]
   */
  VpcEndpointType?: "Interface" | "Gateway" | "GatewayLoadBalancer" | "ServiceNetwork" | "Resource";
  Id?: string;
  /**
   * The tags to associate with the endpoint.
   * @uniqueItems false
   */
  Tags?: {
    /**
     * The value of the tag.
     * Constraints: Tag values are case-sensitive and accept a maximum of 256 Unicode characters.
     */
    Value: string;
    /**
     * The key of the tag.
     * Constraints: Tag keys are case-sensitive and accept a maximum of 127 Unicode characters. May not
     * begin with ``aws:``.
     */
    Key: string;
  }[];
};
