// This file is auto-generated. Do not edit manually.
// Source: aws-elasticache-globalreplicationgroup.json

/**
 * The AWS::ElastiCache::GlobalReplicationGroup resource creates an Amazon ElastiCache Global
 * Replication Group.
 */
export type AwsElasticacheGlobalreplicationgroup = {
  /**
   * The suffix name of a Global Datastore. Amazon ElastiCache automatically applies a prefix to the
   * Global Datastore ID when it is created. Each AWS Region has its own prefix.
   */
  GlobalReplicationGroupIdSuffix?: string;
  /** AutomaticFailoverEnabled */
  AutomaticFailoverEnabled?: boolean;
  /** The cache node type of the Global Datastore */
  CacheNodeType?: string;
  /** The engine version of the Global Datastore. */
  EngineVersion?: string;
  /** The engine of the Global Datastore. */
  Engine?: string;
  /**
   * Cache parameter group name to use for the new engine version. This parameter cannot be modified
   * independently.
   */
  CacheParameterGroupName?: string;
  /** Indicates the number of node groups in the Global Datastore. */
  GlobalNodeGroupCount?: number;
  /** The optional description of the Global Datastore */
  GlobalReplicationGroupDescription?: string;
  /**
   * The name of the Global Datastore, it is generated by ElastiCache adding a prefix to
   * GlobalReplicationGroupIdSuffix.
   */
  GlobalReplicationGroupId?: string;
  /**
   * The replication groups that comprise the Global Datastore.
   * @minItems 1
   * @uniqueItems true
   */
  Members: ({
    /** Regionally unique identifier for the member i.e. ReplicationGroupId. */
    ReplicationGroupId?: string;
    /** The AWS region of the Global Datastore member. */
    ReplicationGroupRegion?: string;
    /**
     * Indicates the role of the member, primary or secondary.
     * @enum ["PRIMARY","SECONDARY"]
     */
    Role?: "PRIMARY" | "SECONDARY";
  })[];
  /** The status of the Global Datastore */
  Status?: string;
  /**
   * Describes the replication group IDs, the AWS regions where they are stored and the shard
   * configuration for each that comprise the Global Datastore
   * @uniqueItems true
   */
  RegionalConfigurations?: {
    /** The replication group id of the Global Datastore member. */
    ReplicationGroupId?: string;
    /** The AWS region of the Global Datastore member. */
    ReplicationGroupRegion?: string;
    /**
     * A list of PreferredAvailabilityZones objects that specifies the configuration of a node group in
     * the resharded cluster.
     * @uniqueItems true
     */
    ReshardingConfigurations?: {
      /**
       * Unique identifier for the Node Group. This is either auto-generated by ElastiCache (4-digit id) or
       * a user supplied id.
       */
      NodeGroupId?: string;
      /**
       * A list of preferred availability zones for the nodes of new node groups.
       * @uniqueItems false
       */
      PreferredAvailabilityZones?: string[];
    }[];
  }[];
};
