// This file is auto-generated. Do not edit manually.
// Source: aws-neptune-eventsubscription.json

/** Resource Type definition for AWS::Neptune::EventSubscription */
export type AwsNeptuneEventsubscription = {
  /**
   * An array of key-value pairs to apply to this resource.
   * @uniqueItems false
   */
  Tags?: {
    Key: string;
    Value: string;
  }[];
  /**
   * A Boolean value; set to true to activate the subscription, set to false to create the subscription
   * but not active it.
   * @default true
   */
  Enabled?: boolean;
  /**
   * A list of event categories for a SourceType that you want to subscribe to. You can see a list of
   * the categories for a given SourceType in the Events topic in the Amazon Neptune User Guide or by
   * using the DescribeEventCategories action.
   * @uniqueItems true
   */
  EventCategories?: string[];
  /**
   * The Amazon Resource Name (ARN) of the SNS topic created for event notification. The ARN is created
   * by Amazon SNS when you create a topic and subscribe to it.
   */
  SnsTopicArn: string;
  /**
   * The name of the subscription.
   * @maxLength 255
   */
  SubscriptionName?: string;
  /**
   * The list of identifiers of the event sources for which events will be returned. If not specified,
   * then all sources are included in the response. An identifier must begin with a letter and must
   * contain only ASCII letters, digits, and hyphens; it cannot end with a hyphen or contain two
   * consecutive hyphens.
   * @uniqueItems true
   */
  SourceIds?: string[];
  /**
   * The type of source that will be generating the events. For example, if you want to be notified of
   * events generated by a DB instance, you would set this parameter to db-instance. if this value is
   * not specified, all events are returned.
   */
  SourceType?: string;
};
