// This file is auto-generated. Do not edit manually.
// Source: aws-securityhub-insight.json

/**
 * The AWS::SecurityHub::Insight resource represents the AWS Security Hub Insight in your account. An
 * AWS Security Hub insight is a collection of related findings.
 */
export type AwsSecurityhubInsight = {
  /**
   * The ARN of a Security Hub insight
   * @pattern arn:aws\S*:securityhub:\S*
   */
  InsightArn?: string;
  /**
   * The name of a Security Hub insight
   * @minLength 1
   * @maxLength 128
   */
  Name: string;
  /** One or more attributes used to filter the findings included in the insight */
  Filters: {
    /**
     * The ARN generated by Security Hub that uniquely identifies a third-party company (security findings
     * provider) after this provider's product (solution that generates findings) is registered with
     * Security Hub.
     * @maxItems 20
     * @uniqueItems true
     */
    ProductArn?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The AWS account ID in which a finding is generated.
     * @maxItems 20
     * @uniqueItems true
     */
    AwsAccountId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of the AWS account in which a finding is generated.
     * @maxItems 20
     * @uniqueItems true
     */
    AwsAccountName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The security findings provider-specific identifier for a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    Id?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The identifier for the solution-specific component (a discrete unit of logic) that generated a
     * finding.
     * @maxItems 20
     * @uniqueItems true
     */
    GeneratorId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A finding type in the format of namespace/category/classifier that classifies a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    Type?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The Region from which the finding was generated.
     * @maxItems 20
     * @uniqueItems true
     */
    Region?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * An ISO8601-formatted timestamp that indicates when the security findings provider first observed
     * the potential security issue that a finding captured.
     * @maxItems 20
     * @uniqueItems true
     */
    FirstObservedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * An ISO8601-formatted timestamp that indicates when the security findings provider most recently
     * observed the potential security issue that a finding captured.
     * @maxItems 20
     * @uniqueItems true
     */
    LastObservedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * An ISO8601-formatted timestamp that indicates when the security findings provider captured the
     * potential security issue that a finding captured.
     * @maxItems 20
     * @uniqueItems true
     */
    CreatedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * An ISO8601-formatted timestamp that indicates when the security findings provider last updated the
     * finding record.
     * @maxItems 20
     * @uniqueItems true
     */
    UpdatedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * The label of a finding's severity.
     * @maxItems 20
     * @uniqueItems true
     */
    SeverityLabel?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A finding's confidence.
     * @maxItems 20
     * @uniqueItems true
     */
    Confidence?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * The level of importance assigned to the resources associated with the finding.
     * @maxItems 20
     * @uniqueItems true
     */
    Criticality?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * A finding's title.
     * @maxItems 20
     * @uniqueItems true
     */
    Title?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A finding's description.
     * @maxItems 20
     * @uniqueItems true
     */
    Description?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The recommendation of what to do about the issue described in a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    RecommendationText?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A URL that links to a page about the current finding in the security findings provider's solution.
     * @maxItems 20
     * @uniqueItems true
     */
    SourceUrl?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A data type where security findings providers can include additional solution-specific details that
     * aren't part of the defined AwsSecurityFinding format.
     * @maxItems 20
     * @uniqueItems true
     */
    ProductFields?: ({
      /**
       * The condition to apply to the key value when filtering Security Hub findings with a map filter.
       * @enum ["EQUALS","NOT_EQUALS"]
       */
      Comparison: "EQUALS" | "NOT_EQUALS";
      Key: string;
      Value: string;
    })[];
    /**
     * The name of the solution (product) that generates findings.
     * @maxItems 20
     * @uniqueItems true
     */
    ProductName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of the findings provider (company) that owns the solution (product) that generates
     * findings.
     * @maxItems 20
     * @uniqueItems true
     */
    CompanyName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A list of name/value string pairs associated with the finding.
     * @maxItems 20
     * @uniqueItems true
     */
    UserDefinedFields?: ({
      /**
       * The condition to apply to the key value when filtering Security Hub findings with a map filter.
       * @enum ["EQUALS","NOT_EQUALS"]
       */
      Comparison: "EQUALS" | "NOT_EQUALS";
      Key: string;
      Value: string;
    })[];
    /**
     * The name of the malware that was observed.
     * @maxItems 20
     * @uniqueItems true
     */
    MalwareName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The type of the malware that was observed.
     * @maxItems 20
     * @uniqueItems true
     */
    MalwareType?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The filesystem path of the malware that was observed.
     * @maxItems 20
     * @uniqueItems true
     */
    MalwarePath?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The state of the malware that was observed.
     * @maxItems 20
     * @uniqueItems true
     */
    MalwareState?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * Indicates the direction of network traffic associated with a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkDirection?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The protocol of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkProtocol?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The source IPv4 address of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkSourceIpV4?: {
      /** A finding's CIDR value. */
      Cidr: string;
    }[];
    /**
     * The source IPv6 address of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkSourceIpV6?: {
      /** A finding's CIDR value. */
      Cidr: string;
    }[];
    /**
     * The source port of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkSourcePort?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * The source domain of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkSourceDomain?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The source media access control (MAC) address of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkSourceMac?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The destination IPv4 address of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkDestinationIpV4?: {
      /** A finding's CIDR value. */
      Cidr: string;
    }[];
    /**
     * The destination IPv6 address of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkDestinationIpV6?: {
      /** A finding's CIDR value. */
      Cidr: string;
    }[];
    /**
     * The destination port of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkDestinationPort?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * The destination domain of network-related information about a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    NetworkDestinationDomain?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of the process.
     * @maxItems 20
     * @uniqueItems true
     */
    ProcessName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The path to the process executable.
     * @maxItems 20
     * @uniqueItems true
     */
    ProcessPath?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The process ID.
     * @maxItems 20
     * @uniqueItems true
     */
    ProcessPid?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * The parent process ID.
     * @maxItems 20
     * @uniqueItems true
     */
    ProcessParentPid?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * A timestamp that identifies when the process was launched.
     * @maxItems 20
     * @uniqueItems true
     */
    ProcessLaunchedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * A timestamp that identifies when the process was terminated.
     * @maxItems 20
     * @uniqueItems true
     */
    ProcessTerminatedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * The type of a threat intelligence indicator.
     * @maxItems 20
     * @uniqueItems true
     */
    ThreatIntelIndicatorType?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The value of a threat intelligence indicator.
     * @maxItems 20
     * @uniqueItems true
     */
    ThreatIntelIndicatorValue?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The category of a threat intelligence indicator.
     * @maxItems 20
     * @uniqueItems true
     */
    ThreatIntelIndicatorCategory?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A timestamp that identifies the last observation of a threat intelligence indicator.
     * @maxItems 20
     * @uniqueItems true
     */
    ThreatIntelIndicatorLastObservedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * The source of the threat intelligence.
     * @maxItems 20
     * @uniqueItems true
     */
    ThreatIntelIndicatorSource?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The URL for more details from the source of the threat intelligence.
     * @maxItems 20
     * @uniqueItems true
     */
    ThreatIntelIndicatorSourceUrl?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * Specifies the type of the resource that details are provided for.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceType?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The canonical identifier for the given resource type.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The canonical AWS partition name that the Region is assigned to.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourcePartition?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The canonical AWS external Region name where this resource is located.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceRegion?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A list of AWS tags associated with a resource at the time the finding was processed.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceTags?: ({
      /**
       * The condition to apply to the key value when filtering Security Hub findings with a map filter.
       * @enum ["EQUALS","NOT_EQUALS"]
       */
      Comparison: "EQUALS" | "NOT_EQUALS";
      Key: string;
      Value: string;
    })[];
    /**
     * The instance type of the instance.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceType?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The Amazon Machine Image (AMI) ID of the instance.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceImageId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The IPv4 addresses associated with the instance.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceIpV4Addresses?: {
      /** A finding's CIDR value. */
      Cidr: string;
    }[];
    /**
     * The IPv6 addresses associated with the instance.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceIpV6Addresses?: {
      /** A finding's CIDR value. */
      Cidr: string;
    }[];
    /**
     * The key name associated with the instance.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceKeyName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The IAM profile ARN of the instance.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceIamInstanceProfileArn?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The identifier of the VPC that the instance was launched in.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceVpcId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The identifier of the subnet that the instance was launched in.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceSubnetId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The date and time the instance was launched.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsEc2InstanceLaunchedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * The canonical user ID of the owner of the S3 bucket.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsS3BucketOwnerId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The display name of the owner of the S3 bucket.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsS3BucketOwnerName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The status of the IAM access key related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsIamAccessKeyStatus?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The creation date/time of the IAM access key related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsIamAccessKeyCreatedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * The name of the container related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceContainerName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The identifier of the image related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceContainerImageId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of the image related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceContainerImageName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A timestamp that identifies when the container was started.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceContainerLaunchedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * The details of a resource that doesn't have a specific subfield for the resource type defined.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceDetailsOther?: ({
      /**
       * The condition to apply to the key value when filtering Security Hub findings with a map filter.
       * @enum ["EQUALS","NOT_EQUALS"]
       */
      Comparison: "EQUALS" | "NOT_EQUALS";
      Key: string;
      Value: string;
    })[];
    /**
     * Exclusive to findings that are generated as the result of a check run against a specific rule in a
     * supported standard.
     * @maxItems 20
     * @uniqueItems true
     */
    ComplianceStatus?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The veracity of a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    VerificationState?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The workflow state of a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    WorkflowState?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The status of the investigation into a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    WorkflowStatus?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The updated record state for the finding.
     * @maxItems 20
     * @uniqueItems true
     */
    RecordState?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The ARN of the solution that generated a related finding.
     * @maxItems 20
     * @uniqueItems true
     */
    RelatedFindingsProductArn?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The solution-generated identifier for a related finding.
     * @maxItems 20
     * @uniqueItems true
     */
    RelatedFindingsId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The ARN of the application that is related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceApplicationArn?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of the application that is related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceApplicationName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The text of a note.
     * @maxItems 20
     * @uniqueItems true
     */
    NoteText?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The timestamp of when the note was updated.
     * @maxItems 20
     * @uniqueItems true
     */
    NoteUpdatedAt?: {
      DateRange?: {
        /**
         * A date range unit for the date filter.
         * @enum ["DAYS"]
         */
        Unit: "DAYS";
        /** A date range value for the date filter. */
        Value: number;
      };
      End?: string;
      Start?: string;
    }[];
    /**
     * The principal that created a note.
     * @maxItems 20
     * @uniqueItems true
     */
    NoteUpdatedBy?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * Indicates whether or not sample findings are included in the filter results.
     * @maxItems 20
     * @uniqueItems true
     */
    Sample?: {
      /** The value of the boolean. */
      Value: boolean;
    }[];
    /**
     * The unique identifier of a standard in which a control is enabled.
     * @maxItems 20
     * @uniqueItems true
     */
    ComplianceAssociatedStandardsId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The unique identifier of a control across standards.
     * @maxItems 20
     * @uniqueItems true
     */
    ComplianceSecurityControlId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of a security control parameter.
     * @maxItems 20
     * @uniqueItems true
     */
    ComplianceSecurityControlParametersName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The current value of a security control parameter.
     * @maxItems 20
     * @uniqueItems true
     */
    ComplianceSecurityControlParametersValue?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The finding provider value for the finding confidence.
     * @maxItems 20
     * @uniqueItems true
     */
    FindingProviderFieldsConfidence?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * The finding provider value for the level of importance assigned to the resources associated with
     * the findings.
     * @maxItems 20
     * @uniqueItems true
     */
    FindingProviderFieldsCriticality?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * The finding identifier of a related finding that is identified by the finding provider.
     * @maxItems 20
     * @uniqueItems true
     */
    FindingProviderFieldsRelatedFindingsId?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The ARN of the solution that generated a related finding that is identified by the finding
     * provider.
     * @maxItems 20
     * @uniqueItems true
     */
    FindingProviderFieldsRelatedFindingsProductArn?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The finding provider value for the severity label.
     * @maxItems 20
     * @uniqueItems true
     */
    FindingProviderFieldsSeverityLabel?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The finding provider's original value for the severity.
     * @maxItems 20
     * @uniqueItems true
     */
    FindingProviderFieldsSeverityOriginal?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * One or more finding types that the finding provider assigned to the finding.
     * @maxItems 20
     * @uniqueItems true
     */
    FindingProviderFieldsTypes?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of the principal that is associated with an IAM access key.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsIamAccessKeyPrincipalName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The name of an IAM user.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsIamUserUserName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * Indicates whether a software vulnerability in your environment has a known exploit.
     * @maxItems 20
     * @uniqueItems true
     */
    VulnerabilitiesExploitAvailable?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * Indicates whether a vulnerability is fixed in a newer version of the affected software packages.
     * @maxItems 20
     * @uniqueItems true
     */
    VulnerabilitiesFixAvailable?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * A keyword for a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    Keyword?: {
      /** A value for the keyword. */
      Value: string;
    }[];
    /**
     * The user associated with the IAM access key related to a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    ResourceAwsIamAccessKeyUserName?: ({
      Comparison: "EQUALS" | "PREFIX" | "NOT_EQUALS" | "PREFIX_NOT_EQUALS";
      Value: string;
    })[];
    /**
     * The normalized severity of a finding.
     * @maxItems 20
     * @uniqueItems true
     */
    SeverityNormalized?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
    /**
     * The native severity as defined by the security findings provider's solution that generated the
     * finding.
     * @maxItems 20
     * @uniqueItems true
     */
    SeverityProduct?: {
      /** The equal-to condition to be applied to a single field when querying for findings. */
      Eq?: number;
      /** The greater-than-equal condition to be applied to a single field when querying for findings. */
      Gte?: number;
      /** The less-than-equal condition to be applied to a single field when querying for findings. */
      Lte?: number;
    }[];
  };
  /** The grouping attribute for the insight's findings */
  GroupByAttribute: string;
};
