// This file is auto-generated. Do not edit manually.
// Source: aws-securitylake-datalake.json

/** Resource Type definition for AWS::SecurityLake::DataLake */
export type AwsSecuritylakeDatalake = {
  EncryptionConfiguration?: {
    /** The id of KMS encryption key used by Amazon Security Lake to encrypt the Security Lake object. */
    KmsKeyId?: string;
  };
  LifecycleConfiguration?: {
    Expiration?: {
      Days?: number;
    };
    /**
     * Provides data storage transition details of Amazon Security Lake object.
     * @uniqueItems false
     */
    Transitions?: {
      /**
       * Number of days before data transitions to a different S3 Storage Class in the Amazon Security Lake
       * object.
       * @minimum 1
       */
      Days?: number;
      /**
       * The range of storage classes that you can choose from based on the data access, resiliency, and
       * cost requirements of your workloads.
       */
      StorageClass?: string;
    }[];
  };
  ReplicationConfiguration?: {
    Regions?: string[];
    /**
     * Replication settings for the Amazon S3 buckets. This parameter uses the AWS Identity and Access
     * Management (IAM) role you created that is managed by Security Lake, to ensure the replication
     * setting is correct.
     * @pattern ^arn:.*$
     */
    RoleArn?: string;
  };
  /**
   * The Amazon Resource Name (ARN) used to index AWS Glue table partitions that are generated by the
   * ingestion and normalization of AWS log sources and custom sources.
   * @pattern ^arn:.*$
   */
  MetaStoreManagerRoleArn?: string;
  /** @uniqueItems false */
  Tags?: {
    /**
     * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and
     * cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode
     * letters, digits, whitespace, `_`, `.`, `/`, `=`, `+`, and `-`.
     */
    Key: string;
    /** The value for the tag. You can specify a value that is 0 to 256 characters in length. */
    Value: string;
  }[];
  /**
   * The Amazon Resource Name (ARN) created by you to provide to the subscriber.
   * @minLength 1
   * @maxLength 1011
   */
  Arn?: string;
  /** The ARN for the Amazon Security Lake Amazon S3 bucket. */
  S3BucketArn?: string;
};
