import Connection_ from './connection';
import DataSource_ from './dataSource';
import Domain_ from './domain';
import DomainUnit_ from './domainUnit';
import Environment_ from './environment';
import EnvironmentActions_ from './environmentActions';
import EnvironmentBlueprintConfiguration_ from './environmentBlueprintConfiguration';
import EnvironmentProfile_ from './environmentProfile';
import FormType_ from './formType';
import GroupProfile_ from './groupProfile';
import Owner_ from './owner';
import PolicyGrant_ from './policyGrant';
import Project_ from './project';
import ProjectMembership_ from './projectMembership';
import ProjectProfile_ from './projectProfile';
import SubscriptionTarget_ from './subscriptionTarget';
import UserProfile_ from './userProfile';
export namespace DataZone {
  export const Connection = Connection_;
  export const DataSource = DataSource_;
  export const Domain = Domain_;
  export const DomainUnit = DomainUnit_;
  export const Environment = Environment_;
  export const EnvironmentActions = EnvironmentActions_;
  export const EnvironmentBlueprintConfiguration = EnvironmentBlueprintConfiguration_;
  export const EnvironmentProfile = EnvironmentProfile_;
  export const FormType = FormType_;
  export const GroupProfile = GroupProfile_;
  export const Owner = Owner_;
  export const PolicyGrant = PolicyGrant_;
  export const Project = Project_;
  export const ProjectMembership = ProjectMembership_;
  export const ProjectProfile = ProjectProfile_;
  export const SubscriptionTarget = SubscriptionTarget_;
  export const UserProfile = UserProfile_;
  export type Connection = Connection_;
  export type DataSource = DataSource_;
  export type Domain = Domain_;
  export type DomainUnit = DomainUnit_;
  export type Environment = Environment_;
  export type EnvironmentActions = EnvironmentActions_;
  export type EnvironmentBlueprintConfiguration = EnvironmentBlueprintConfiguration_;
  export type EnvironmentProfile = EnvironmentProfile_;
  export type FormType = FormType_;
  export type GroupProfile = GroupProfile_;
  export type Owner = Owner_;
  export type PolicyGrant = PolicyGrant_;
  export type Project = Project_;
  export type ProjectMembership = ProjectMembership_;
  export type ProjectProfile = ProjectProfile_;
  export type SubscriptionTarget = SubscriptionTarget_;
  export type UserProfile = UserProfile_;
}
