import AnycastIpList_ from './anycastIpList';
import CachePolicy_ from './cachePolicy';
import CloudFrontOriginAccessIdentity_ from './cloudFrontOriginAccessIdentity';
import ConnectionGroup_ from './connectionGroup';
import ContinuousDeploymentPolicy_ from './continuousDeploymentPolicy';
import Distribution_ from './distribution';
import DistributionTenant_ from './distributionTenant';
import Function_ from './function';
import KeyGroup_ from './keyGroup';
import KeyValueStore_ from './keyValueStore';
import MonitoringSubscription_ from './monitoringSubscription';
import OriginAccessControl_ from './originAccessControl';
import OriginRequestPolicy_ from './originRequestPolicy';
import PublicKey_ from './publicKey';
import RealtimeLogConfig_ from './realtimeLogConfig';
import ResponseHeadersPolicy_ from './responseHeadersPolicy';
import StreamingDistribution_ from './streamingDistribution';
import VpcOrigin_ from './vpcOrigin';
export namespace CloudFront {
  export const AnycastIpList = AnycastIpList_;
  export const CachePolicy = CachePolicy_;
  export const CloudFrontOriginAccessIdentity = CloudFrontOriginAccessIdentity_;
  export const ConnectionGroup = ConnectionGroup_;
  export const ContinuousDeploymentPolicy = ContinuousDeploymentPolicy_;
  export const Distribution = Distribution_;
  export const DistributionTenant = DistributionTenant_;
  export const Function = Function_;
  export const KeyGroup = KeyGroup_;
  export const KeyValueStore = KeyValueStore_;
  export const MonitoringSubscription = MonitoringSubscription_;
  export const OriginAccessControl = OriginAccessControl_;
  export const OriginRequestPolicy = OriginRequestPolicy_;
  export const PublicKey = PublicKey_;
  export const RealtimeLogConfig = RealtimeLogConfig_;
  export const ResponseHeadersPolicy = ResponseHeadersPolicy_;
  export const StreamingDistribution = StreamingDistribution_;
  export const VpcOrigin = VpcOrigin_;
  export type AnycastIpList = AnycastIpList_;
  export type CachePolicy = CachePolicy_;
  export type CloudFrontOriginAccessIdentity = CloudFrontOriginAccessIdentity_;
  export type ConnectionGroup = ConnectionGroup_;
  export type ContinuousDeploymentPolicy = ContinuousDeploymentPolicy_;
  export type Distribution = Distribution_;
  export type DistributionTenant = DistributionTenant_;
  export type Function = Function_;
  export type KeyGroup = KeyGroup_;
  export type KeyValueStore = KeyValueStore_;
  export type MonitoringSubscription = MonitoringSubscription_;
  export type OriginAccessControl = OriginAccessControl_;
  export type OriginRequestPolicy = OriginRequestPolicy_;
  export type PublicKey = PublicKey_;
  export type RealtimeLogConfig = RealtimeLogConfig_;
  export type ResponseHeadersPolicy = ResponseHeadersPolicy_;
  export type StreamingDistribution = StreamingDistribution_;
  export type VpcOrigin = VpcOrigin_;
}
