import CustomResource_ from './customResource';
import GuardHook_ from './guardHook';
import HookDefaultVersion_ from './hookDefaultVersion';
import HookTypeConfig_ from './hookTypeConfig';
import HookVersion_ from './hookVersion';
import LambdaHook_ from './lambdaHook';
import Macro_ from './macro';
import ModuleDefaultVersion_ from './moduleDefaultVersion';
import ModuleVersion_ from './moduleVersion';
import PublicTypeVersion_ from './publicTypeVersion';
import Publisher_ from './publisher';
import ResourceDefaultVersion_ from './resourceDefaultVersion';
import ResourceVersion_ from './resourceVersion';
import Stack_ from './stack';
import StackSet_ from './stackSet';
import TypeActivation_ from './typeActivation';
import WaitCondition_ from './waitCondition';
import WaitConditionHandle_ from './waitConditionHandle';
export namespace CloudFormation {
  export const CustomResource = CustomResource_;
  export const GuardHook = GuardHook_;
  export const HookDefaultVersion = HookDefaultVersion_;
  export const HookTypeConfig = HookTypeConfig_;
  export const HookVersion = HookVersion_;
  export const LambdaHook = LambdaHook_;
  export const Macro = Macro_;
  export const ModuleDefaultVersion = ModuleDefaultVersion_;
  export const ModuleVersion = ModuleVersion_;
  export const PublicTypeVersion = PublicTypeVersion_;
  export const Publisher = Publisher_;
  export const ResourceDefaultVersion = ResourceDefaultVersion_;
  export const ResourceVersion = ResourceVersion_;
  export const Stack = Stack_;
  export const StackSet = StackSet_;
  export const TypeActivation = TypeActivation_;
  export const WaitCondition = WaitCondition_;
  export const WaitConditionHandle = WaitConditionHandle_;
  export type CustomResource = CustomResource_;
  export type GuardHook = GuardHook_;
  export type HookDefaultVersion = HookDefaultVersion_;
  export type HookTypeConfig = HookTypeConfig_;
  export type HookVersion = HookVersion_;
  export type LambdaHook = LambdaHook_;
  export type Macro = Macro_;
  export type ModuleDefaultVersion = ModuleDefaultVersion_;
  export type ModuleVersion = ModuleVersion_;
  export type PublicTypeVersion = PublicTypeVersion_;
  export type Publisher = Publisher_;
  export type ResourceDefaultVersion = ResourceDefaultVersion_;
  export type ResourceVersion = ResourceVersion_;
  export type Stack = Stack_;
  export type StackSet = StackSet_;
  export type TypeActivation = TypeActivation_;
  export type WaitCondition = WaitCondition_;
  export type WaitConditionHandle = WaitConditionHandle_;
}
