import AgentStatus_ from './agentStatus';
import ApprovedOrigin_ from './approvedOrigin';
import ContactFlow_ from './contactFlow';
import ContactFlowModule_ from './contactFlowModule';
import EmailAddress_ from './emailAddress';
import EvaluationForm_ from './evaluationForm';
import HoursOfOperation_ from './hoursOfOperation';
import Instance_ from './instance';
import InstanceStorageConfig_ from './instanceStorageConfig';
import IntegrationAssociation_ from './integrationAssociation';
import PhoneNumber_ from './phoneNumber';
import PredefinedAttribute_ from './predefinedAttribute';
import Prompt_ from './prompt';
import Queue_ from './queue';
import QuickConnect_ from './quickConnect';
import RoutingProfile_ from './routingProfile';
import Rule_ from './rule';
import SecurityKey_ from './securityKey';
import SecurityProfile_ from './securityProfile';
import TaskTemplate_ from './taskTemplate';
import TrafficDistributionGroup_ from './trafficDistributionGroup';
import User_ from './user';
import UserHierarchyGroup_ from './userHierarchyGroup';
import UserHierarchyStructure_ from './userHierarchyStructure';
import View_ from './view';
import ViewVersion_ from './viewVersion';
import ContactFlowVersion_ from './contactFlowVersion';
export namespace Connect {
  export const AgentStatus = AgentStatus_;
  export const ApprovedOrigin = ApprovedOrigin_;
  export const ContactFlow = ContactFlow_;
  export const ContactFlowModule = ContactFlowModule_;
  export const EmailAddress = EmailAddress_;
  export const EvaluationForm = EvaluationForm_;
  export const HoursOfOperation = HoursOfOperation_;
  export const Instance = Instance_;
  export const InstanceStorageConfig = InstanceStorageConfig_;
  export const IntegrationAssociation = IntegrationAssociation_;
  export const PhoneNumber = PhoneNumber_;
  export const PredefinedAttribute = PredefinedAttribute_;
  export const Prompt = Prompt_;
  export const Queue = Queue_;
  export const QuickConnect = QuickConnect_;
  export const RoutingProfile = RoutingProfile_;
  export const Rule = Rule_;
  export const SecurityKey = SecurityKey_;
  export const SecurityProfile = SecurityProfile_;
  export const TaskTemplate = TaskTemplate_;
  export const TrafficDistributionGroup = TrafficDistributionGroup_;
  export const User = User_;
  export const UserHierarchyGroup = UserHierarchyGroup_;
  export const UserHierarchyStructure = UserHierarchyStructure_;
  export const View = View_;
  export const ViewVersion = ViewVersion_;
  export const ContactFlowVersion = ContactFlowVersion_;
  export type AgentStatus = AgentStatus_;
  export type ApprovedOrigin = ApprovedOrigin_;
  export type ContactFlow = ContactFlow_;
  export type ContactFlowModule = ContactFlowModule_;
  export type EmailAddress = EmailAddress_;
  export type EvaluationForm = EvaluationForm_;
  export type HoursOfOperation = HoursOfOperation_;
  export type Instance = Instance_;
  export type InstanceStorageConfig = InstanceStorageConfig_;
  export type IntegrationAssociation = IntegrationAssociation_;
  export type PhoneNumber = PhoneNumber_;
  export type PredefinedAttribute = PredefinedAttribute_;
  export type Prompt = Prompt_;
  export type Queue = Queue_;
  export type QuickConnect = QuickConnect_;
  export type RoutingProfile = RoutingProfile_;
  export type Rule = Rule_;
  export type SecurityKey = SecurityKey_;
  export type SecurityProfile = SecurityProfile_;
  export type TaskTemplate = TaskTemplate_;
  export type TrafficDistributionGroup = TrafficDistributionGroup_;
  export type User = User_;
  export type UserHierarchyGroup = UserHierarchyGroup_;
  export type UserHierarchyStructure = UserHierarchyStructure_;
  export type View = View_;
  export type ViewVersion = ViewVersion_;
  export type ContactFlowVersion = ContactFlowVersion_;
}
