import AccessLogSubscription_ from './accessLogSubscription';
import AuthPolicy_ from './authPolicy';
import Listener_ from './listener';
import ResourceConfiguration_ from './resourceConfiguration';
import ResourceGateway_ from './resourceGateway';
import ResourcePolicy_ from './resourcePolicy';
import Rule_ from './rule';
import Service_ from './service';
import ServiceNetwork_ from './serviceNetwork';
import ServiceNetworkResourceAssociation_ from './serviceNetworkResourceAssociation';
import ServiceNetworkServiceAssociation_ from './serviceNetworkServiceAssociation';
import ServiceNetworkVpcAssociation_ from './serviceNetworkVpcAssociation';
import TargetGroup_ from './targetGroup';
export namespace VpcLattice {
  export const AccessLogSubscription = AccessLogSubscription_;
  export const AuthPolicy = AuthPolicy_;
  export const Listener = Listener_;
  export const ResourceConfiguration = ResourceConfiguration_;
  export const ResourceGateway = ResourceGateway_;
  export const ResourcePolicy = ResourcePolicy_;
  export const Rule = Rule_;
  export const Service = Service_;
  export const ServiceNetwork = ServiceNetwork_;
  export const ServiceNetworkResourceAssociation = ServiceNetworkResourceAssociation_;
  export const ServiceNetworkServiceAssociation = ServiceNetworkServiceAssociation_;
  export const ServiceNetworkVpcAssociation = ServiceNetworkVpcAssociation_;
  export const TargetGroup = TargetGroup_;
  export type AccessLogSubscription = AccessLogSubscription_;
  export type AuthPolicy = AuthPolicy_;
  export type Listener = Listener_;
  export type ResourceConfiguration = ResourceConfiguration_;
  export type ResourceGateway = ResourceGateway_;
  export type ResourcePolicy = ResourcePolicy_;
  export type Rule = Rule_;
  export type Service = Service_;
  export type ServiceNetwork = ServiceNetwork_;
  export type ServiceNetworkResourceAssociation = ServiceNetworkResourceAssociation_;
  export type ServiceNetworkServiceAssociation = ServiceNetworkServiceAssociation_;
  export type ServiceNetworkVpcAssociation = ServiceNetworkVpcAssociation_;
  export type TargetGroup = TargetGroup_;
}
