import { readFileSync, readdirSync } from 'node:fs';
import { basename, join } from 'node:path';
import { CONFIG_BRIDGE_PATH, CONFIG_PACKAGE_SRC_PATH } from '@shared/naming/project-fs-paths';
import { logInfo, logSuccess } from '@shared/utils/logging';
import { outputFile } from 'fs-extra';
import * as ts from 'typescript';

/**
 * `@stacktape/config` owns the authored configuration model, but most CLI files still reference those types as
 * ambient globals. This bridge re-declares the package's whole exported type surface as global aliases so those
 * files keep compiling while their imports are migrated cluster by cluster.
 *
 * The bridge is regenerated wholesale, so an individual alias does not disappear when its last consumer
 * migrates. Progress is measured by `check-config-bridge.ts`, which resolves real symbols and reports how many
 * files and names still come from here. The bridge is deleted in one step when that reaches zero.
 */
const BRIDGE_HEADER = `// Generated by scripts/generate-config-bridge.ts. Do not edit.
//
// Temporary ambient bridge. It aliases the complete @stacktape/config type surface into the global scope so
// that CLI files which have not yet been migrated keep compiling. Aliases are regenerated as a set: one does
// not disappear when its last consumer migrates.
//
// Migrate a consumer with an explicit \`import type { X } from '@stacktape/config/<module>'\`.
// Remaining work, and the condition for deleting this file: \`bun run check:config-bridge\`.
`;

/** A declaration this package exports, and the specifier a consumer should import it from. */
export type BridgedDeclaration = { name: string; specifier: string };

/**
 * `tests/` and any `*.acceptance.ts` prove the package is importable and are not part of the configuration
 * model, so they are excluded from the bridge, from schema generation and from documentation extraction.
 */
export const isConfigModelModule = (file: string) => file.endsWith('.ts') && !file.endsWith('.acceptance.ts');

/**
 * The subpaths the package's own manifest publishes, so the bridge can only ever emit a specifier a consumer
 * can actually resolve.
 *
 * The manifest is the single source of truth: `.` and `./shared` are intentional entry points and everything
 * else is reached through the `./*` wildcard. Duplicating that mapping in the generator is how a bridge alias
 * ends up importing from a subpath the export map does not have.
 */
export type PackageSpecifiers = { name: string; rootModule: string; named: Map<string, string>; wildcard?: string };

export const readPackageSpecifiers = (packageSrcPath: string): PackageSpecifiers => {
  const manifestPath = join(packageSrcPath, '..', 'package.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8')) as {
    name?: string;
    exports?: Record<string, string>;
  };
  if (!manifest.name || !manifest.exports) {
    throw new Error(`${manifestPath} has no name or exports map; the bridge cannot know how to import the package.`);
  }

  const moduleOf = (target: string) => basename(target, '.ts');
  const named = new Map<string, string>();
  let rootModule: string | undefined;
  let wildcard: string | undefined;

  for (const [subpath, target] of Object.entries(manifest.exports)) {
    if (subpath === '.') rootModule = moduleOf(target);
    else if (subpath === './*') wildcard = target;
    else named.set(moduleOf(target), `${manifest.name}${subpath.slice(1)}`);
  }

  if (!rootModule) {
    throw new Error(`${manifestPath} has no "." export; the bridge cannot import ${manifest.name} itself.`);
  }
  return { name: manifest.name, rootModule, named, wildcard };
};

/** The specifier a module is published under, according to the manifest. */
export const publicSpecifierFor = (moduleName: string, specifiers: PackageSpecifiers): string => {
  if (moduleName === specifiers.rootModule) return specifiers.name;
  const named = specifiers.named.get(moduleName);
  if (named) return named;
  if (!specifiers.wildcard) {
    throw new Error(`${specifiers.name} publishes no subpath for "${moduleName}" and has no "./*" export.`);
  }
  return `${specifiers.name}/${moduleName}`;
};

/**
 * Reads the package's exported type names from each module's export table rather than from its statements, so
 * `export { Foo }` after a local declaration and `export type { Bar } from './other'` are seen the same way the
 * compiler sees them. Runtime-only exports are skipped: a `const` has no ambient consumers, because CLI code
 * imports the value directly, which is the end state this bridge exists to reach.
 */
export const readPackageDeclarations = (packageSrcPath: string): BridgedDeclaration[] => {
  const specifiers = readPackageSpecifiers(packageSrcPath);
  const modules = readdirSync(packageSrcPath).filter(isConfigModelModule);
  if (modules.length === 0) {
    throw new Error(`No @stacktape/config modules found in ${packageSrcPath}. Refusing to generate an empty bridge.`);
  }

  const program = ts.createProgram(
    modules.map((file) => join(packageSrcPath, file)),
    { noEmit: true, target: ts.ScriptTarget.ES2022, moduleResolution: ts.ModuleResolutionKind.Bundler, types: [] }
  );
  const checker = program.getTypeChecker();

  const declarations = program
    .getSourceFiles()
    .filter((sourceFile) => modules.includes(basename(sourceFile.fileName)))
    .flatMap((sourceFile) => {
      const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
      if (!moduleSymbol) {
        throw new Error(`${sourceFile.fileName} is not a module; every configuration module must export something.`);
      }
      const specifier = publicSpecifierFor(basename(sourceFile.fileName, '.ts'), specifiers);
      return checker
        .getExportsOfModule(moduleSymbol)
        .filter((symbol) => symbol.getName() !== 'default')
        .filter((symbol) => isBridgeableType(symbol, checker))
        .map((symbol) => ({ name: symbol.getName(), specifier }));
    });

  if (declarations.length === 0) {
    throw new Error(`No exported type declarations found in ${packageSrcPath}. Refusing to generate an empty bridge.`);
  }

  const duplicates = [
    ...new Set(declarations.map(({ name }) => name).filter((name, index, all) => all.indexOf(name) !== index))
  ];
  if (duplicates.length > 0) {
    throw new Error(`@stacktape/config exports the same name from more than one module: ${duplicates.join(', ')}`);
  }

  return declarations.sort((a, b) => a.name.localeCompare(b.name));
};

/** Whether an exported symbol can be aliased as `type X = import(...).X`. */
const isBridgeableType = (symbol: ts.Symbol, checker: ts.TypeChecker): boolean => {
  const resolved = symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
  const typeFlags = ts.SymbolFlags.Interface | ts.SymbolFlags.TypeAlias | ts.SymbolFlags.Class | ts.SymbolFlags.Enum;
  return (resolved.flags & typeFlags) !== 0;
};

export const buildConfigBridge = (declarations: BridgedDeclaration[]): string => {
  const aliases = declarations
    .map(({ name, specifier }) => `type ${name} = import('${specifier}').${name};`)
    .join('\n');
  return `${BRIDGE_HEADER}\n${aliases}\n`;
};

export const generateConfigBridge = async () => {
  logInfo('Generating the @stacktape/config ambient bridge...');
  const declarations = readPackageDeclarations(CONFIG_PACKAGE_SRC_PATH);
  await outputFile(CONFIG_BRIDGE_PATH, buildConfigBridge(declarations), 'utf-8');
  logSuccess(`Bridged ${declarations.length} configuration declarations.`);
};

if (import.meta.main) {
  generateConfigBridge();
}
