import { join } from 'node:path';
import { logInfo, logSuccess } from '@scripts/support/logging';
import { outputFile } from 'fs-extra';

/**
 * Regenerates the catalogue of AWS-managed OpenTelemetry (Application Signals) Lambda layer ARNs
 * used for tracing instrumentation. The canonical upstream source is the data file behind the
 * ADOT docs table at https://aws-otel.github.io/docs/getting-started/lambda#adot-lambda-layer-arns.
 * Layer versions drift per region and per release, so re-run this at release time.
 */
const UPSTREAM_URL = 'https://raw.githubusercontent.com/aws-otel/aws-otel.github.io/main/src/config/lambdaLayerArns.js';
const OUTPUT_PATH = join(import.meta.dir, '../src/domain/config-manager/utils/otel-lambda-layer-arns.ts');

const RUNTIME_TABS = ['nodejs', 'python', 'java', 'dotnet'] as const;

const parseTabArns = ({ source, tab }: { source: string; tab: string }): Record<string, string> => {
  const tabBlockMatch = source.match(new RegExp(`${tab}: \\{\\s*label:[^{]*arns: \\{([\\s\\S]*?)\\}`));
  if (!tabBlockMatch) {
    throw new Error(`Could not find the "${tab}" arns block in the upstream data file. Its format likely changed.`);
  }
  const arns: Record<string, string> = {};
  for (const [, region, arn] of tabBlockMatch[1].matchAll(/"([a-z0-9-]+)":\s*"(arn:aws[^"]+)"/g)) {
    arns[region] = arn;
  }
  if (Object.keys(arns).length < 10) {
    throw new Error(
      `Parsed only ${Object.keys(arns).length} regions for "${tab}". Refusing to write a gutted catalogue.`
    );
  }
  return arns;
};

const refreshOtelLambdaLayers = async () => {
  const response = await fetch(UPSTREAM_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${UPSTREAM_URL}: ${response.status}`);
  }
  const upstreamSource = await response.text();

  const catalogue = Object.fromEntries(
    RUNTIME_TABS.map((tab) => {
      const arns = parseTabArns({ source: upstreamSource, tab });
      logInfo(`${tab}: ${Object.keys(arns).length} regions`);
      return [tab, Object.fromEntries(Object.entries(arns).sort(([a], [b]) => a.localeCompare(b)))];
    })
  );

  const moduleSource = `/**
 * AWS-managed OpenTelemetry (Application Signals) Lambda layer ARNs, keyed by runtime family and region.
 *
 * Regenerated by \`pnpm refresh:catalog:otel-layers\` (scripts/refresh-otel-lambda-layers.ts) from the
 * canonical upstream data file behind https://aws-otel.github.io/docs/getting-started/lambda. Do not
 * hand-edit. Old layer versions remain usable after upstream bumps, so a stale catalogue degrades
 * gracefully; refresh at release time.
 */
export type OtelLayerRuntimeFamily = ${RUNTIME_TABS.map((tab) => `'${tab}'`).join(' | ')};

export const OTEL_LAMBDA_LAYER_ARNS: Record<OtelLayerRuntimeFamily, Record<string, string>> = ${JSON.stringify(
    catalogue,
    null,
    2
  )};
`;

  await outputFile(OUTPUT_PATH, moduleSource);
  logSuccess(`Wrote ${OUTPUT_PATH}`);
};

refreshOtelLambdaLayers();
