import type { StpResourceType } from '@domain-services/config-manager/resolved-types/resources';
export type StacktapePrerequisite = 'docker' | 'node' | 'java' | 'ruby' | 'python' | 'go' | 'php' | 'dotnet';

export type SupportedAutogeneratedConfigType =
  | 'web-service-apigw'
  | 'web-service-alb'
  | 'cron-job'
  | 'spa-website'
  | 'static-website'
  | 'nextjs-website';

export type RawStarterProjectMetadata = {
  tags: string[];
  name: string;
  icon?: string;
  prerequisites: StacktapePrerequisite[];
  disableLintingOption?: boolean;
  hasOwnTsConfig?: boolean;
  priority?: number;
};

export type UsedResourceData = {
  name: string;
  type: StpResourceType;
  containerNames: string[];
};

export type StarterProjectMetadata = RawStarterProjectMetadata & {
  projectType: 'es' | 'python' | 'ruby' | 'java' | 'go' | 'php' | 'dotnet' | 'elixir' | 'rust' | 'docker' | 'other';
  usedResourceTypes: StpResourceType[];
  usedResources: UsedResourceData[];
  githubLink: string;
  isRestApi: boolean;
  hasReact: boolean;
  hasPrisma: boolean;
  hasTypescript: boolean;
  hasCognito: boolean;
  hasNextJs: boolean;
  isWebsite: boolean;
  isSpaWebsite: boolean;
  isServerSideRenderedWebsite: boolean;
  isStaticWebsite: boolean;
  starterProjectId: string;
  description: string;
};
