import CustomDBEngineVersion_ from './customDbEngineVersion';
import DBCluster_ from './dbCluster';
import DBClusterParameterGroup_ from './dbClusterParameterGroup';
import DBInstance_ from './dbInstance';
import DBParameterGroup_ from './dbParameterGroup';
import DBProxy_ from './dbProxy';
import DBProxyEndpoint_ from './dbProxyEndpoint';
import DBProxyTargetGroup_ from './dbProxyTargetGroup';
import DBSecurityGroup_ from './dbSecurityGroup';
import DBSecurityGroupIngress_ from './dbSecurityGroupIngress';
import DBShardGroup_ from './dbShardGroup';
import DBSubnetGroup_ from './dbSubnetGroup';
import EventSubscription_ from './eventSubscription';
import GlobalCluster_ from './globalCluster';
import Integration_ from './integration';
import OptionGroup_ from './optionGroup';
export namespace RDS {
  export const CustomDBEngineVersion = CustomDBEngineVersion_;
  export const DBCluster = DBCluster_;
  export const DBClusterParameterGroup = DBClusterParameterGroup_;
  export const DBInstance = DBInstance_;
  export const DBParameterGroup = DBParameterGroup_;
  export const DBProxy = DBProxy_;
  export const DBProxyEndpoint = DBProxyEndpoint_;
  export const DBProxyTargetGroup = DBProxyTargetGroup_;
  export const DBSecurityGroup = DBSecurityGroup_;
  export const DBSecurityGroupIngress = DBSecurityGroupIngress_;
  export const DBShardGroup = DBShardGroup_;
  export const DBSubnetGroup = DBSubnetGroup_;
  export const EventSubscription = EventSubscription_;
  export const GlobalCluster = GlobalCluster_;
  export const Integration = Integration_;
  export const OptionGroup = OptionGroup_;
  export type CustomDBEngineVersion = CustomDBEngineVersion_;
  export type DBCluster = DBCluster_;
  export type DBClusterParameterGroup = DBClusterParameterGroup_;
  export type DBInstance = DBInstance_;
  export type DBParameterGroup = DBParameterGroup_;
  export type DBProxy = DBProxy_;
  export type DBProxyEndpoint = DBProxyEndpoint_;
  export type DBProxyTargetGroup = DBProxyTargetGroup_;
  export type DBSecurityGroup = DBSecurityGroup_;
  export type DBSecurityGroupIngress = DBSecurityGroupIngress_;
  export type DBShardGroup = DBShardGroup_;
  export type DBSubnetGroup = DBSubnetGroup_;
  export type EventSubscription = EventSubscription_;
  export type GlobalCluster = GlobalCluster_;
  export type Integration = Integration_;
  export type OptionGroup = OptionGroup_;
}
