import AppBlock_ from './appBlock';
import AppBlockBuilder_ from './appBlockBuilder';
import Application_ from './application';
import ApplicationEntitlementAssociation_ from './applicationEntitlementAssociation';
import ApplicationFleetAssociation_ from './applicationFleetAssociation';
import DirectoryConfig_ from './directoryConfig';
import Entitlement_ from './entitlement';
import Fleet_ from './fleet';
import ImageBuilder_ from './imageBuilder';
import Stack_ from './stack';
import StackFleetAssociation_ from './stackFleetAssociation';
import StackUserAssociation_ from './stackUserAssociation';
import User_ from './user';
export namespace AppStream {
  export const AppBlock = AppBlock_;
  export const AppBlockBuilder = AppBlockBuilder_;
  export const Application = Application_;
  export const ApplicationEntitlementAssociation = ApplicationEntitlementAssociation_;
  export const ApplicationFleetAssociation = ApplicationFleetAssociation_;
  export const DirectoryConfig = DirectoryConfig_;
  export const Entitlement = Entitlement_;
  export const Fleet = Fleet_;
  export const ImageBuilder = ImageBuilder_;
  export const Stack = Stack_;
  export const StackFleetAssociation = StackFleetAssociation_;
  export const StackUserAssociation = StackUserAssociation_;
  export const User = User_;
  export type AppBlock = AppBlock_;
  export type AppBlockBuilder = AppBlockBuilder_;
  export type Application = Application_;
  export type ApplicationEntitlementAssociation = ApplicationEntitlementAssociation_;
  export type ApplicationFleetAssociation = ApplicationFleetAssociation_;
  export type DirectoryConfig = DirectoryConfig_;
  export type Entitlement = Entitlement_;
  export type Fleet = Fleet_;
  export type ImageBuilder = ImageBuilder_;
  export type Stack = Stack_;
  export type StackFleetAssociation = StackFleetAssociation_;
  export type StackUserAssociation = StackUserAssociation_;
  export type User = User_;
}
