import Agent_ from './agent';
import AgentAlias_ from './agentAlias';
import ApplicationInferenceProfile_ from './applicationInferenceProfile';
import Blueprint_ from './blueprint';
import DataAutomationProject_ from './dataAutomationProject';
import DataSource_ from './dataSource';
import EnforcedGuardrailConfiguration_ from './enforcedGuardrailConfiguration';
import Flow_ from './flow';
import FlowAlias_ from './flowAlias';
import FlowVersion_ from './flowVersion';
import Guardrail_ from './guardrail';
import GuardrailVersion_ from './guardrailVersion';
import IntelligentPromptRouter_ from './intelligentPromptRouter';
import KnowledgeBase_ from './knowledgeBase';
import Prompt_ from './prompt';
import PromptVersion_ from './promptVersion';
import ResourcePolicy_ from './resourcePolicy';
import DataAutomationLibrary_ from './dataAutomationLibrary';
import AutomatedReasoningPolicy_ from './automatedReasoningPolicy';
import AutomatedReasoningPolicyVersion_ from './automatedReasoningPolicyVersion';
export namespace Bedrock {
  export const Agent = Agent_;
  export const AgentAlias = AgentAlias_;
  export const ApplicationInferenceProfile = ApplicationInferenceProfile_;
  export const Blueprint = Blueprint_;
  export const DataAutomationProject = DataAutomationProject_;
  export const DataSource = DataSource_;
  export const EnforcedGuardrailConfiguration = EnforcedGuardrailConfiguration_;
  export const Flow = Flow_;
  export const FlowAlias = FlowAlias_;
  export const FlowVersion = FlowVersion_;
  export const Guardrail = Guardrail_;
  export const GuardrailVersion = GuardrailVersion_;
  export const IntelligentPromptRouter = IntelligentPromptRouter_;
  export const KnowledgeBase = KnowledgeBase_;
  export const Prompt = Prompt_;
  export const PromptVersion = PromptVersion_;
  export const ResourcePolicy = ResourcePolicy_;
  export const DataAutomationLibrary = DataAutomationLibrary_;
  export const AutomatedReasoningPolicy = AutomatedReasoningPolicy_;
  export const AutomatedReasoningPolicyVersion = AutomatedReasoningPolicyVersion_;
  export type Agent = Agent_;
  export type AgentAlias = AgentAlias_;
  export type ApplicationInferenceProfile = ApplicationInferenceProfile_;
  export type Blueprint = Blueprint_;
  export type DataAutomationProject = DataAutomationProject_;
  export type DataSource = DataSource_;
  export type EnforcedGuardrailConfiguration = EnforcedGuardrailConfiguration_;
  export type Flow = Flow_;
  export type FlowAlias = FlowAlias_;
  export type FlowVersion = FlowVersion_;
  export type Guardrail = Guardrail_;
  export type GuardrailVersion = GuardrailVersion_;
  export type IntelligentPromptRouter = IntelligentPromptRouter_;
  export type KnowledgeBase = KnowledgeBase_;
  export type Prompt = Prompt_;
  export type PromptVersion = PromptVersion_;
  export type ResourcePolicy = ResourcePolicy_;
  export type DataAutomationLibrary = DataAutomationLibrary_;
  export type AutomatedReasoningPolicy = AutomatedReasoningPolicy_;
  export type AutomatedReasoningPolicyVersion = AutomatedReasoningPolicyVersion_;
}
