import Api_ from './api';
import ApiGatewayManagedOverrides_ from './apiGatewayManagedOverrides';
import ApiMapping_ from './apiMapping';
import Authorizer_ from './authorizer';
import Deployment_ from './deployment';
import DomainName_ from './domainName';
import Integration_ from './integration';
import IntegrationResponse_ from './integrationResponse';
import Model_ from './model';
import Route_ from './route';
import RouteResponse_ from './routeResponse';
import RoutingRule_ from './routingRule';
import Stage_ from './stage';
import VpcLink_ from './vpcLink';
export namespace ApiGatewayV2 {
  export const Api = Api_;
  export const ApiGatewayManagedOverrides = ApiGatewayManagedOverrides_;
  export const ApiMapping = ApiMapping_;
  export const Authorizer = Authorizer_;
  export const Deployment = Deployment_;
  export const DomainName = DomainName_;
  export const Integration = Integration_;
  export const IntegrationResponse = IntegrationResponse_;
  export const Model = Model_;
  export const Route = Route_;
  export const RouteResponse = RouteResponse_;
  export const RoutingRule = RoutingRule_;
  export const Stage = Stage_;
  export const VpcLink = VpcLink_;
  export type Api = Api_;
  export type ApiGatewayManagedOverrides = ApiGatewayManagedOverrides_;
  export type ApiMapping = ApiMapping_;
  export type Authorizer = Authorizer_;
  export type Deployment = Deployment_;
  export type DomainName = DomainName_;
  export type Integration = Integration_;
  export type IntegrationResponse = IntegrationResponse_;
  export type Model = Model_;
  export type Route = Route_;
  export type RouteResponse = RouteResponse_;
  export type RoutingRule = RoutingRule_;
  export type Stage = Stage_;
  export type VpcLink = VpcLink_;
}
