import AccessKey_ from './accessKey';
import Group_ from './group';
import GroupPolicy_ from './groupPolicy';
import InstanceProfile_ from './instanceProfile';
import ManagedPolicy_ from './managedPolicy';
import OIDCProvider_ from './oidcProvider';
import Policy_ from './policy';
import Role_ from './role';
import RolePolicy_ from './rolePolicy';
import SAMLProvider_ from './samlProvider';
import ServerCertificate_ from './serverCertificate';
import ServiceLinkedRole_ from './serviceLinkedRole';
import User_ from './user';
import UserPolicy_ from './userPolicy';
import UserToGroupAddition_ from './userToGroupAddition';
import VirtualMFADevice_ from './virtualMfaDevice';
export namespace IAM {
  export const AccessKey = AccessKey_;
  export const Group = Group_;
  export const GroupPolicy = GroupPolicy_;
  export const InstanceProfile = InstanceProfile_;
  export const ManagedPolicy = ManagedPolicy_;
  export const OIDCProvider = OIDCProvider_;
  export const Policy = Policy_;
  export const Role = Role_;
  export const RolePolicy = RolePolicy_;
  export const SAMLProvider = SAMLProvider_;
  export const ServerCertificate = ServerCertificate_;
  export const ServiceLinkedRole = ServiceLinkedRole_;
  export const User = User_;
  export const UserPolicy = UserPolicy_;
  export const UserToGroupAddition = UserToGroupAddition_;
  export const VirtualMFADevice = VirtualMFADevice_;
  export type AccessKey = AccessKey_;
  export type Group = Group_;
  export type GroupPolicy = GroupPolicy_;
  export type InstanceProfile = InstanceProfile_;
  export type ManagedPolicy = ManagedPolicy_;
  export type OIDCProvider = OIDCProvider_;
  export type Policy = Policy_;
  export type Role = Role_;
  export type RolePolicy = RolePolicy_;
  export type SAMLProvider = SAMLProvider_;
  export type ServerCertificate = ServerCertificate_;
  export type ServiceLinkedRole = ServiceLinkedRole_;
  export type User = User_;
  export type UserPolicy = UserPolicy_;
  export type UserToGroupAddition = UserToGroupAddition_;
  export type VirtualMFADevice = VirtualMFADevice_;
}
