import Classifier_ from './classifier';
import Connection_ from './connection';
import Crawler_ from './crawler';
import CustomEntityType_ from './customEntityType';
import DataCatalogEncryptionSettings_ from './dataCatalogEncryptionSettings';
import DataQualityRuleset_ from './dataQualityRuleset';
import Database_ from './database';
import DevEndpoint_ from './devEndpoint';
import Job_ from './job';
import MLTransform_ from './mlTransform';
import Partition_ from './partition';
import Registry_ from './registry';
import Schema_ from './schema';
import SchemaVersion_ from './schemaVersion';
import SchemaVersionMetadata_ from './schemaVersionMetadata';
import SecurityConfiguration_ from './securityConfiguration';
import Table_ from './table';
import TableOptimizer_ from './tableOptimizer';
import Trigger_ from './trigger';
import UsageProfile_ from './usageProfile';
import Workflow_ from './workflow';
export namespace Glue {
  export const Classifier = Classifier_;
  export const Connection = Connection_;
  export const Crawler = Crawler_;
  export const CustomEntityType = CustomEntityType_;
  export const DataCatalogEncryptionSettings = DataCatalogEncryptionSettings_;
  export const DataQualityRuleset = DataQualityRuleset_;
  export const Database = Database_;
  export const DevEndpoint = DevEndpoint_;
  export const Job = Job_;
  export const MLTransform = MLTransform_;
  export const Partition = Partition_;
  export const Registry = Registry_;
  export const Schema = Schema_;
  export const SchemaVersion = SchemaVersion_;
  export const SchemaVersionMetadata = SchemaVersionMetadata_;
  export const SecurityConfiguration = SecurityConfiguration_;
  export const Table = Table_;
  export const TableOptimizer = TableOptimizer_;
  export const Trigger = Trigger_;
  export const UsageProfile = UsageProfile_;
  export const Workflow = Workflow_;
  export type Classifier = Classifier_;
  export type Connection = Connection_;
  export type Crawler = Crawler_;
  export type CustomEntityType = CustomEntityType_;
  export type DataCatalogEncryptionSettings = DataCatalogEncryptionSettings_;
  export type DataQualityRuleset = DataQualityRuleset_;
  export type Database = Database_;
  export type DevEndpoint = DevEndpoint_;
  export type Job = Job_;
  export type MLTransform = MLTransform_;
  export type Partition = Partition_;
  export type Registry = Registry_;
  export type Schema = Schema_;
  export type SchemaVersion = SchemaVersion_;
  export type SchemaVersionMetadata = SchemaVersionMetadata_;
  export type SecurityConfiguration = SecurityConfiguration_;
  export type Table = Table_;
  export type TableOptimizer = TableOptimizer_;
  export type Trigger = Trigger_;
  export type UsageProfile = UsageProfile_;
  export type Workflow = Workflow_;
}
