import Account_ from './account';
import ApiKey_ from './apiKey';
import Authorizer_ from './authorizer';
import BasePathMapping_ from './basePathMapping';
import BasePathMappingV2_ from './basePathMappingV2';
import ClientCertificate_ from './clientCertificate';
import Deployment_ from './deployment';
import DocumentationPart_ from './documentationPart';
import DocumentationVersion_ from './documentationVersion';
import DomainName_ from './domainName';
import DomainNameAccessAssociation_ from './domainNameAccessAssociation';
import DomainNameV2_ from './domainNameV2';
import GatewayResponse_ from './gatewayResponse';
import Method_ from './method';
import Model_ from './model';
import RequestValidator_ from './requestValidator';
import Resource_ from './resource';
import RestApi_ from './restApi';
import Stage_ from './stage';
import UsagePlan_ from './usagePlan';
import UsagePlanKey_ from './usagePlanKey';
import VpcLink_ from './vpcLink';
export namespace ApiGateway {
  export const Account = Account_;
  export const ApiKey = ApiKey_;
  export const Authorizer = Authorizer_;
  export const BasePathMapping = BasePathMapping_;
  export const BasePathMappingV2 = BasePathMappingV2_;
  export const ClientCertificate = ClientCertificate_;
  export const Deployment = Deployment_;
  export const DocumentationPart = DocumentationPart_;
  export const DocumentationVersion = DocumentationVersion_;
  export const DomainName = DomainName_;
  export const DomainNameAccessAssociation = DomainNameAccessAssociation_;
  export const DomainNameV2 = DomainNameV2_;
  export const GatewayResponse = GatewayResponse_;
  export const Method = Method_;
  export const Model = Model_;
  export const RequestValidator = RequestValidator_;
  export const Resource = Resource_;
  export const RestApi = RestApi_;
  export const Stage = Stage_;
  export const UsagePlan = UsagePlan_;
  export const UsagePlanKey = UsagePlanKey_;
  export const VpcLink = VpcLink_;
  export type Account = Account_;
  export type ApiKey = ApiKey_;
  export type Authorizer = Authorizer_;
  export type BasePathMapping = BasePathMapping_;
  export type BasePathMappingV2 = BasePathMappingV2_;
  export type ClientCertificate = ClientCertificate_;
  export type Deployment = Deployment_;
  export type DocumentationPart = DocumentationPart_;
  export type DocumentationVersion = DocumentationVersion_;
  export type DomainName = DomainName_;
  export type DomainNameAccessAssociation = DomainNameAccessAssociation_;
  export type DomainNameV2 = DomainNameV2_;
  export type GatewayResponse = GatewayResponse_;
  export type Method = Method_;
  export type Model = Model_;
  export type RequestValidator = RequestValidator_;
  export type Resource = Resource_;
  export type RestApi = RestApi_;
  export type Stage = Stage_;
  export type UsagePlan = UsagePlan_;
  export type UsagePlanKey = UsagePlanKey_;
  export type VpcLink = VpcLink_;
}
