/**
 * The CI-shaped install baseline. The pipeline has already run its frozen install, and then `stacktape package` starts
 * in a fresh process with `CI=1`. Two owned one-Lambda projects are measured, one npm and one pnpm with an exact
 * `packageManager` declaration. Each has `workspaces: []`, so `findProjectRoot` stops at the project, and each depends
 * only on a local tarball its handler imports.
 *
 * Outside every timed sample:
 * - The dependency tarball is packed once with `npm pack`; it has no lifecycle script.
 * - Each project's lockfile is generated by its own manager. Only that lockfile is kept, since the CLI's lock detection
 *   takes `package-lock.json` before `pnpm-lock.yaml`.
 * - pnpm's exact declared version is fetched once into an owned dlx cache (`prewarmPnpm`), outside the sandbox. It is
 *   the only step with network access.
 * - Each project is installed inside the network sandbox with the exact command the CLI runs in CI:
 *   `npm ci --no-audit --no-update-notifier`, or
 *   `pnpm dlx pnpm@X install --frozen-lockfile`. The result becomes an immutable seed of the project and the manager's
 *   cache and state.
 * - Before each sample the seed is copied back to the same absolute paths with one `cp -a`, so pnpm's recorded store
 *   path and its hard links hold. The copy is then checked (`checkPrepared`): inputs byte-identical, `node_modules`
 *   present, the sentinel importable and no install lock. There is no install marker, or, for the marker mate, one
 *   holding the lockfile's SHA-256.
 *
 * Each manager is also sampled `partial`: its seed without the record the manager writes last, pnpm's
 * `node_modules/.modules.yaml` and current lockfile `node_modules/.pnpm/lock.yaml`, or npm's hidden lockfile
 * `node_modules/.package-lock.json`. That is what an interrupted install leaves: the packages resolve, but the manager
 * never recorded finishing.
 *
 * Every sample is held to what the CLI's installer (`dependency-installer.ts`) must do (`checkCiInstallSample`):
 * - A partial sample installs with the exact command, detects CI and leaves a marker equal to the lockfile's SHA-256.
 *   The marker is read directly, because `saveInstallHash` swallows write errors.
 * - A markerless sample holds the pipeline's completed install: it decides `<manager>-install-verified`, starts no
 *   installer and writes no marker.
 * - A marker sample decides `marker-matches` and starts no installer.
 * - Both exit 0, leave no install lock, change no input, make no DNS lookup and no request beyond the CLI's own, and
 *   meet the artifact contract.
 * - The function ZIP, extracted with `unzip` and invoked with Node, must return the sentinel.
 * - Within each manager, every sample's function ZIP has the same canonical content and name digest.
 *   npm and pnpm payloads are never compared.
 */
import type { FixtureRequest } from './external-service-fixture';
import type { DnsQuery } from './network-sandbox';
import type { ContractResult, InstalledHelperLambda } from './cli-artifact-contract';
import type { SampleRecord } from './cli-report';
import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { lstat, mkdir, readdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { runBoundedProcess } from './bounded-process';
import { checkArtifactContract } from './cli-artifact-contract';

export const CI_INSTALL_MANAGERS = ['npm', 'pnpm'] as const;
export type CiInstallManager = (typeof CI_INSTALL_MANAGERS)[number];
export const CI_INSTALL_STATES = [
  'markerless',
  'marker',
  'partial',
  'marker-manifest-changed',
  'marker-package-removed',
  'marker-scripts-changed'
] as const;
/**
 * States that start from a valid Stacktape marker and then break the tree it vouches for: the manifest's direct
 * specifier changes without a lockfile update, or the direct package is removed from `node_modules`.
 */
export const MARKER_STATES: readonly CiInstallState[] = [
  'marker',
  'marker-manifest-changed',
  'marker-package-removed',
  'marker-scripts-changed'
];
/** The file the root script `marker-scripts-changed` adds writes, so a sample can show the script ran. */
export const ROOT_SCRIPT_EVIDENCE = 'root-postinstall-ran';
/** The root script `marker-scripts-changed` adds; the lockfile and dependencies stay as locked. */
export const ADDED_ROOT_SCRIPTS = {
  postinstall: `node -e "require('fs').writeFileSync('${ROOT_SCRIPT_EVIDENCE}', '')"`
};
/** The specifier `marker-manifest-changed` writes instead of the locked one; the lockfile is not updated. */
export const CHANGED_SPECIFIER = 'file:vendor/fixture-dep-1.0.1.tgz';
/**
 * The version 3 marker `dependency-installer.ts` writes after a successful install, stated here independently: the
 * lockfile's SHA-256, a SHA-256 over the complete root manifest's SHA-256 (the fixture has no install configuration
 * file), and the direct dependencies present afterwards.
 */
export const validMarkerFor = ({ lockSha256, manifest }: { lockSha256: string; manifest: string }) =>
  JSON.stringify({
    version: 3,
    lockfileSha256: lockSha256,
    inputsSha256: sha256Bytes(JSON.stringify({ manifestSha256: sha256Bytes(manifest), config: {} })),
    installedDirectDependencies: [DEPENDENCY.name]
  });
export type CiInstallState = (typeof CI_INSTALL_STATES)[number];
/** What each manager writes when an install has finished, and the `partial` state lacks. */
export const COMPLETION_RECORD: Record<CiInstallManager, string[]> = {
  npm: ['node_modules/.package-lock.json'],
  pnpm: ['node_modules/.modules.yaml', 'node_modules/.pnpm/lock.yaml']
};

export const DEPENDENCY = {
  name: 'fixture-dep',
  version: '1.0.0',
  tarball: 'fixture-dep-1.0.0.tgz',
  sentinel: 'stacktape-ci-install-sentinel-7f3a'
} as const;

export const FUNCTION_NAME = 'ciHandler';
/** `localStatePaths.dependencyInstallHashFile` and `dependencyInstallLockFile`, relative to the project. */
export const INSTALL_MARKER = 'node_modules/.stacktape-install-hash';
export const INSTALL_LOCK = '.stacktape-install.lock';
export const LOCKFILE: Record<CiInstallManager, string> = { npm: 'package-lock.json', pnpm: 'pnpm-lock.yaml' };
/** Every lockfile `getLockFileData` detects, in its order, and npm's shrinkwrap. */
export const KNOWN_LOCKFILES = [
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'bun.lock',
  'deno.lockb',
  'npm-shrinkwrap.json'
];
/** The files a sample must leave byte-identical. */
export const inputFiles = (manager: CiInstallManager) => [
  'package.json',
  LOCKFILE[manager],
  `vendor/${DEPENDENCY.tarball}`,
  'src/handler.js',
  'stacktape.yml'
];

/** The command the CLI's install table gives each manager in CI (`es-install-scripts.ts`), stated here independently. */
export const expectedInstallCommand = ({ manager, pnpmVersion }: { manager: CiInstallManager; pnpmVersion: string }) =>
  manager === 'npm'
    ? 'npm ci --no-audit --no-update-notifier'
    : `pnpm dlx pnpm@${pnpmVersion} install --frozen-lockfile`;

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

export const dependencyFiles = (): Record<string, string> => ({
  'package.json': json({
    name: DEPENDENCY.name,
    version: DEPENDENCY.version,
    description: 'Stacktape CI-install measurement dependency',
    license: 'UNLICENSED',
    main: 'index.js',
    files: ['index.js']
  }),
  'index.js': `'use strict';\nexports.sentinel = '${DEPENDENCY.sentinel}';\n`
});

export const projectFiles = ({
  manager,
  pnpmVersion
}: {
  manager: CiInstallManager;
  pnpmVersion: string;
}): Record<string, string> => ({
  'package.json': json({
    name: `ci-install-${manager}`,
    version: '1.0.0',
    private: true,
    type: 'module',
    workspaces: [],
    ...(manager === 'pnpm' && { packageManager: `pnpm@${pnpmVersion}` }),
    dependencies: { [DEPENDENCY.name]: `file:vendor/${DEPENDENCY.tarball}` }
  }),
  'src/handler.js': `import { sentinel } from '${DEPENDENCY.name}';\n\nexport const handler = async () => ({ statusCode: 200, body: sentinel });\n`,
  'stacktape.yml': [
    '# Generated by the Stacktape CI-install measurement.',
    'resources:',
    `  ${FUNCTION_NAME}:`,
    '    type: function',
    '    properties:',
    '      packaging:',
    '        type: stacktape-lambda-buildpack',
    '        properties:',
    '          entryfilePath: src/handler.js',
    '      memory: 512',
    '      timeout: 10',
    ''
  ].join('\n')
});

export const writeFiles = async (root: string, files: Record<string, string>) => {
  for (const [path, content] of Object.entries(files)) {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), content);
  }
};

/** The owned cache and state locations of a manager, all under `state`: the only extra environment its processes get. */
export const managerEnvironment = ({
  manager,
  state
}: {
  manager: CiInstallManager;
  state: string;
}): Record<string, string> =>
  manager === 'npm'
    ? { npm_config_cache: join(state, 'npm-cache') }
    : {
        XDG_CACHE_HOME: join(state, 'cache'),
        XDG_CONFIG_HOME: join(state, 'config'),
        XDG_DATA_HOME: join(state, 'data'),
        XDG_STATE_HOME: join(state, 'state'),
        PNPM_HOME: join(state, 'pnpm-home')
      };

export type ManagerLayout = { root: string; active: string; seed: string; project: string; state: string };

/**
 * Where a manager's project and tool state live. Samples always run in `active`, which is a fresh copy of `seed`. So
 * the absolute paths pnpm records, such as its store directory, are the same for every sample.
 */
export const managerLayout = (ciRoot: string, manager: CiInstallManager): ManagerLayout => {
  const root = join(ciRoot, manager);
  const active = join(root, 'active');
  return { root, active, seed: join(root, 'seed'), project: join(active, 'project'), state: join(active, 'state') };
};

export const sha256Bytes = (bytes: Buffer | string) => createHash('sha256').update(bytes).digest('hex');

export const hashInputs = async (project: string, manager: CiInstallManager) =>
  Object.fromEntries(
    await Promise.all(
      inputFiles(manager).map(async (path) => [path, sha256Bytes(await readFile(join(project, path)))] as const)
    )
  );

export const presentLockfiles = (project: string) => KNOWN_LOCKFILES.filter((file) => existsSync(join(project, file)));

export type TreeSize = { files: number; directories: number; links: number; bytes: number };

/** Every entry under `directory`, without following links. */
export const measureTree = async (directory: string): Promise<TreeSize> => {
  const size: TreeSize = { files: 0, directories: 0, links: 0, bytes: 0 };
  const visit = async (path: string) => {
    for (const entry of await readdir(path, { withFileTypes: true }).catch(() => [])) {
      const child = join(path, entry.name);
      if (entry.isSymbolicLink()) size.links += 1;
      else if (entry.isDirectory()) {
        size.directories += 1;
        await visit(child);
      } else if (entry.isFile()) {
        size.files += 1;
        size.bytes += (await lstat(child)).size;
      }
    }
  };
  await visit(directory);
  return size;
};

export const treeGrowth = (before: TreeSize, after: TreeSize): TreeSize => ({
  files: after.files - before.files,
  directories: after.directories - before.directories,
  links: after.links - before.links,
  bytes: after.bytes - before.bytes
});

/** One untimed setup or check command, with what the fixture and the DNS recorder saw while it ran. */
export type CommandRecord = {
  label: string;
  /** The executable's name and its arguments. */
  command: string;
  cwd: string;
  exitCode: number | null;
  signal: string | null;
  timedOut: boolean;
  wallMs: number;
  stdoutTail: string;
  stderrTail: string;
  /** Null when no recorder watched the command: outside the sandbox, or a check run without one. */
  fixtureRequests: FixtureRequest[] | null;
  dnsQueries: DnsQuery[] | null;
};

export type Recorders = { takeRequests: () => FixtureRequest[]; takeQueries: () => DnsQuery[] };

const TAIL = 2000;

export const runRecorded = async ({
  label,
  cmd,
  cwd,
  env,
  timeoutMs = 180_000,
  recorders
}: {
  label: string;
  cmd: string[];
  cwd: string;
  env: Record<string, string>;
  timeoutMs?: number;
  recorders?: Recorders | undefined;
}): Promise<CommandRecord> => {
  recorders?.takeRequests();
  recorders?.takeQueries();
  const run = await runBoundedProcess({ cmd, cwd, env, timeoutMs });
  return {
    label,
    command: [basename(cmd[0]!), ...cmd.slice(1)].join(' '),
    cwd,
    exitCode: run.exitCode,
    signal: run.signal,
    timedOut: run.timedOut,
    wallMs: Math.round(run.wallMs * 10) / 10,
    stdoutTail: run.stdout.slice(-TAIL),
    stderrTail: run.stderr.slice(-TAIL),
    fixtureRequests: recorders ? recorders.takeRequests() : null,
    dnsQueries: recorders ? recorders.takeQueries() : null
  };
};

export const succeeded = (record: CommandRecord) => record.exitCode === 0 && !record.timedOut;

/** Imports the dependency from the project, as the handler does, and returns what it exports as the sentinel. */
export const importSentinel = ({
  project,
  env,
  node,
  recorders
}: {
  project: string;
  env: Record<string, string>;
  node: string;
  recorders?: Recorders | undefined;
}) =>
  runRecorded({
    label: 'import the dependency sentinel',
    cmd: [
      node,
      '--input-type=module',
      '--eval',
      `const { sentinel } = await import('${DEPENDENCY.name}'); process.stdout.write(String(sentinel));`
    ],
    cwd: project,
    env,
    timeoutMs: 60_000,
    recorders
  });

export type PreparedState = {
  inputs: Record<string, string>;
  inputsIdentical: boolean;
  nodeModules: boolean;
  sentinel: string | null;
  /** `absent`, `matches` (the lockfile's SHA-256 exactly) or `other`. */
  marker: 'absent' | 'matches' | 'other';
  installLock: boolean;
  lockfiles: string[];
};

const readMarker = async (project: string) => readFile(join(project, INSTALL_MARKER), 'utf8').catch(() => null);

const describeMarker = (content: string | null, expected: string): PreparedState['marker'] =>
  content === null ? 'absent' : content === expected ? 'matches' : 'other';

/** The state of a copied seed before a sample, or of a project after one. */
export const readProjectState = async ({
  project,
  manager,
  expectedInputs,
  expectedMarker
}: {
  project: string;
  manager: CiInstallManager;
  expectedInputs: Record<string, string>;
  expectedMarker: string;
}) => {
  const inputs = await hashInputs(project, manager);
  const markerContent = await readMarker(project);
  return {
    inputs,
    inputsIdentical: JSON.stringify(inputs) === JSON.stringify(expectedInputs),
    changedInputs: Object.keys(expectedInputs).filter((path) => inputs[path] !== expectedInputs[path]),
    nodeModules: existsSync(join(project, 'node_modules')),
    markerContent,
    marker: describeMarker(markerContent, expectedMarker),
    installLock: existsSync(join(project, INSTALL_LOCK)),
    lockfiles: presentLockfiles(project)
  };
};

/** Why a prepared copy is not the precondition a sample needs; empty when it is. */
export const preparedProblems = ({
  state,
  manager,
  wanted,
  sentinel
}: {
  state: Awaited<ReturnType<typeof readProjectState>>;
  manager: CiInstallManager;
  wanted: CiInstallState;
  sentinel: string | null;
}) => [
  ...(state.inputsIdentical ? [] : [`inputs differ from the seed: ${state.changedInputs.join(', ')}`]),
  ...(state.nodeModules ? [] : ['node_modules is missing']),
  ...(wanted === 'marker-package-removed'
    ? sentinel === null
      ? []
      : ['the removed dependency still resolves']
    : sentinel === DEPENDENCY.sentinel
      ? []
      : [`the dependency sentinel did not resolve (${sentinel})`]),
  ...(state.installLock ? ['a Stacktape install lock is present'] : []),
  ...(!MARKER_STATES.includes(wanted) && state.marker !== 'absent' ? ['an install marker is present'] : []),
  ...(MARKER_STATES.includes(wanted) && state.marker !== 'matches' ? ['the install marker is not the valid one'] : []),
  ...(JSON.stringify(state.lockfiles) === JSON.stringify([LOCKFILE[manager]])
    ? []
    : [`lockfiles present: ${state.lockfiles.join(', ') || 'none'}`])
];

export type HandlerInvocation = {
  extract: CommandRecord;
  invoke: CommandRecord | null;
  /** The handler's result, parsed; null when it could not be read. */
  result: unknown;
  sentinelMatched: boolean;
};

/**
 * Extracts a function ZIP with Info-ZIP `unzip` into a new directory, imports its `index.js` with Node and calls
 * `handler`, as the Lambda runtime would. The ZIP is ours: the fixture's handler returns the dependency's sentinel.
 */
export const invokeExtractedHandler = async ({
  zipPath,
  directory,
  env,
  node,
  unzip = '/usr/bin/unzip'
}: {
  zipPath: string;
  directory: string;
  env: Record<string, string>;
  node: string;
  unzip?: string;
}): Promise<HandlerInvocation> => {
  await mkdir(directory, { recursive: true });
  const extract = await runRecorded({
    label: 'extract the function ZIP',
    cmd: [unzip, '-q', zipPath, '-d', directory],
    cwd: directory,
    env,
    timeoutMs: 60_000
  });
  if (!succeeded(extract)) return { extract, invoke: null, result: null, sentinelMatched: false };
  const invoke = await runRecorded({
    label: 'invoke the extracted handler',
    cmd: [
      node,
      '--input-type=module',
      '--eval',
      [
        "const { pathToFileURL } = await import('node:url');",
        "const module = await import(pathToFileURL(process.env.EXTRACTED_FUNCTION + '/index.js').href);",
        'const result = await module.handler({}, {});',
        'process.stdout.write(JSON.stringify(result));'
      ].join(' ')
    ],
    cwd: directory,
    env: { ...env, EXTRACTED_FUNCTION: directory },
    timeoutMs: 60_000
  });
  let result: unknown = null;
  try {
    result = succeeded(invoke) ? JSON.parse(invoke.stdoutTail) : null;
  } catch {
    result = null;
  }
  const body = typeof result === 'object' && result !== null ? (result as { body?: unknown }).body : undefined;
  return { extract, invoke, result, sentinelMatched: body === DEPENDENCY.sentinel };
};

/** The function ZIP a `package` left, found by name under the invocation's `build/lambdas`. */
export const findFunctionZip = async (project: string) => {
  const output = join(project, '.stacktape');
  for (const invocation of await readdir(output).catch(() => [] as string[])) {
    const lambdas = join(output, invocation, 'build', 'lambdas');
    const zips = (await readdir(lambdas).catch(() => [] as string[])).filter(
      (name) => name.startsWith(`${FUNCTION_NAME}-`) && name.endsWith('.zip')
    );
    if (zips.length === 1) return join(lambdas, zips[0]!);
  }
  return null;
};

/** What a CI-install sample recorded outside its timing: the prepared state, the state after, and the invocation. */
export type CiInstallSampleEvidence = {
  manager: CiInstallManager;
  state: CiInstallState;
  pnpmVersion: string;
  lockSha256: string;
  restore: CommandRecord;
  /** Restoring and checking the copy, before the sample. */
  preparationMs: number;
  before: Omit<Awaited<ReturnType<typeof readProjectState>>, 'inputs'> & { sentinel: string | null };
  after: Omit<Awaited<ReturnType<typeof readProjectState>>, 'inputs'>;
  /** The manager's cache and state, and the project's `node_modules`, after the sample minus before it. */
  growth: { state: TreeSize; nodeModules: TreeSize };
  invocation: HandlerInvocation | null;
  /** Whether the root script `marker-scripts-changed` adds left its file; false in every other state. */
  rootScriptRan?: boolean;
};

/** The requests a `package` of these projects makes by itself; anything else is a problem. */
export const EXPECTED_REQUESTS = new Set([
  'aws sts:GetCallerIdentity 200 allowed',
  'telemetry /batch 200 allowed',
  'tunnel installs.stacktape.com:443 403 refused',
  'tunnel announcements.stacktape-dev.com:443 403 refused'
]);

const describeRequest = ({ kind, target, status, allowed }: FixtureRequest) =>
  `${kind} ${target} ${status} ${allowed ? 'allowed' : 'refused'}`;

export type CiInstallSampleResult = {
  id: string;
  manager: CiInstallManager;
  state: CiInstallState;
  warmUp: boolean;
  exitCode: number | null;
  wallMs: number;
  /** The `dependencies:install` span's duration, the installer's own time inside the CLI. */
  installMs: number | null;
  decision: string | null;
  ciDetected: boolean | null;
  command: string | null;
  installerChildren: { executable: string; exitCode: number | null; ms: number | null }[];
  markerAfter: CiInstallSampleEvidence['after']['marker'] | null;
  unexpectedRequests: string[];
  dnsNames: string[];
  contract: ContractResult | null;
  functionZip: { canonicalSha256: string; nameDigest: string | null } | null;
  sentinelMatched: boolean;
  preparationMs: number | null;
  growth: CiInstallSampleEvidence['growth'] | null;
  /** Every requirement the sample did not meet; empty when it met them all. */
  problems: string[];
};

const INSTALLER_EXECUTABLES = new Set(['npm', 'pnpm', 'npx', 'pnpx', 'yarn', 'bun', 'deno', 'corepack']);

/** Holds one CI-install sample to the installer, output and isolation requirements. */
export const checkCiInstallSample = ({
  sample,
  helperLambdas
}: {
  sample: SampleRecord;
  helperLambdas: InstalledHelperLambda[];
}): CiInstallSampleResult => {
  const evidence = sample.ciInstall ?? null;
  const problems: string[] = [];
  const installs = sample.analysis?.dependencyInstalls ?? [];
  const install = installs[0] ?? null;
  const installerChildren = (sample.analysis?.subprocesses ?? [])
    .filter(({ executable }) => INSTALLER_EXECUTABLES.has(executable))
    .map(({ executable, exitCode, ms }) => ({ executable, exitCode, ms }));
  const unexpectedRequests = sample.fixtureRequests
    .map(describeRequest)
    .filter((request) => !EXPECTED_REQUESTS.has(request));
  const dnsNames = [...new Set((sample.dnsQueries ?? []).map(({ name }) => name))];
  const contract = sample.artifacts
    ? checkArtifactContract({ sample, functions: [FUNCTION_NAME], situation: 'docker-absent', helperLambdas })
    : null;
  const zipIdentity = contract?.identities.find(({ key }) => key === `function ZIP ${FUNCTION_NAME}`) ?? null;

  if (!evidence) problems.push('no CI-install evidence was recorded');
  const failureExpected = evidence?.state === 'marker-manifest-changed';
  if (!failureExpected && sample.exitCode !== 0) problems.push(`exit code ${sample.exitCode}`);
  if (failureExpected && sample.exitCode === 0) problems.push('exit code 0, not the frozen install failure');
  if (installs.length !== 1) problems.push(`${installs.length} dependencies:install spans instead of 1`);
  if (install && install.ciDetected !== true) problems.push('the installer did not detect CI');
  if (evidence) {
    const expected = expectedInstallCommand({ manager: evidence.manager, pnpmVersion: evidence.pnpmVersion });
    if (evidence.state === 'marker-scripts-changed' && !evidence.rootScriptRan) {
      problems.push('the added root postinstall script did not run');
    }
    if (evidence.state === 'markerless') {
      const verified = `${evidence.manager}-install-verified`;
      if (install?.decision !== verified) problems.push(`decided ${install?.decision ?? 'nothing'}, not ${verified}`);
      if (installerChildren.length > 0) {
        problems.push(`an installer ran: ${installerChildren.map(({ executable }) => executable).join(', ')}`);
      }
      if (evidence.after.marker !== 'absent')
        problems.push(`the install marker afterwards is ${evidence.after.marker}`);
    } else if (evidence.state === 'marker-manifest-changed') {
      if (install?.decision !== 'install-failed') {
        problems.push(`decided ${install?.decision ?? 'nothing'}, not install-failed`);
      }
      if (install?.command !== expected) problems.push(`ran ${install?.command ?? 'no command'}, not ${expected}`);
      const children = installerChildren.filter(({ executable }) => executable === evidence.manager);
      if (installerChildren.length !== 1 || children.length !== 1 || children[0]!.exitCode === 0) {
        problems.push(
          `installer children: ${installerChildren.map(({ executable, exitCode }) => `${executable} exit ${exitCode}`).join(', ') || 'none'}, not one failing ${evidence.manager}`
        );
      }
      if (evidence.after.markerContent !== evidence.before.markerContent) {
        problems.push('the install marker was rewritten after a failed install');
      }
    } else if (evidence.state !== 'marker') {
      if (install?.decision !== 'installed') problems.push(`decided ${install?.decision ?? 'nothing'}, not installed`);
      if (install?.command !== expected) problems.push(`ran ${install?.command ?? 'no command'}, not ${expected}`);
      const children = installerChildren.filter(({ executable }) => executable === evidence.manager);
      if (installerChildren.length !== 1 || children.length !== 1 || children[0]!.exitCode !== 0) {
        problems.push(
          `installer children: ${installerChildren.map(({ executable, exitCode }) => `${executable} exit ${exitCode}`).join(', ') || 'none'}, not one ${evidence.manager} exiting 0`
        );
      }
      if (evidence.after.marker !== 'matches')
        problems.push(`the install marker afterwards is ${evidence.after.marker}`);
    } else {
      if (install?.decision !== 'marker-matches') {
        problems.push(`decided ${install?.decision ?? 'nothing'}, not marker-matches`);
      }
      if (installerChildren.length > 0) {
        problems.push(`an installer ran: ${installerChildren.map(({ executable }) => executable).join(', ')}`);
      }
      if (evidence.after.marker !== 'matches')
        problems.push(`the install marker afterwards is ${evidence.after.marker}`);
    }
    if (evidence.after.installLock) problems.push('a Stacktape install lock was left');
    if (!evidence.after.inputsIdentical) problems.push(`inputs changed: ${evidence.after.changedInputs.join(', ')}`);
    if (JSON.stringify(evidence.after.lockfiles) !== JSON.stringify([LOCKFILE[evidence.manager]])) {
      problems.push(`lockfiles afterwards: ${evidence.after.lockfiles.join(', ') || 'none'}`);
    }
    if (!failureExpected && !evidence.invocation?.sentinelMatched) {
      problems.push('the extracted handler did not return the sentinel');
    }
  }
  if (dnsNames.length > 0) problems.push(`DNS lookups: ${dnsNames.join(', ')}`);
  if (unexpectedRequests.length > 0) problems.push(`requests beyond the CLI's own: ${unexpectedRequests.join(', ')}`);
  if (failureExpected) {
    if (zipIdentity) problems.push('a function ZIP was packaged despite the failed install');
  } else if (!contract) problems.push('no artifact manifest');
  else problems.push(...contract.problems.map((problem) => `artifact contract: ${problem}`));

  return {
    id: sample.id,
    manager: evidence?.manager ?? (sample.scenario.split('-')[0] as CiInstallManager),
    state: evidence?.state ?? (sample.scenario.split('-')[1] as CiInstallState),
    warmUp: sample.warmUp,
    exitCode: sample.exitCode,
    wallMs: sample.wallMs,
    installMs: install?.ms ?? null,
    decision: install?.decision ?? null,
    ciDetected: install?.ciDetected ?? null,
    command: install?.command ?? null,
    installerChildren,
    markerAfter: evidence?.after.marker ?? null,
    unexpectedRequests,
    dnsNames,
    contract,
    functionZip: zipIdentity
      ? { canonicalSha256: zipIdentity.canonicalSha256, nameDigest: zipIdentity.nameDigest }
      : null,
    sentinelMatched: evidence?.invocation?.sentinelMatched ?? false,
    preparationMs: evidence?.preparationMs ?? null,
    growth: evidence?.growth ?? null,
    problems
  };
};

export type CiInstallManagerSetup = {
  manager: CiInstallManager;
  /** Null when ready; otherwise why the manager's samples did not run. */
  blocked: string | null;
  packageManagerDeclaration: string | null;
  lockfile: string;
  lockSha256: string | null;
  inputs: Record<string, string>;
  lockfilesPresent: string[];
  steps: CommandRecord[];
  seed: { project: TreeSize; state: TreeSize } | null;
};

export type CiInstallSetup = {
  pnpmVersion: string;
  /** Run outside the sandbox, with network access, before the measurement started. */
  prewarm: CommandRecord | null;
  dependency: { sha256: string; bytes: number; pack: CommandRecord } | null;
  managers: CiInstallManagerSetup[];
};

export type CiInstallResult = {
  samples: CiInstallSampleResult[];
  setup: CiInstallSetup | null;
  setupProblems: string[];
  /** Per manager: the function ZIP's distinct canonical digests and name digests over all its samples. */
  identity: { manager: CiInstallManager; canonicalSha256: string[]; nameDigests: string[]; samples: number }[];
  retainedPerState: { manager: CiInstallManager; state: CiInstallState; retained: number }[];
};

/** Every CI-install sample checked, the setup reviewed, and each manager's function ZIP compared across its samples. */
export const evaluateCiInstall = ({
  samples,
  setup,
  helperLambdas
}: {
  samples: SampleRecord[];
  setup: CiInstallSetup | null;
  helperLambdas: InstalledHelperLambda[];
}): CiInstallResult => {
  const results = samples
    .filter(({ suite }) => suite === 'ci-install')
    .map((sample) => checkCiInstallSample({ sample, helperLambdas }));
  const setupProblems = [
    ...(setup ? [] : ['no CI-install setup was recorded']),
    ...(setup?.managers ?? []).flatMap(({ manager, blocked }) => (blocked ? [`${manager}: ${blocked}`] : [])),
    ...CI_INSTALL_MANAGERS.filter((manager) => !setup?.managers.some((entry) => entry.manager === manager)).map(
      (manager) => `${manager}: not prepared`
    )
  ];
  return {
    samples: results,
    setup,
    setupProblems,
    identity: CI_INSTALL_MANAGERS.map((manager) => {
      const own = results.filter((result) => result.manager === manager);
      return {
        manager,
        canonicalSha256: [
          ...new Set(own.flatMap(({ functionZip }) => (functionZip ? [functionZip.canonicalSha256] : [])))
        ],
        nameDigests: [
          ...new Set(own.flatMap(({ functionZip }) => (functionZip?.nameDigest ? [functionZip.nameDigest] : [])))
        ],
        samples: own.length
      };
    }),
    retainedPerState: CI_INSTALL_MANAGERS.flatMap((manager) =>
      CI_INSTALL_STATES.map((state) => ({
        manager,
        state,
        retained: results.filter((result) => result.manager === manager && result.state === state && !result.warmUp)
          .length
      }))
    )
  };
};

/** Removes the active copy and copies the seed back with one `cp -a`, which keeps its hard links and modes. */
export const restoreSeed = async ({ layout, env }: { layout: ManagerLayout; env: Record<string, string> }) => {
  await rm(layout.active, { recursive: true, force: true });
  return runRecorded({
    label: 'restore the seed',
    cmd: ['/usr/bin/cp', '-a', layout.seed, layout.active],
    cwd: layout.root,
    env,
    timeoutMs: 120_000
  });
};

const lastLine = (text: string) =>
  text
    .trim()
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .at(-1) ?? '';

/**
 * Fetches pnpm's exact available version into the owned dlx cache with `pnpm dlx pnpm@X --version`. It runs outside
 * the sandbox, with network access, and is the one step that may reach a registry. Its cache and state paths are the
 * ones every sample uses. On any failure the pnpm branch is blocked: no global pnpm stands in for it.
 */
export const prewarmPnpm = async ({
  ciRoot,
  home,
  toolsDirectory,
  systemPath
}: {
  ciRoot: string;
  home: string;
  toolsDirectory: string;
  systemPath: string[];
}) => {
  const layout = managerLayout(ciRoot, 'pnpm');
  const environment = managerEnvironment({ manager: 'pnpm', state: layout.state });
  for (const directory of Object.values(environment)) await mkdir(directory, { recursive: true });
  await mkdir(home, { recursive: true });
  const env = { HOME: home, PATH: [toolsDirectory, ...systemPath].join(':'), LANG: 'C.UTF-8', CI: '1', ...environment };
  const pnpm = join(toolsDirectory, 'pnpm');
  const version = await runRecorded({
    label: 'read the available pnpm version',
    cmd: [pnpm, '--version'],
    cwd: layout.root,
    env
  });
  const pnpmVersion = lastLine(version.stdoutTail);
  if (!succeeded(version) || !/^\d+\.\d+\.\d+$/.test(pnpmVersion)) {
    return { pnpmVersion: null, version, prewarm: null, blocked: 'the available pnpm version could not be read' };
  }
  const prewarm = await runRecorded({
    label: 'prewarm pnpm dlx (network)',
    cmd: [pnpm, 'dlx', `pnpm@${pnpmVersion}`, '--version'],
    cwd: layout.root,
    env,
    timeoutMs: 300_000
  });
  const reported = lastLine(prewarm.stdoutTail);
  const blocked = !succeeded(prewarm)
    ? `prewarming pnpm dlx failed with exit ${prewarm.exitCode}`
    : reported !== pnpmVersion
      ? `pnpm dlx reported ${reported}, not ${pnpmVersion}`
      : null;
  return { pnpmVersion, version, prewarm, blocked };
};

/** Packs the dependency once with `npm pack`; its package has no lifecycle script. */
export const packDependency = async ({
  ciRoot,
  npm,
  env,
  recorders
}: {
  ciRoot: string;
  npm: string;
  env: Record<string, string>;
  recorders: Recorders;
}) => {
  const source = join(ciRoot, 'dependency');
  const destination = join(ciRoot, 'tarball');
  await writeFiles(source, dependencyFiles());
  await mkdir(destination, { recursive: true });
  const pack = await runRecorded({
    label: 'pack the dependency',
    cmd: [npm, 'pack', '--pack-destination', destination, '--json'],
    cwd: source,
    env,
    recorders
  });
  const path = join(destination, DEPENDENCY.tarball);
  const bytes = succeeded(pack) && existsSync(path) ? await readFile(path) : null;
  return { pack, path, bytes: bytes?.length ?? 0, sha256: bytes ? sha256Bytes(bytes) : null };
};

/**
 * Writes a manager's project, generates its lockfile with that manager, installs it with the exact command the CLI runs
 * in CI, checks the result, and freezes project and state into the seed. Every step runs inside the sandbox.
 */
export const prepareManagerSeed = async ({
  manager,
  layout,
  pnpmVersion,
  tarball,
  tools,
  env,
  recorders
}: {
  manager: CiInstallManager;
  layout: ManagerLayout;
  pnpmVersion: string;
  tarball: string;
  tools: { npm: string; pnpm: string; node: string };
  env: Record<string, string>;
  recorders: Recorders;
}): Promise<CiInstallManagerSetup> => {
  const setup: CiInstallManagerSetup = {
    manager,
    blocked: null,
    packageManagerDeclaration: manager === 'pnpm' ? `pnpm@${pnpmVersion}` : null,
    lockfile: LOCKFILE[manager],
    lockSha256: null,
    inputs: {},
    lockfilesPresent: [],
    steps: [],
    seed: null
  };
  const step = async (label: string, cmd: string[]) => {
    const record = await runRecorded({ label, cmd, cwd: layout.project, env, recorders });
    setup.steps.push(record);
    if (!succeeded(record)) setup.blocked = `${label} failed with exit ${record.exitCode}`;
    return succeeded(record);
  };
  await writeFiles(layout.project, projectFiles({ manager, pnpmVersion }));
  await mkdir(join(layout.project, 'vendor'), { recursive: true });
  await writeFile(join(layout.project, 'vendor', DEPENDENCY.tarball), await readFile(tarball));
  for (const directory of Object.values(managerEnvironment({ manager, state: layout.state }))) {
    await mkdir(directory, { recursive: true });
  }

  const generated =
    manager === 'npm'
      ? await step('generate the lockfile with npm', [
          tools.npm,
          'install',
          '--package-lock-only',
          '--no-audit',
          '--no-fund'
        ])
      : await step('generate the lockfile with pnpm', [tools.pnpm, 'install', '--lockfile-only']);
  setup.lockfilesPresent = presentLockfiles(layout.project);
  if (!generated) return setup;
  if (JSON.stringify(setup.lockfilesPresent) !== JSON.stringify([LOCKFILE[manager]])) {
    setup.blocked = `lockfiles after generation: ${setup.lockfilesPresent.join(', ') || 'none'}`;
    return setup;
  }

  const exact =
    manager === 'npm'
      ? [tools.npm, 'ci', '--no-audit', '--no-update-notifier']
      : [tools.pnpm, 'dlx', `pnpm@${pnpmVersion}`, 'install', '--frozen-lockfile'];
  if (!(await step(`install with the exact CI command (${expectedInstallCommand({ manager, pnpmVersion })})`, exact))) {
    return setup;
  }
  const sentinel = await importSentinel({ project: layout.project, env, node: tools.node, recorders });
  setup.steps.push(sentinel);
  setup.lockSha256 = sha256Bytes(await readFile(join(layout.project, LOCKFILE[manager])));
  setup.inputs = await hashInputs(layout.project, manager);
  const state = await readProjectState({
    project: layout.project,
    manager,
    expectedInputs: setup.inputs,
    expectedMarker: validMarkerFor({
      lockSha256: setup.lockSha256,
      manifest: await readFile(join(layout.project, 'package.json'), 'utf8')
    })
  });
  const problems = preparedProblems({
    state,
    manager,
    wanted: 'markerless',
    sentinel: succeeded(sentinel) ? sentinel.stdoutTail : null
  });
  if (problems.length > 0) {
    setup.blocked = `the installed seed is not usable: ${problems.join('; ')}`;
    return setup;
  }
  setup.seed = { project: await measureTree(layout.project), state: await measureTree(layout.state) };
  await rm(layout.seed, { recursive: true, force: true });
  await rename(layout.active, layout.seed);
  return setup;
};

/**
 * Copies the seed back and checks the copy is the precondition the sample needs, adding the lockfile's SHA-256 as the
 * install marker for the marker mate. Fails closed: any difference stops the measurement.
 */
export const prepareSample = async ({
  layout,
  manager,
  state,
  setup,
  env,
  node
}: {
  layout: ManagerLayout;
  manager: CiInstallManager;
  state: CiInstallState;
  setup: CiInstallManagerSetup;
  env: Record<string, string>;
  node: string;
}) => {
  const started = performance.now();
  const restore = await restoreSeed({ layout, env });
  if (!succeeded(restore)) throw new Error(`Restoring the ${manager} seed failed with exit ${restore.exitCode}.`);
  const validMarker = validMarkerFor({
    lockSha256: setup.lockSha256!,
    manifest: await readFile(join(layout.project, 'package.json'), 'utf8')
  });
  if (MARKER_STATES.includes(state)) await writeFile(join(layout.project, INSTALL_MARKER), validMarker);
  const expectedInputs = { ...setup.inputs };
  if (state === 'marker-manifest-changed') {
    const manifestPath = join(layout.project, 'package.json');
    const manifest = await readFile(manifestPath, 'utf8');
    const changed = manifest.replace(`file:vendor/${DEPENDENCY.tarball}`, CHANGED_SPECIFIER);
    if (changed === manifest) throw new Error('The manifest holds no locked specifier to change.');
    await writeFile(manifestPath, changed);
    expectedInputs['package.json'] = sha256Bytes(changed);
  }
  if (state === 'marker-scripts-changed') {
    const manifestPath = join(layout.project, 'package.json');
    const changed = json({ ...JSON.parse(await readFile(manifestPath, 'utf8')), scripts: ADDED_ROOT_SCRIPTS });
    await writeFile(manifestPath, changed);
    expectedInputs['package.json'] = sha256Bytes(changed);
  }
  // A valid marker for the manifest the sample ends with: what a successful install during the sample must leave.
  const validMarkerAfter = validMarkerFor({
    lockSha256: setup.lockSha256!,
    manifest: await readFile(join(layout.project, 'package.json'), 'utf8')
  });
  // A symlink for pnpm, a directory for npm; either way the direct import stops resolving.
  if (state === 'marker-package-removed')
    await rm(join(layout.project, 'node_modules', DEPENDENCY.name), { recursive: true });
  // Without `force`, a completion record the seed lacks fails the preparation instead of passing unnoticed.
  if (state === 'partial') await Promise.all(COMPLETION_RECORD[manager].map((file) => rm(join(layout.project, file))));
  const projectState = await readProjectState({
    project: layout.project,
    manager,
    expectedInputs,
    expectedMarker: validMarker
  });
  const sentinelRun = await importSentinel({ project: layout.project, env, node });
  const sentinel = succeeded(sentinelRun) ? sentinelRun.stdoutTail : null;
  const problems = preparedProblems({ state: projectState, manager, wanted: state, sentinel });
  if (problems.length > 0) {
    throw new Error(`The ${manager} ${state} copy is not the sample's precondition: ${problems.join('; ')}.`);
  }
  const sizes = {
    state: await measureTree(layout.state),
    nodeModules: await measureTree(join(layout.project, 'node_modules'))
  };
  const { inputs: _inputs, ...before } = projectState;
  return {
    restore,
    expectedInputs,
    validMarkerAfter,
    before: { ...before, sentinel },
    sizes,
    preparationMs: Math.round((performance.now() - started) * 10) / 10
  };
};

/** What the sample left, read after the CLI exited and before its output is removed, and the extracted handler's answer. */
export const inspectAfterSample = async ({
  layout,
  manager,
  expectedInputs,
  validMarker,
  sizesBefore,
  extractDirectory,
  invocationEnv,
  node
}: {
  layout: ManagerLayout;
  manager: CiInstallManager;
  /** The inputs the sample started from: the seed's, or its changed manifest. */
  expectedInputs: Record<string, string>;
  /** The marker a successful install of the seed leaves. */
  validMarker: string;
  sizesBefore: { state: TreeSize; nodeModules: TreeSize };
  extractDirectory: string;
  invocationEnv: Record<string, string>;
  node: string;
}) => {
  const { inputs: _inputs, ...after } = await readProjectState({
    project: layout.project,
    manager,
    expectedInputs,
    expectedMarker: validMarker
  });
  const growth = {
    state: treeGrowth(sizesBefore.state, await measureTree(layout.state)),
    nodeModules: treeGrowth(sizesBefore.nodeModules, await measureTree(join(layout.project, 'node_modules')))
  };
  const zip = await findFunctionZip(layout.project);
  const invocation = zip
    ? await invokeExtractedHandler({ zipPath: zip, directory: extractDirectory, env: invocationEnv, node })
    : null;
  await rm(extractDirectory, { recursive: true, force: true });
  return { after, growth, invocation, rootScriptRan: existsSync(join(layout.project, ROOT_SCRIPT_EVIDENCE)) };
};
