/**
 * Deterministic Node Lambda projects for the offline packaging harness.
 *
 * Every byte comes from this file and a fixed seed, so a fixture of a given size is identical on every machine and at
 * every revision until `FIXTURE_GENERATOR_VERSION` changes. Dependencies are vendored as generated packages under
 * `node_modules`, so no package manager or registry is involved. The shape mirrors an ordinary service: handlers share
 * a core library, subsets of handlers share feature modules, one feature reads a binary asset, and handlers use an AWS
 * SDK client that the Lambda runtime provides.
 */
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';

/** Bump whenever generated bytes change, so reports from different generators are never compared by accident. */
export const FIXTURE_GENERATOR_VERSION = 1;

export const FIXTURE_EDITS = ['handler', 'shared', 'manifest', 'asset'] as const;
export type FixtureEdit = (typeof FIXTURE_EDITS)[number];

export type FixtureFunction = { name: string; entryfilePath: string };

export type FixtureManifest = {
  generatorVersion: number;
  functions: FixtureFunction[];
  /** Packages declared in `package.json` and present under `node_modules`. */
  dependencies: Record<string, string>;
  /** Container entrypoint over the same sources, for the opt-in Docker shape. */
  containerEntryfilePath: string;
};

export type FixtureIdentity = { contentSha256: string; files: number; bytes: number };

type Random = () => number;

/** mulberry32: small, fast and fully determined by its seed. */
const createRandom = (seedText: string): Random => {
  let seed = 2166136261;
  for (const character of seedText) {
    seed = Math.imul(seed ^ character.charCodeAt(0), 16777619) >>> 0;
  }
  return () => {
    seed = (seed + 0x6d2b79f5) >>> 0;
    let value = seed;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
};

const NOUNS = `
account address amount archive balance batch billing bucket carrier catalog channel charge checkout coupon
credit currency customer delivery discount dispatch document draft entry estimate event export fulfilment
invoice item journal label ledger line location margin member message notice order parcel payment payout period
plan price product profile quote rate receipt record refund region report request reserve review route schedule
segment session shipment slot source stock store subscription summary supplier tax tenant ticket total transfer
unit usage vendor voucher warehouse window
`
  .trim()
  .split(/\s+/);
const VERBS = `
apply build check collect compose compute derive describe estimate expand filter format group map merge
normalize parse plan prepare rank reconcile reduce render resolve score select sort split summarize validate
`
  .trim()
  .split(/\s+/);

const pick = <T>(random: Random, values: readonly T[]): T => values[Math.floor(random() * values.length)]!;
const capitalize = (word: string) => `${word[0]!.toUpperCase()}${word.slice(1)}`;
const sentence = (random: Random, words: number) => Array.from({ length: words }, () => pick(random, NOUNS)).join(' ');

/** One exported function whose structure varies with the seed, so minification and compression see real variety. */
const generateFunction = (random: Random, name: string, typed: boolean): string => {
  const input = typed ? 'input: Record<string, any>' : 'input';
  const options = typed ? 'options: { mode?: string; limit?: number } = {}' : 'options = {}';
  const [first, second, third] = [pick(random, NOUNS), pick(random, NOUNS), pick(random, NOUNS)];
  const factor = (random() * 9 + 1).toFixed(2);
  const threshold = Math.floor(random() * 5000);
  switch (Math.floor(random() * 4)) {
    case 0:
      return `export function ${name}(${input}, ${options}) {
  const ${first}Items = Array.isArray(input?.${second}) ? input.${second} : [];
  let total = ${threshold};
  for (const item of ${first}Items) {
    if (item && typeof item.${third} === 'number') {
      total += item.${third} * ${factor};
    } else if (typeof item === 'string' && item.startsWith('${pick(random, NOUNS)}')) {
      total -= ${Math.floor(random() * 100)};
    }
  }
  return { kind: '${first}-${second}', total: Math.round(total), limit: options.limit ?? ${Math.floor(random() * 200)} };
}
`;
    case 1:
      return `export function ${name}(${input}, ${options}) {
  switch (options.mode ?? input?.mode) {
    case '${first}':
      return { status: '${second}', value: (input?.${third} ?? 0) + ${threshold}, note: '${sentence(random, 6)}' };
    case '${second}':
      return { status: '${third}', value: Math.max(0, (input?.${first} ?? 0) - ${factor}), note: '${sentence(random, 5)}' };
    case '${third}':
      return { status: '${first}', value: String(input?.${second} ?? '${pick(random, NOUNS)}').length * ${factor} };
    default:
      return { status: 'unknown', value: ${threshold}, note: '${sentence(random, 8)}' };
  }
}
`;
    case 2:
      return `export function ${name}(${input}, ${options}) {
  const parts = [
    '${sentence(random, 3)}',
    String(input?.${first} ?? '${pick(random, NOUNS)}').trim(),
    (input?.${second} ?? []).length > ${Math.floor(random() * 10)} ? '${sentence(random, 4)}' : '${sentence(random, 2)}'
  ];
  const label = parts.filter(Boolean).join(options.mode === '${third}' ? ' / ' : ' - ');
  return { label, key: label.toLowerCase().replaceAll(' ', '-').slice(0, ${Math.floor(random() * 40) + 20}) };
}
`;
    default:
      return `export function ${name}(${input}, ${options}) {
  const entries = Object.entries(input ?? {}).filter(([key]) => !key.startsWith('${first}'));
  const mapped = entries.map(([key, value]) => ({
    key: \`\${key}.${second}\`,
    weight: typeof value === 'number' ? value * ${factor} : ${threshold},
    tags: ['${pick(random, NOUNS)}', '${pick(random, NOUNS)}', options.mode ?? '${third}']
  }));
  return mapped.sort((left, right) => right.weight - left.weight).slice(0, options.limit ?? ${Math.floor(random() * 30) + 5});
}
`;
  }
};

const generateFunctionNames = (random: Random, prefix: string, count: number) =>
  Array.from(
    { length: count },
    (_, index) => `${pick(random, VERBS)}${capitalize(pick(random, NOUNS))}${capitalize(prefix)}${index}`
  );

/** A package whose entry registers every function, so importing it keeps all of it, as most real libraries do. */
const generatePackage = ({
  name,
  version,
  modules,
  functionsPerModule,
  commonJs = false
}: {
  name: string;
  version: string;
  modules: number;
  functionsPerModule: number;
  commonJs?: boolean;
}): Record<string, string> => {
  const random = createRandom(`package:${name}@${version}`);
  const files: Record<string, string> = {};
  const moduleNames = Array.from({ length: modules }, (_, index) => `lib/part-${index}.${commonJs ? 'cjs' : 'js'}`);
  for (const [index, modulePath] of moduleNames.entries()) {
    const names = generateFunctionNames(random, `p${index}`, functionsPerModule);
    const body = names.map((functionName) => generateFunction(random, functionName, false)).join('\n');
    files[modulePath] = commonJs
      ? `'use strict';\n${body.replaceAll('export function ', 'function ')}\nmodule.exports = { ${names.join(', ')} };\n`
      : body;
  }
  files['package.json'] = `${JSON.stringify(
    commonJs
      ? { name, version, main: 'index.cjs', license: 'MIT' }
      : { name, version, type: 'module', main: 'index.js', exports: { '.': './index.js' }, license: 'MIT' },
    null,
    2
  )}\n`;
  files[commonJs ? 'index.cjs' : 'index.js'] = commonJs
    ? `'use strict';
const registry = Object.assign({}, ${moduleNames.map((modulePath) => `require('./${modulePath}')`).join(', ')});
const run = (operation, input, options) => {
  const handler = registry[operation];
  if (!handler) throw new Error('Unknown operation ' + operation);
  return handler(input, options);
};
module.exports = { run, names: Object.keys(registry), version: '${version}' };
`
    : `${moduleNames.map((modulePath, index) => `import * as part${index} from './${modulePath}';`).join('\n')}
const registry = { ${moduleNames.map((_, index) => `...part${index}`).join(', ')} };
export const names = Object.keys(registry);
export const run = (operation, input, options) => {
  const handler = registry[operation];
  if (!handler) throw new Error(\`Unknown operation \${operation}\`);
  return handler(input, options);
};
export default { run, names, version: '${version}' };
`;
  return Object.fromEntries(
    Object.entries(files).map(([path, content]) => [join('node_modules', name, path), content])
  );
};

type VendoredPackage = {
  name: string;
  version: string;
  modules: number;
  functionsPerModule: number;
  commonJs?: boolean;
};

const VENDORED_PACKAGES: VendoredPackage[] = [
  { name: '@perf-fixture/validation', version: '2.4.1', modules: 6, functionsPerModule: 30 },
  { name: '@perf-fixture/dates', version: '1.9.0', modules: 3, functionsPerModule: 24 },
  { name: 'perf-fixture-logger', version: '3.1.2', modules: 2, functionsPerModule: 22, commonJs: true },
  { name: 'perf-fixture-ids', version: '0.8.3', modules: 1, functionsPerModule: 10 },
  { name: '@perf-fixture/money', version: '5.0.4', modules: 3, functionsPerModule: 20 },
  { name: '@perf-fixture/documents', version: '1.2.0', modules: 8, functionsPerModule: 30 }
];

/** Installed by the manifest edit: declared and present, but not imported yet. */
const MANIFEST_EDIT_PACKAGE: VendoredPackage = {
  name: '@perf-fixture/search',
  version: '0.3.0',
  modules: 1,
  functionsPerModule: 12
};

/** The core library every handler imports; each module wraps one vendored package. */
const LIBRARY_MODULES = [
  { file: 'logger', binding: 'logger', import: "import logger from 'perf-fixture-logger';" },
  { file: 'validation', binding: 'validation', import: "import validation from '@perf-fixture/validation';" },
  { file: 'time', binding: 'dates', import: "import dates from '@perf-fixture/dates';" },
  { file: 'ids', binding: 'ids', import: "import ids from 'perf-fixture-ids';" }
] as const;

const FEATURE_MODULES = [
  { file: 'orders', import: '' },
  { file: 'billing', import: "import money from '@perf-fixture/money';" },
  { file: 'inventory', import: '' },
  { file: 'notifications', import: '' },
  {
    file: 'reports',
    import:
      "import documents from '@perf-fixture/documents';\nimport reportTemplatePath from '../assets/report-template.bin';"
  }
] as const;

const SHARED_REVISION_LINE = "export const SHARED_REVISION = 'fixture-base';";
const HANDLER_REVISION_LINE = "const HANDLER_REVISION = 'fixture-base';";
const ASSET_BYTES = 32 * 1024;

const pad = (value: number) => String(value).padStart(2, '0');
const handlerName = (index: number) => `handler${pad(index)}`;

const generateAsset = (seed: string): Buffer => {
  const random = createRandom(seed);
  return Buffer.from(Array.from({ length: ASSET_BYTES }, () => Math.floor(random() * 256)));
};

/**
 * Generated functions plus a registry that references them. The exported entry uses the registry, so the bundler keeps
 * every function, as it would keep the reachable code of a real module.
 */
const generateSourceModule = ({
  seed,
  prefix,
  functionCount,
  header,
  usage
}: {
  seed: string;
  prefix: string;
  functionCount: number;
  header: string;
  usage: string;
}) => {
  const random = createRandom(seed);
  const names = generateFunctionNames(random, prefix, functionCount);
  return `${header}

${names.map((name) => generateFunction(random, name, true)).join('\n')}
const operations: Record<string, (input: Record<string, any>) => unknown> = { ${names.join(', ')} };

${usage}
`;
};

const generateProjectFiles = (functionCount: number): Record<string, string | Buffer> => {
  const files: Record<string, string | Buffer> = {};
  for (const module of LIBRARY_MODULES) {
    files[`src/lib/${module.file}.ts`] = generateSourceModule({
      seed: `lib:${module.file}`,
      prefix: module.file,
      functionCount: 14,
      header: module.import,
      usage: `export const use${capitalize(module.file)} = (input: Record<string, any>) => ({
  result: ${module.binding}.run(${module.binding}.names[0], input),
  operations: Object.keys(operations)
});`
    });
  }
  files['src/lib/responses.ts'] = generateSourceModule({
    seed: 'lib:responses',
    prefix: 'responses',
    functionCount: 14,
    header: '',
    usage: `${SHARED_REVISION_LINE}
export const jsonResponse = (statusCode: number, body: unknown) => ({
  statusCode,
  headers: { 'content-type': 'application/json', 'x-fixture-revision': SHARED_REVISION },
  body: JSON.stringify({ body, operations: Object.keys(operations) })
});`
  });
  for (const feature of FEATURE_MODULES) {
    const dependencyUse =
      feature.file === 'billing'
        ? 'money.run(money.names[1], input)'
        : feature.file === 'reports'
          ? '{ template: reportTemplatePath, rendered: documents.run(documents.names[2], input) }'
          : `'${feature.file}'`;
    files[`src/features/${feature.file}.ts`] = generateSourceModule({
      seed: `feature:${feature.file}`,
      prefix: feature.file,
      functionCount: 18,
      header: feature.import,
      usage: `export const run${capitalize(feature.file)} = (input: Record<string, any>) => ({
  result: ${dependencyUse},
  operations: Object.keys(operations)
});`
    });
  }
  files['src/assets/report-template.bin'] = generateAsset('asset:report-template');
  files['src/types/assets.d.ts'] = "declare module '*.bin' {\n  const path: string;\n  export default path;\n}\n";

  for (let index = 1; index <= functionCount; index++) {
    // The first handler uses the reports feature, so even a one-function fixture carries the asset and its largest
    // dependency. Every third handler also uses a second feature, so feature modules are shared by different subsets.
    const features = [FEATURE_MODULES[(index + 3) % FEATURE_MODULES.length]!.file];
    if (index % 3 === 0) features.push(FEATURE_MODULES[(index + 1) % FEATURE_MODULES.length]!.file);
    const imports = [
      "import { DynamoDBClient } from '@aws-sdk/client-dynamodb';",
      "import { useLogger } from '../lib/logger';",
      "import { jsonResponse } from '../lib/responses';",
      "import { useIds } from '../lib/ids';",
      "import { useTime } from '../lib/time';",
      "import { useValidation } from '../lib/validation';",
      ...features.map((feature) => `import { run${capitalize(feature)} } from '../features/${feature}';`)
    ].join('\n');
    const usage = `${HANDLER_REVISION_LINE}
const client = new DynamoDBClient({});

export const handler = async (event: { body?: string | null }) => {
  const input = JSON.parse(event.body ?? '{}');
  return jsonResponse(200, {
    handler: '${handlerName(index)}',
    revision: HANDLER_REVISION,
    region: typeof client.config.region === 'string' ? client.config.region : 'runtime',
    logged: useLogger(input),
    id: useIds(input),
    time: useTime(input),
    valid: useValidation(input),
    features: [${features.map((feature) => `run${capitalize(feature)}(input)`).join(', ')}],
    operations: Object.keys(operations)
  });
};`;
    files[`src/handlers/handler-${pad(index)}.ts`] = generateSourceModule({
      seed: `handler:${index}`,
      prefix: `h${index}`,
      functionCount: 5,
      header: imports,
      usage
    });
  }

  files['src/server.ts'] = `import { createServer } from 'node:http';
${FEATURE_MODULES.map((feature) => `import { run${capitalize(feature.file)} } from './features/${feature.file}';`).join('\n')}
import { jsonResponse } from './lib/responses';
import { useValidation } from './lib/validation';

const routes: Record<string, (input: Record<string, any>) => unknown> = {
${FEATURE_MODULES.map((feature) => `  '/${feature.file}': run${capitalize(feature.file)}`).join(',\n')}
};

createServer((request, response) => {
  const route = routes[request.url ?? ''];
  const result = route ? jsonResponse(200, { result: route({}), valid: useValidation({}) }) : jsonResponse(404, {});
  response.writeHead(result.statusCode, result.headers).end(result.body);
}).listen(Number(process.env.PORT ?? 3000));
`;
  return files;
};

const packageJson = (dependencies: Record<string, string>) =>
  `${JSON.stringify(
    {
      name: 'stacktape-packaging-perf-fixture',
      version: '1.0.0',
      private: true,
      type: 'module',
      // The harness keeps fixtures inside the ignored `.stacktape` directory of a Stacktape checkout. Stacktape's
      // project-root discovery stops at the nearest workspace root, which would otherwise be that checkout. An empty
      // workspace list makes the fixture its own root: the same directory a standalone project resolves to.
      workspaces: [],
      dependencies
    },
    null,
    2
  )}\n`;

const packageLock = (dependencies: Record<string, string>) =>
  `${JSON.stringify(
    {
      name: 'stacktape-packaging-perf-fixture',
      version: '1.0.0',
      lockfileVersion: 3,
      requires: true,
      packages: {
        '': { name: 'stacktape-packaging-perf-fixture', version: '1.0.0', dependencies },
        ...Object.fromEntries(
          Object.entries(dependencies).map(([name, version]) => [`node_modules/${name}`, { version, license: 'MIT' }])
        )
      }
    },
    null,
    2
  )}\n`;

const TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2023',
      module: 'ESNext',
      moduleResolution: 'bundler',
      strict: true,
      skipLibCheck: true,
      noEmit: true
    },
    include: ['src']
  },
  null,
  2
)}\n`;

const dependencyVersions = (packages: VendoredPackage[]) =>
  Object.fromEntries(
    packages.map(({ name, version }) => [name, version]).toSorted(([left], [right]) => (left! < right! ? -1 : 1))
  );

const writeFiles = async (root: string, files: Record<string, string | Buffer>) => {
  for (const [path, content] of Object.entries(files)) {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), content);
  }
};

/** Writes a complete fixture project into an empty or absent directory. */
export const writePackagingFixture = async ({
  root,
  functions
}: {
  root: string;
  functions: number;
}): Promise<FixtureManifest> => {
  if (!Number.isInteger(functions) || functions < 1) {
    throw new Error(`A fixture needs at least one function; received ${functions}.`);
  }
  await rm(root, { recursive: true, force: true });
  const dependencies = dependencyVersions(VENDORED_PACKAGES);
  await writeFiles(root, {
    ...generateProjectFiles(functions),
    ...Object.assign({}, ...VENDORED_PACKAGES.map((vendored) => generatePackage(vendored))),
    'package.json': packageJson(dependencies),
    'package-lock.json': packageLock(dependencies),
    'tsconfig.json': TSCONFIG
  });
  return {
    generatorVersion: FIXTURE_GENERATOR_VERSION,
    functions: Array.from({ length: functions }, (_, offset) => ({
      name: handlerName(offset + 1),
      entryfilePath: `src/handlers/handler-${pad(offset + 1)}.ts`
    })),
    dependencies,
    containerEntryfilePath: 'src/server.ts'
  };
};

const replaceOnce = (content: string, search: string, replacement: string, path: string) => {
  if (!content.includes(search)) throw new Error(`Fixture file ${path} does not contain the edit marker.`);
  return content.replace(search, replacement);
};

/**
 * Applies one of the representative edits and returns how to undo it. Every edit is a change a developer makes:
 * one handler's code, the library every handler imports, a newly installed dependency, or a binary asset.
 */
export const applyFixtureEdit = async ({
  root,
  edit
}: {
  root: string;
  edit: FixtureEdit;
}): Promise<{ description: string; revert: () => Promise<void> }> => {
  const originals = new Map<string, Buffer>();
  const created: string[] = [];
  const rewrite = async (path: string, change: (content: Buffer) => string | Buffer) => {
    const absolutePath = join(root, path);
    const original = await readFile(absolutePath);
    originals.set(absolutePath, original);
    await writeFile(absolutePath, change(original));
  };
  let description: string;
  switch (edit) {
    case 'handler':
      description = 'Changed a string constant in src/handlers/handler-01.ts.';
      await rewrite('src/handlers/handler-01.ts', (content) =>
        replaceOnce(
          content.toString(),
          HANDLER_REVISION_LINE,
          HANDLER_REVISION_LINE.replace('base', 'edited'),
          'handler-01'
        )
      );
      break;
    case 'shared':
      description = 'Changed a string constant in src/lib/responses.ts, which every handler imports.';
      await rewrite('src/lib/responses.ts', (content) =>
        replaceOnce(
          content.toString(),
          SHARED_REVISION_LINE,
          SHARED_REVISION_LINE.replace('base', 'edited'),
          'responses'
        )
      );
      break;
    case 'manifest': {
      description = `Installed ${MANIFEST_EDIT_PACKAGE.name}@${MANIFEST_EDIT_PACKAGE.version}: package.json, package-lock.json and node_modules change; no source imports it yet.`;
      const dependencies = dependencyVersions([...VENDORED_PACKAGES, MANIFEST_EDIT_PACKAGE]);
      await rewrite('package.json', () => packageJson(dependencies));
      await rewrite('package-lock.json', () => packageLock(dependencies));
      created.push(join(root, 'node_modules', MANIFEST_EDIT_PACKAGE.name));
      await writeFiles(root, generatePackage(MANIFEST_EDIT_PACKAGE));
      break;
    }
    case 'asset':
      description = 'Replaced the bytes of src/assets/report-template.bin, which one feature module imports.';
      await rewrite('src/assets/report-template.bin', () => generateAsset('asset:report-template:edited'));
      break;
    default:
      throw new Error(`Unknown fixture edit ${edit satisfies never}.`);
  }
  return {
    description,
    revert: async () => {
      for (const [path, content] of originals) await writeFile(path, content);
      for (const path of created) await rm(path, { recursive: true, force: true });
    }
  };
};

/** Edits that change only the Stacktape configuration. Only the full-CLI harness writes and reads that file. */
export const CONFIG_EDITS = ['config'] as const;
export type ConfigEdit = (typeof CONFIG_EDITS)[number];

export const FIXTURE_CONFIG_FILE = 'stacktape.yml';
const CONFIG_REVISION_VALUE = 'fixture-base';

/**
 * Every function packaged with the Stacktape Lambda buildpack. YAML, because a TypeScript configuration imports the
 * `stacktape` package from the project, and the fixture vendors only its own generated packages.
 */
const stacktapeConfig = ({ functions, revision }: { functions: FixtureFunction[]; revision: string }) =>
  [
    '# Generated by the Stacktape CLI measurement harness.',
    'resources:',
    ...functions.flatMap(({ name, entryfilePath }) => [
      `  ${name}:`,
      '    type: function',
      '    properties:',
      '      packaging:',
      '        type: stacktape-lambda-buildpack',
      '        properties:',
      `          entryfilePath: ${entryfilePath}`,
      '      memory: 512',
      '      timeout: 10',
      '      environment:',
      '        - name: CONFIG_REVISION',
      `          value: ${revision}`
    ]),
    ''
  ].join('\n');

/** Writes the configuration the full-CLI harness packages the fixture with. */
export const writeFixtureConfig = async ({ root, functions }: { root: string; functions: FixtureFunction[] }) => {
  await writeFile(join(root, FIXTURE_CONFIG_FILE), stacktapeConfig({ functions, revision: CONFIG_REVISION_VALUE }));
};

/**
 * Changes one function's environment variable value in the configuration and returns how to undo it. No source,
 * manifest or asset changes, so the packages built from it are the same; what changes is deployment configuration.
 */
export const applyConfigEdit = async ({
  root
}: {
  root: string;
}): Promise<{ description: string; revert: () => Promise<void> }> => {
  const path = join(root, FIXTURE_CONFIG_FILE);
  const original = await readFile(path);
  await writeFile(
    path,
    replaceOnce(original.toString(), `value: ${CONFIG_REVISION_VALUE}`, 'value: fixture-edited', FIXTURE_CONFIG_FILE)
  );
  return {
    description: `Changed the value of the first function's CONFIG_REVISION environment variable in ${FIXTURE_CONFIG_FILE}.`,
    revert: async () => {
      await writeFile(path, original);
    }
  };
};

/**
 * Content identity of the fixture's source tree, excluding Stacktape's own `.stacktape` output and any `exclude` path,
 * relative to the root.
 */
export const getFixtureIdentity = async (
  root: string,
  { exclude = [] }: { exclude?: string[] } = {}
): Promise<FixtureIdentity> => {
  const files: string[] = [];
  const walk = async (directory: string) => {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (entry.name === '.stacktape') continue;
      const path = join(directory, entry.name);
      if (exclude.includes(relative(root, path).split('\\').join('/'))) continue;
      if (entry.isDirectory()) await walk(path);
      else files.push(path);
    }
  };
  await walk(root);
  const hash = createHash('sha256');
  let bytes = 0;
  for (const path of files.map((file) => relative(root, file).split('\\').join('/')).toSorted()) {
    const content = await readFile(join(root, path));
    bytes += content.length;
    hash.update(`${path}\0${content.length}\0`);
    hash.update(content);
  }
  return { contentSha256: hash.digest('hex'), files: files.length, bytes };
};
