// This file is auto-generated. Do not edit manually.
// Source: aws-apigatewayv2-route.json

/** The ``AWS::ApiGatewayV2::Route`` resource creates a route for an API. */
export type AwsApigatewayv2Route = {
  RouteId?: string;
  /** The route response selection expression for the route. Supported only for WebSocket APIs. */
  RouteResponseSelectionExpression?: string;
  /** The request models for the route. Supported only for WebSocket APIs. */
  RequestModels?: Record<string, unknown>;
  /** The operation name for the route. */
  OperationName?: string;
  /**
   * The authorization scopes supported by this route.
   * @uniqueItems false
   */
  AuthorizationScopes?: string[];
  /** Specifies whether an API key is required for the route. Supported only for WebSocket APIs. */
  ApiKeyRequired?: boolean;
  /**
   * The route key for the route. For HTTP APIs, the route key can be either ``$default``, or a
   * combination of an HTTP method and resource path, for example, ``GET /pets``.
   */
  RouteKey: string;
  /**
   * The authorization type for the route. For WebSocket APIs, valid values are ``NONE`` for open
   * access, ``AWS_IAM`` for using AWS IAM permissions, and ``CUSTOM`` for using a Lambda authorizer.
   * For HTTP APIs, valid values are ``NONE`` for open access, ``JWT`` for using JSON Web Tokens,
   * ``AWS_IAM`` for using AWS IAM permissions, and ``CUSTOM`` for using a Lambda authorizer.
   */
  AuthorizationType?: string;
  /** The model selection expression for the route. Supported only for WebSocket APIs. */
  ModelSelectionExpression?: string;
  /** The API identifier. */
  ApiId: string;
  /** The request parameters for the route. Supported only for WebSocket APIs. */
  RequestParameters?: Record<string, unknown>;
  /** The target for the route. */
  Target?: string;
  /**
   * The identifier of the ``Authorizer`` resource to be associated with this route. The authorizer
   * identifier is generated by API Gateway when you created the authorizer.
   */
  AuthorizerId?: string;
};
