// This file is auto-generated. Do not edit manually.
// Source: aws-apigatewayv2-routingrule.json

/** Schema for AWS::ApiGatewayV2::RoutingRule */
export type AwsApigatewayv2Routingrule = {
  /** RoutingRule Id generated by service */
  RoutingRuleId?: string;
  /** Amazon Resource Name (ARN) of the resource. */
  RoutingRuleArn?: string;
  /** The amazon resource name (ARN) of the domain name resource. */
  DomainNameArn: string;
  Priority: number;
  Conditions: {
    MatchHeaders?: {
      AnyOf: {
        Header: string;
        ValueGlob: string;
      }[];
    };
    MatchBasePaths?: {
      AnyOf: string[];
    };
  }[];
  Actions: {
    InvokeApi: {
      ApiId: string;
      Stage: string;
      StripBasePath?: boolean;
    };
  }[];
};
