// This file is auto-generated. Do not edit manually.
// Source: aws-appsync-api.json

/** Resource schema for AppSync Api */
export type AwsAppsyncApi = {
  /** The unique identifier for the AppSync Api generated by the service */
  ApiId?: string;
  /** The Amazon Resource Name (ARN) of the AppSync Api */
  ApiArn?: string;
  Name: string;
  OwnerContact?: string;
  Dns?: {
    Realtime?: string;
    Http?: string;
  };
  EventConfig?: {
    AuthProviders: ({
      AuthType: "AMAZON_COGNITO_USER_POOLS" | "AWS_IAM" | "API_KEY" | "OPENID_CONNECT" | "AWS_LAMBDA";
      OpenIDConnectConfig?: {
        ClientId?: string;
        AuthTTL?: number;
        Issuer: string;
        IatTTL?: number;
      };
      CognitoConfig?: {
        AppIdClientRegex?: string;
        UserPoolId: string;
        AwsRegion: string;
      };
      LambdaAuthorizerConfig?: {
        /**
         * @minimum 0
         * @maximum 3600
         */
        AuthorizerResultTtlInSeconds?: number;
        AuthorizerUri: string;
        IdentityValidationExpression?: string;
      };
    })[];
    ConnectionAuthModes: ({
      AuthType?: "AMAZON_COGNITO_USER_POOLS" | "AWS_IAM" | "API_KEY" | "OPENID_CONNECT" | "AWS_LAMBDA";
    })[];
    DefaultPublishAuthModes: ({
      AuthType?: "AMAZON_COGNITO_USER_POOLS" | "AWS_IAM" | "API_KEY" | "OPENID_CONNECT" | "AWS_LAMBDA";
    })[];
    DefaultSubscribeAuthModes: ({
      AuthType?: "AMAZON_COGNITO_USER_POOLS" | "AWS_IAM" | "API_KEY" | "OPENID_CONNECT" | "AWS_LAMBDA";
    })[];
    LogConfig?: {
      LogLevel: "NONE" | "ERROR" | "ALL" | "INFO" | "DEBUG";
      CloudWatchLogsRoleArn: string;
    };
  };
  Tags?: {
    /**
     * A string used to identify this tag. You can specify a maximum of 128 characters for a tag key.
     * @minLength 1
     * @maxLength 128
     * @pattern ^(?!aws:)[ a-zA-Z+-=._:/]+$
     */
    Key: string;
    /**
     * A string containing the value for this tag. You can specify a maximum of 256 characters for a tag
     * value.
     * @minLength 0
     * @maxLength 256
     * @pattern ^[\s\w+-=\.:/@]*$
     */
    Value: string;
  }[];
};
