// This file is auto-generated. Do not edit manually.
// Source: aws-ec2-vpcendpointconnectionnotification.json

/** Resource Type definition for AWS::EC2::VPCEndpointConnectionNotification */
export type AwsEc2Vpcendpointconnectionnotification = {
  /**
   * The endpoint events for which to receive notifications.
   * @uniqueItems false
   */
  ConnectionEvents: string[];
  /** The ID of the endpoint. */
  VPCEndpointId?: string;
  /** VPC Endpoint Connection ID generated by service */
  VPCEndpointConnectionNotificationId?: string;
  /** The ARN of the SNS topic for the notifications. */
  ConnectionNotificationArn: string;
  /** The ID of the endpoint service. */
  ServiceId?: string;
};
