// This file is auto-generated. Do not edit manually.
// Source: aws-emr-step.json

/** Schema for AWS::EMR::Step */
export type AwsEmrStep = {
  /** ID generated by service */
  Id?: string;
  /**
   * This specifies what action to take when the cluster step fails. Possible values are CANCEL_AND_WAIT
   * and CONTINUE.
   */
  ActionOnFailure: string;
  /**
   * The HadoopJarStepConfig property type specifies a job flow step consisting of a JAR file whose main
   * function will be executed. The main function submits a job for the cluster to execute as a step on
   * the master node, and then waits for the job to finish or fail before executing subsequent steps.
   */
  HadoopJarStep: {
    /** @uniqueItems false */
    Args?: string[];
    Jar: string;
    MainClass?: string;
    /** @uniqueItems true */
    StepProperties?: {
      Key?: string;
      Value?: string;
    }[];
  };
  /** A string that uniquely identifies the cluster (job flow). */
  JobFlowId: string;
  /** The name of the cluster step. */
  Name: string;
};
