// This file is auto-generated. Do not edit manually.
// Source: aws-lambda-alias.json

/** Resource Type definition for AWS::Lambda::Alias */
export type AwsLambdaAlias = {
  /** The name of the Lambda function. */
  FunctionName: string;
  /** Lambda Alias ARN generated by the service. */
  AliasArn?: string;
  /** Specifies a provisioned concurrency configuration for a function's alias. */
  ProvisionedConcurrencyConfig?: {
    /** The amount of provisioned concurrency to allocate for the alias. */
    ProvisionedConcurrentExecutions: number;
  };
  /** A description of the alias. */
  Description?: string;
  /** The function version that the alias invokes. */
  FunctionVersion: string;
  /** The routing configuration of the alias. */
  RoutingConfig?: {
    /**
     * The second version, and the percentage of traffic that's routed to it.
     * @uniqueItems true
     */
    AdditionalVersionWeights?: {
      /** The percentage of traffic that the alias routes to the second version. */
      FunctionWeight: number;
      /** The qualifier of the second version. */
      FunctionVersion: string;
    }[];
  };
  /** The name of the alias. */
  Name: string;
};
