// This file is auto-generated. Do not edit manually.
// Source: aws-neptunegraph-privategraphendpoint.json

/**
 * The AWS::NeptuneGraph::PrivateGraphEndpoint resource creates an Amazon NeptuneGraph
 * PrivateGraphEndpoint.
 */
export type AwsNeptunegraphPrivategraphendpoint = {
  /** The auto-generated Graph Id assigned by the service. */
  GraphIdentifier: string;
  /**
   * The security group Ids associated with the VPC where you want the private graph endpoint to be
   * created, ie, the graph will be reachable from within the VPC.
   */
  SecurityGroupIds?: string[];
  /**
   * The subnet Ids associated with the VPC where you want the private graph endpoint to be created, ie,
   * the graph will be reachable from within the VPC.
   */
  SubnetIds?: string[];
  /**
   * The VPC where you want the private graph endpoint to be created, ie, the graph will be reachable
   * from within the VPC.
   */
  VpcId: string;
  /**
   * PrivateGraphEndpoint resource identifier generated by concatenating the associated GraphIdentifier
   * and VpcId with an underscore separator.
   * For example, if GraphIdentifier is `g-12a3bcdef4` and VpcId is `vpc-0a12bc34567de8f90`, the
   * generated PrivateGraphEndpointIdentifier will be `g-12a3bcdef4_vpc-0a12bc34567de8f90`
   */
  PrivateGraphEndpointIdentifier?: string;
  /** VPC endpoint that provides a private connection between the Graph and specified VPC. */
  VpcEndpointId?: string;
};
