import { loadAwsServiceSpecSync } from '@aws-cdk/aws-service-spec';
import type { Property, PropertyType, Resource, SpecDatabase, TypeDefinition } from '@aws-cdk/service-spec-types';
import { createRequire } from 'node:module';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const AWS_SERVICE_SPEC_VERSION = '0.1.199';
const SERVICE_SPEC_TYPES_VERSION = '0.0.265';
const GENERATED_DIRECTORY = fileURLToPath(new URL('../generated', import.meta.url));
const GENERATED_HEADER = `// Generated by packages/cloudformation/scripts/generate.ts from @aws-cdk/aws-service-spec@${AWS_SERVICE_SPEC_VERSION}.
// Do not edit this file directly.

`;

type GeneratedArtifacts = ReadonlyMap<string, string>;

type ResourceDefinitionNames = ReadonlyMap<string, string>;

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function assertPinnedDependencyVersion(packageName: string, expectedVersion: string): void {
  const require = createRequire(import.meta.url);
  const manifestPath = require.resolve(`${packageName}/package.json`);
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as { version?: unknown };
  if (manifest.version !== expectedVersion) {
    throw new Error(
      `Expected ${packageName}@${expectedVersion}, but generation resolved ${String(manifest.version)}. Update the generator and its tests deliberately before changing the pinned source.`
    );
  }
}

export function resourceModuleName(cloudFormationType: string): string {
  return cloudFormationType.replaceAll('::', '-').toLowerCase();
}

function typeIdentifier(name: string): string {
  const sanitized = name.replaceAll(/[^A-Za-z0-9_$]/g, '_');
  return /^[A-Za-z_$]/.test(sanitized) ? sanitized : `_${sanitized}`;
}

function resourcePropertiesTypeName(resource: Resource): string {
  return `${typeIdentifier(resource.name)}Properties`;
}

function resourceMapAlias(cloudFormationType: string): string {
  return `${cloudFormationType
    .split('::')
    .map((part) => {
      const normalized = typeIdentifier(part);
      return `${normalized[0]!.toUpperCase()}${normalized.slice(1)}`;
    })
    .join('')}Properties`;
}

function writableDefinitions(resource: Resource, database: SpecDatabase): TypeDefinition[] {
  const definitions = new Map<string, TypeDefinition>();

  const visit = (type: PropertyType): void => {
    switch (type.type) {
      case 'ref': {
        const definition = database.get('typeDefinition', type.reference);
        if (definitions.has(definition.$id)) return;
        definitions.set(definition.$id, definition);
        for (const property of Object.values(definition.properties)) visit(property.type);
        return;
      }
      case 'array':
      case 'map':
        visit(type.element);
        return;
      case 'union':
        for (const member of type.types) visit(member);
        return;
      default:
        return;
    }
  };

  for (const property of Object.values(resource.properties)) visit(property.type);
  return [...definitions.values()];
}

function buildDefinitionNames(resource: Resource, definitions: readonly TypeDefinition[]): ResourceDefinitionNames {
  const topLevelName = resourcePropertiesTypeName(resource);
  const occupiedNames = new Set([
    topLevelName,
    'Array',
    'Record',
    'CloudFormationJson',
    'CloudFormationTag',
    'CloudFormationValue'
  ]);
  const result = new Map<string, string>();

  for (const definition of definitions.toSorted((left, right) => compareText(left.name, right.name))) {
    const baseName = typeIdentifier(definition.name);
    let exportName = baseName;
    if (occupiedNames.has(exportName)) exportName = `${baseName}Definition`;
    let suffix = 2;
    while (occupiedNames.has(exportName)) {
      exportName = `${baseName}Definition${suffix}`;
      suffix += 1;
    }
    occupiedNames.add(exportName);
    result.set(definition.$id, exportName);
  }

  return result;
}

function renderAllowedValues(values: readonly (number | string)[]): string {
  return values.map((value) => JSON.stringify(value)).join(' | ');
}

function renderRawType(type: PropertyType, database: SpecDatabase, definitionNames: ResourceDefinitionNames): string {
  switch (type.type) {
    case 'string':
      return type.allowedValues?.length ? renderAllowedValues(type.allowedValues) : 'string';
    case 'number':
      return 'number';
    case 'integer':
      return type.allowedValues?.length ? renderAllowedValues(type.allowedValues) : 'number';
    case 'boolean':
      return 'boolean';
    case 'date-time':
      return 'string';
    case 'json':
      return 'CloudFormationJson';
    case 'null':
      return 'null';
    case 'tag':
      return 'CloudFormationTag';
    case 'ref': {
      const definition = database.get('typeDefinition', type.reference);
      const exportName = definitionNames.get(definition.$id);
      if (!exportName) {
        throw new Error(`The service specification references definition ${definition.name} outside this resource.`);
      }
      return exportName;
    }
    case 'array':
      return `Array<CloudFormationValue<${renderRawType(type.element, database, definitionNames)}>>`;
    case 'map':
      return `Record<string, CloudFormationValue<${renderRawType(type.element, database, definitionNames)}>>`;
    case 'union':
      return type.types.map((member) => renderRawType(member, database, definitionNames)).join(' | ');
  }
}

function renderPropertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function renderProperties(
  properties: Readonly<Record<string, Property>>,
  database: SpecDatabase,
  definitionNames: ResourceDefinitionNames
): string {
  const entries = Object.entries(properties).toSorted(([left], [right]) => compareText(left, right));
  if (entries.length === 0) return 'Record<string, never>';

  const lines = entries.flatMap(([name, property]) => {
    const result: string[] = [];
    if (property.deprecated === 'WARN') result.push('  /** @deprecated */');
    const optional = property.required ? '' : '?';
    const rawType = renderRawType(property.type, database, definitionNames);
    result.push(`  ${renderPropertyName(name)}${optional}: CloudFormationValue<${rawType}>;`);
    return result;
  });
  return `{
${lines.join('\n')}
}`;
}

export function buildResourceModule(
  resource: Resource,
  definitions: readonly TypeDefinition[],
  database: SpecDatabase
): string {
  const definitionNames = buildDefinitionNames(resource, definitions);
  const sections = [
    `export type ${resourcePropertiesTypeName(resource)} = ${renderProperties(resource.properties, database, definitionNames)};`
  ];

  for (const definition of definitions.toSorted((left, right) => {
    return compareText(definitionNames.get(left.$id)!, definitionNames.get(right.$id)!);
  })) {
    sections.push(
      `export type ${definitionNames.get(definition.$id)!} = ${renderProperties(
        definition.properties,
        database,
        definitionNames
      )};`
    );
  }

  const body = sections.join('\n\n');
  const intrinsicImports = ['CloudFormationJson', 'CloudFormationTag', 'CloudFormationValue'].filter((name) =>
    body.includes(name)
  );
  const importBlock = intrinsicImports.length
    ? `import type { ${intrinsicImports.join(', ')} } from '../../src/intrinsics';\n\n`
    : '';

  return `${GENERATED_HEADER}${importBlock}${body}\n`;
}

function buildResourceTypeMap(resources: readonly Resource[]): string {
  const imports: string[] = [];
  const properties: string[] = [];

  for (const resource of resources) {
    const resourcePropertiesName = resourcePropertiesTypeName(resource);
    const alias = resourceMapAlias(resource.cloudFormationType);
    imports.push(
      `import type { ${resourcePropertiesName} as ${alias} } from './resources/${resourceModuleName(resource.cloudFormationType)}';`
    );
    properties.push(`  '${resource.cloudFormationType}': ${alias};`);
  }

  return `${GENERATED_HEADER}${imports.join('\n')}

export type CloudFormationResourceProperties = {
${properties.join('\n')}
};

export type KnownCloudFormationResourceType = keyof CloudFormationResourceProperties;
`;
}

export function generateArtifacts(): GeneratedArtifacts {
  assertPinnedDependencyVersion('@aws-cdk/aws-service-spec', AWS_SERVICE_SPEC_VERSION);
  assertPinnedDependencyVersion('@aws-cdk/service-spec-types', SERVICE_SPEC_TYPES_VERSION);

  const database = loadAwsServiceSpecSync();
  const resources = database
    .all('resource')
    .toSorted((left, right) => compareText(left.cloudFormationType, right.cloudFormationType));
  const artifacts = new Map<string, string>();

  for (const resource of resources) {
    const fileName = resourceModuleName(resource.cloudFormationType);
    const relativePath = `resources/${fileName}.ts`;
    if (artifacts.has(relativePath)) {
      throw new Error(`Multiple CloudFormation resource types map to ${relativePath}.`);
    }
    artifacts.set(relativePath, buildResourceModule(resource, writableDefinitions(resource, database), database));
  }
  artifacts.set('resource-types.ts', buildResourceTypeMap(resources));

  return artifacts;
}

function listFiles(directory: string): string[] {
  if (!existsSync(directory)) return [];
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolutePath = join(directory, entry.name);
    return entry.isDirectory() ? listFiles(absolutePath) : [absolutePath];
  });
}

function checkArtifacts(artifacts: GeneratedArtifacts): boolean {
  const expectedPaths = new Set(artifacts.keys());
  const problems: string[] = [];

  for (const [relativePath, expectedContent] of artifacts) {
    const absolutePath = join(GENERATED_DIRECTORY, relativePath);
    if (!existsSync(absolutePath)) {
      problems.push(`missing ${relativePath}`);
    } else if (readFileSync(absolutePath, 'utf8') !== expectedContent) {
      problems.push(`outdated ${relativePath}`);
    }
  }

  for (const absolutePath of listFiles(GENERATED_DIRECTORY)) {
    const relativePath = relative(GENERATED_DIRECTORY, absolutePath).replaceAll('\\', '/');
    if (!expectedPaths.has(relativePath)) problems.push(`stale ${relativePath}`);
  }

  if (problems.length > 0) {
    console.error(`CloudFormation generated output is not current:\n${problems.join('\n')}`);
    return false;
  }
  return true;
}

export function writeArtifacts(artifacts: GeneratedArtifacts, directory = GENERATED_DIRECTORY): void {
  mkdirSync(directory, { recursive: true });
  const expectedPaths = new Set<string>();

  for (const [relativePath, content] of artifacts) {
    expectedPaths.add(relativePath);
    const absolutePath = join(directory, relativePath);
    mkdirSync(dirname(absolutePath), { recursive: true });
    if (!existsSync(absolutePath) || readFileSync(absolutePath, 'utf8') !== content) {
      writeFileSync(absolutePath, content, 'utf8');
    }
  }

  for (const absolutePath of listFiles(directory)) {
    const relativePath = relative(directory, absolutePath).replaceAll('\\', '/');
    if (!expectedPaths.has(relativePath)) rmSync(absolutePath);
  }
}

function isDirectInvocation(): boolean {
  return process.argv[1] !== undefined && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
}

if (isDirectInvocation()) {
  try {
    const artifacts = generateArtifacts();
    if (process.argv.includes('--check')) {
      if (!checkArtifacts(artifacts)) process.exitCode = 1;
    } else {
      writeArtifacts(artifacts);
      console.log(`Generated ${artifacts.size - 1} CloudFormation resource modules.`);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
