/**
 * Creating the secrets the composer invented, before the deploy that needs them.
 *
 * The composer writes `masterUserPassword: $Secret('mainDatabase.password')` for every database it
 * creates — a password nobody has ever typed, for a database that does not exist yet. Without this
 * step, the first deploy of every project with a database fails on secret resolution, asking the
 * user to invent and store a password for infrastructure they never asked to understand. That is
 * the exact opposite of what `init` promises.
 *
 * So: any secret the *composer generated* — recognisable as `<resource>.password`, the shape
 * `secretReference()` produces and nothing else in the pipeline does — is created here with a
 * strong random value if it does not already exist. It lives in the user's own Secrets Manager,
 * readable by them at any time, and an existing secret is never touched.
 *
 * Deliberately narrow: user-owned secrets — `database_url` for a database we are leaving alone,
 * `stripe_key` — are NOT created. Filling those with random bytes would turn "the deploy stopped
 * and told me to provide my key" into "the deploy succeeded and production cannot talk to Stripe".
 * Only values nobody possesses yet may be invented.
 */

import { randomBytes } from 'node:crypto';
import {
  CreateSecretCommand,
  GetSecretValueCommand,
  ResourceNotFoundException,
  SecretsManagerClient
} from '@aws-sdk/client-secrets-manager';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';
import { createFetchHandler } from 'src/aws/fetch-handler';

/** `$Secret('mainDatabase.password')`, and no other directive shape. */
const GENERATED_SECRET_PATTERN = /^\$Secret\('([^']+\.password)'\)$/;

/**
 * The composer-generated secret names a configuration references.
 *
 * Walks the resource properties rather than the rendered YAML, so it reads the same objects the
 * file is written from.
 */
export const generatedSecretNames = (resources: Record<string, { properties: Record<string, unknown> }>): string[] => {
  const names = new Set<string>();
  const walk = (value: unknown): void => {
    if (typeof value === 'string') {
      const match = GENERATED_SECRET_PATTERN.exec(value);
      if (match?.[1] !== undefined) names.add(match[1]);
      return;
    }
    if (Array.isArray(value)) {
      for (const entry of value) walk(entry);
      return;
    }
    if (value !== null && typeof value === 'object') {
      for (const entry of Object.values(value)) walk(entry);
    }
  };
  for (const resource of Object.values(resources)) walk(resource.properties);
  return [...names];
};

/**
 * A password RDS accepts for any engine.
 *
 * Alphanumeric only: RDS forbids `/`, `@`, `"` and spaces, and the exact forbidden set varies by
 * engine, so the safe alphabet is the boring one. 40 characters of it is ~238 bits.
 */
const generatePassword = (): string => {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const bytes = randomBytes(40);
  let password = '';
  for (const byte of bytes) password += alphabet[byte % alphabet.length];
  return password;
};

export type EnsuredSecret = { name: string; created: boolean };

/**
 * Make sure every generated secret exists, creating the missing ones with random values.
 *
 * Existing secrets are left exactly as they are — a user who set their own password keeps it, and a
 * retry after a failed deploy finds the secret from the first attempt rather than rotating it.
 */
export const ensureGeneratedSecrets = async ({
  names,
  region
}: {
  names: readonly string[];
  region: string;
}): Promise<EnsuredSecret[]> => {
  if (names.length === 0) return [];

  const client = new SecretsManagerClient({
    region,
    credentials: fromNodeProviderChain({ timeout: 8_000, maxRetries: 1 }),
    // Bun's `node:https` stalls against the AWS SDK; every client in this CLI uses fetch instead.
    requestHandler: createFetchHandler({ requestTimeout: 15_000 })
  });

  try {
    const results: EnsuredSecret[] = [];
    for (const name of names) {
      try {
        await client.send(new GetSecretValueCommand({ SecretId: name }));
        results.push({ name, created: false });
      } catch (error) {
        if (!(error instanceof ResourceNotFoundException)) throw error;
        await client.send(
          new CreateSecretCommand({
            Name: name,
            SecretString: generatePassword(),
            Description: 'Generated by stacktape init'
          })
        );
        results.push({ name, created: true });
      }
    }
    return results;
  } finally {
    client.destroy();
  }
};
