import { describe, expect, test } from 'bun:test';
import type { LambdaPackaging } from '@stacktape/config/deployment-artifacts';
import type { SplitBundlingCandidate } from './split-bundling-policy';
import { canBuildSplitNativeDependencies, selectSplitBundlingGroup } from './split-bundling-policy';

type StacktapeLambdaPackaging = Extract<LambdaPackaging, { type: 'stacktape-lambda-buildpack' }>;
type NamedCandidate = SplitBundlingCandidate & { name: string };

const candidate = (
  name: string,
  properties: Partial<StacktapeLambdaPackaging['properties']> = {},
  overrides: Omit<SplitBundlingCandidate, 'packaging'> = {}
): NamedCandidate => ({
  name,
  packaging: {
    type: 'stacktape-lambda-buildpack',
    properties: { entryfilePath: `./${name}.ts`, ...properties }
  },
  ...overrides
});

const names = (candidates: NamedCandidate[]) => candidates.map(({ name }) => name).toSorted();

describe('choosing which Lambdas share one build', () => {
  test('bundles two homogeneous default Lambdas together', () => {
    const { split, perFunction } = selectSplitBundlingGroup([candidate('api'), candidate('worker')]);
    expect(names(split)).toEqual(['api', 'worker']);
    expect(perFunction).toEqual([]);
  });

  test('a lone Lambda has nothing to share with', () => {
    const { split, perFunction } = selectSplitBundlingGroup([candidate('api')]);
    expect(split).toEqual([]);
    expect(names(perFunction)).toEqual(['api']);
  });

  test('one incompatible Lambda no longer costs the others their shared layer', () => {
    const { split, perFunction } = selectSplitBundlingGroup([
      candidate('api'),
      candidate('worker'),
      candidate('reports'),
      candidate('legacy', { languageSpecificConfig: { nodeVersion: 24, outputModuleFormat: 'cjs' } })
    ]);
    expect(names(split)).toEqual(['api', 'reports', 'worker']);
    expect(names(perFunction)).toEqual(['legacy']);
  });

  test('the larger compatible group is the one that shares a build', () => {
    const arm = { architecture: 'arm64' } as const;
    const { split, perFunction } = selectSplitBundlingGroup([
      candidate('armOne', {}, arm),
      candidate('armTwo', {}, arm),
      candidate('x86One'),
      candidate('x86Two'),
      candidate('x86Three')
    ]);
    expect(names(split)).toEqual(['x86One', 'x86Three', 'x86Two']);
    expect(names(perFunction)).toEqual(['armOne', 'armTwo']);
  });

  test('the same configuration always produces the same grouping', () => {
    const build = () =>
      selectSplitBundlingGroup([
        candidate('a', {}, { architecture: 'arm64' }),
        candidate('b', {}, { architecture: 'arm64' }),
        candidate('c'),
        candidate('d')
      ]);
    expect(names(build().split)).toEqual(names(build().split));
  });

  test.each([
    ['a named handler export, which only the CloudFormation handler string depends on', { handlerFunction: 'handle' }],
    ['dependencies excluded from the deployment package', { excludeDependencies: ['sharp'] }],
    ['Node 20', { languageSpecificConfig: { nodeVersion: 20 } }],
    ['Node 18', { languageSpecificConfig: { nodeVersion: 18 } }]
  ])('shares a build across two Lambdas that both use %s', (_description, properties) => {
    const shared = properties as Partial<StacktapeLambdaPackaging['properties']>;
    const { split } = selectSplitBundlingGroup([candidate('api', shared), candidate('worker', shared)]);
    expect(names(split)).toEqual(['api', 'worker']);
  });

  test('a traced function stays on the per-function path, which is the only one that wraps its handler', () => {
    // The OTel wrapper is generated by the per-Lambda buildpack. A split build bundles the entry file
    // directly, so a traced function packaged there would deploy with tracing silently absent.
    const { split, perFunction } = selectSplitBundlingGroup([
      candidate('api'),
      candidate('worker'),
      { ...candidate('traced'), tracingEnabled: true }
    ]);

    expect(names(split)).toEqual(['api', 'worker']);
    expect(names(perFunction)).toEqual(['traced']);
  });

  test('tracing every function leaves nothing to share', () => {
    const { split, perFunction } = selectSplitBundlingGroup([
      { ...candidate('api'), tracingEnabled: true },
      { ...candidate('worker'), tracingEnabled: true }
    ]);

    expect(split).toEqual([]);
    expect(names(perFunction)).toEqual(['api', 'worker']);
  });

  test.each([
    ['included files', { includeFiles: ['templates/**'] }],
    ['excluded files', { excludeFiles: ['**/*.test.ts'] }],
    ['decorator metadata', { languageSpecificConfig: { nodeVersion: 24, emitTsDecoratorMetadata: true } }],
    ['local source-map output', { languageSpecificConfig: { nodeVersion: 24, outputSourceMapsTo: './maps' } }],
    [
      'deployment-package dependency exclusions',
      { languageSpecificConfig: { nodeVersion: 24, dependenciesToExcludeFromDeploymentPackage: ['pg'] } }
    ],
    ['CommonJS output', { languageSpecificConfig: { nodeVersion: 24, outputModuleFormat: 'cjs' } }],
    ['an unsupported Node target', { languageSpecificConfig: { nodeVersion: 16 } }]
  ])('keeps a Lambda on the per-function path for %s', (_description, properties) => {
    const { split, perFunction } = selectSplitBundlingGroup([
      candidate('api'),
      candidate('worker'),
      candidate('odd', properties as Partial<StacktapeLambdaPackaging['properties']>)
    ]);
    expect(names(split)).toEqual(['api', 'worker']);
    expect(names(perFunction)).toEqual(['odd']);
  });

  test.each([
    ['architectures', [candidate('api'), candidate('worker', {}, { architecture: 'arm64' })]],
    [
      'tsconfig files',
      [
        candidate('api', { languageSpecificConfig: { nodeVersion: 24, tsConfigPath: './tsconfig.api.json' } }),
        candidate('worker', { languageSpecificConfig: { nodeVersion: 24, tsConfigPath: './tsconfig.worker.json' } })
      ]
    ],
    [
      'source-map settings',
      [
        candidate('api', { languageSpecificConfig: { nodeVersion: 24, disableSourceMaps: true } }),
        candidate('worker', { languageSpecificConfig: { nodeVersion: 24, disableSourceMaps: false } })
      ]
    ],
    [
      'minification',
      [
        candidate('api', { languageSpecificConfig: { nodeVersion: 24, minify: false } }),
        candidate('worker', { languageSpecificConfig: { nodeVersion: 24 } })
      ]
    ],
    [
      'identifier minification',
      [
        candidate('api', { languageSpecificConfig: { nodeVersion: 24, minifyIdentifiers: true } }),
        candidate('worker', { languageSpecificConfig: { nodeVersion: 24 } })
      ]
    ],
    [
      'AWS SDK bundling',
      [
        candidate('api', { languageSpecificConfig: { nodeVersion: 24, bundleAwsSdk: true } }),
        candidate('worker', { languageSpecificConfig: { nodeVersion: 24 } })
      ]
    ],
    [
      'Node versions',
      [
        candidate('api', { languageSpecificConfig: { nodeVersion: 24 } }),
        candidate('worker', { languageSpecificConfig: { nodeVersion: 20 } })
      ]
    ],
    [
      'excluded dependencies',
      [candidate('api', { excludeDependencies: ['sharp'] }), candidate('worker', { excludeDependencies: ['bcrypt'] })]
    ]
  ])('does not put two Lambdas with different %s in one build', (_description, candidates) => {
    const { split, perFunction } = selectSplitBundlingGroup(candidates);
    expect(split).toEqual([]);
    expect(names(perFunction)).toEqual(['api', 'worker']);
  });

  test.each([
    [
      'dependencies excluded from the bundle',
      (names: string[]) => ({ languageSpecificConfig: { nodeVersion: 24, dependenciesToExcludeFromBundle: names } })
    ],
    ['dependencies excluded from the deployment package', (names: string[]) => ({ excludeDependencies: names })]
  ])('shares a build when two Lambdas list the same %s in a different order', (_description, properties) => {
    const { split, perFunction } = selectSplitBundlingGroup([
      candidate('api', properties(['sharp', 'bcrypt'])),
      candidate('worker', properties(['bcrypt', 'sharp', 'bcrypt']))
    ]);
    expect(names(split)).toEqual(['api', 'worker']);
    expect(perFunction).toEqual([]);
  });

  test('reads the authored dependency lists without reordering them', () => {
    // Frozen, so sorting the authored array in place would throw instead of silently rewriting the user's config.
    const excludedFromBundle = Object.freeze(['sharp', 'bcrypt']) as string[];
    const excludedFromPackage = Object.freeze(['pg', 'aws-crt']) as string[];
    const properties = {
      excludeDependencies: excludedFromPackage,
      languageSpecificConfig: { nodeVersion: 24, dependenciesToExcludeFromBundle: excludedFromBundle }
    } as const;

    const { split } = selectSplitBundlingGroup([candidate('api', properties), candidate('worker', properties)]);

    expect(names(split)).toEqual(['api', 'worker']);
    expect(excludedFromBundle).toEqual(['sharp', 'bcrypt']);
    expect(excludedFromPackage).toEqual(['pg', 'aws-crt']);
  });

  test('breaks a tie between equally large groups by code-unit order, not the machine collation', () => {
    // Collation puts "api" before "Workers"; code units put "W" (0x57) before "a" (0x61). Code-unit order is the same
    // on every machine, so the same configuration always lifts the same functions into a shared layer.
    const workers = { languageSpecificConfig: { nodeVersion: 24, tsConfigPath: './config/Workers.json' } } as const;
    const api = { languageSpecificConfig: { nodeVersion: 24, tsConfigPath: './config/api.json' } } as const;
    const { split, perFunction } = selectSplitBundlingGroup([
      candidate('apiOne', api),
      candidate('apiTwo', api),
      candidate('workerOne', workers),
      candidate('workerTwo', workers)
    ]);
    expect(names(split)).toEqual(['workerOne', 'workerTwo']);
    expect(names(perFunction)).toEqual(['apiOne', 'apiTwo']);
  });

  test('allows identical supported ESM settings', () => {
    const properties: Partial<StacktapeLambdaPackaging['properties']> = {
      languageSpecificConfig: {
        nodeVersion: 24,
        outputModuleFormat: 'esm',
        tsConfigPath: './tsconfig.build.json',
        dependenciesToExcludeFromBundle: ['sharp']
      }
    };
    const { split } = selectSplitBundlingGroup([candidate('api', properties), candidate('worker', properties)]);
    expect(names(split)).toEqual(['api', 'worker']);
  });
});

describe('split bundling native dependency support', () => {
  test('requires Docker when native dependencies need materialization', () => {
    expect(canBuildSplitNativeDependencies({ dependencyCount: 1, dockerIsRunning: false })).toBe(false);
    expect(canBuildSplitNativeDependencies({ dependencyCount: 1, dockerIsRunning: true })).toBe(true);
  });

  test('does not require Docker when the split output has no native dependencies', () => {
    expect(canBuildSplitNativeDependencies({ dependencyCount: 0, dockerIsRunning: false })).toBe(true);
  });
});
