import { ensureDir, writeFile } from 'fs-extra';
import { dirname, resolve } from 'node:path';
import configSchema from '../../@generated/schemas/enhanced-config-schema.json';
import { buildApiReferenceData } from '../src/utils/build-api-reference-data';

const outputPath = resolve(import.meta.dir, '..', 'src', 'generated', 'api-reference-data.ts');

const generated = buildApiReferenceData(configSchema as { definitions: Record<string, unknown> });

const file = `/* eslint-disable */\n/* This file is generated by scripts/generate-api-reference-data.ts. Do not edit by hand. */\n\nimport type { NormalizedDefinition } from '@/utils/api-reference-extractor';\n\nexport type ApiReferenceGeneratedDefinition = NormalizedDefinition & {\n  stats: {\n    requiredCount: number;\n    optionalCount: number;\n  };\n  typeDeclaration: string;\n};\n\nexport const apiReferenceData = ${JSON.stringify(generated, null, 2)} satisfies Record<string, ApiReferenceGeneratedDefinition>;\n`;

await ensureDir(dirname(outputPath));
await writeFile(outputPath, file);

console.info(`Generated API reference data for ${Object.keys(generated).length} definitions at ${outputPath}`);
