import { ensureDir, writeFile } from 'fs-extra';
import { dirname, resolve } from 'node:path';
import configSchema from '../../@generated/schemas/enhanced-config-schema.json';
import {
  normalizeDefinition,
  type NormalizedDefinition,
  type NormalizedTypeInfo
} from '../src/utils/api-reference-extractor';
import { buildApiReferenceTypeDeclaration } from '../src/utils/api-reference-typescript';

type ApiReferenceGeneratedDefinition = NormalizedDefinition & {
  stats: {
    requiredCount: number;
    optionalCount: number;
  };
  typeDeclaration: string;
};

const definitions = (configSchema as { definitions: Record<string, unknown> }).definitions as Record<string, any>;

const outputPath = resolve(import.meta.dir, '..', 'src', 'generated', 'api-reference-data.ts');

const collectReferencedTypeNames = (typeInfo: NormalizedTypeInfo, result = new Set<string>()) => {
  if (typeInfo.kind === 'array') {
    collectReferencedTypeNames(typeInfo.itemType, result);
    return result;
  }
  if (typeInfo.kind === 'reference') {
    result.add(typeInfo.typeName);
    return result;
  }
  if (typeInfo.kind === 'union') {
    for (const branch of typeInfo.branches) {
      if (branch.typeName) result.add(branch.typeName);
      for (const property of branch.properties) {
        collectReferencedTypeNames(property.typeInfo, result);
      }
    }
  }
  return result;
};

const collectDefinitionReferences = (definition: NormalizedDefinition) => {
  const result = new Set<string>();
  for (const property of definition.properties) {
    collectReferencedTypeNames(property.typeInfo, result);
  }
  return result;
};

const buildGeneratedDefinition = (definition: NormalizedDefinition): ApiReferenceGeneratedDefinition => {
  const requiredCount = definition.properties.filter((property) => property.required).length;
  return {
    ...definition,
    stats: {
      requiredCount,
      optionalCount: definition.properties.length - requiredCount
    },
    typeDeclaration: buildApiReferenceTypeDeclaration(definition)
  };
};

const generated: Record<string, ApiReferenceGeneratedDefinition> = {};

for (const definitionName of Object.keys(definitions).sort()) {
  const definition = normalizeDefinition(definitionName, definitions);
  if (!definition || definition.properties.length === 0) continue;
  generated[definitionName] = buildGeneratedDefinition(definition);
}

const unresolvedReferences: string[] = [];
for (const definition of Object.values(generated)) {
  for (const referencedTypeName of collectDefinitionReferences(definition)) {
    if (!generated[referencedTypeName] && !definitions[referencedTypeName]) {
      unresolvedReferences.push(`${definition.definitionName} -> ${referencedTypeName}`);
    }
  }
}

if (unresolvedReferences.length > 0) {
  throw new Error(
    `API reference data has unresolved referenced types:\n${unresolvedReferences.slice(0, 50).join('\n')}`
  );
}

const file = `/* eslint-disable */\n/* This file is generated by scripts/generate-api-reference-data.ts. Do not edit by hand. */\n\nimport type { NormalizedDefinition } from '@/utils/api-reference-extractor';\n\nexport type ApiReferenceGeneratedDefinition = NormalizedDefinition & {\n  stats: {\n    requiredCount: number;\n    optionalCount: number;\n  };\n  typeDeclaration: string;\n};\n\nexport const apiReferenceData = ${JSON.stringify(generated, null, 2)} satisfies Record<string, ApiReferenceGeneratedDefinition>;\n`;

await ensureDir(dirname(outputPath));
await writeFile(outputPath, file);

console.info(`Generated API reference data for ${Object.keys(generated).length} definitions at ${outputPath}`);
