import ApiKeyCredentialProvider_ from './apiKeyCredentialProvider';
import BrowserCustom_ from './browserCustom';
import BrowserProfile_ from './browserProfile';
import CodeInterpreterCustom_ from './codeInterpreterCustom';
import Evaluator_ from './evaluator';
import Gateway_ from './gateway';
import GatewayTarget_ from './gatewayTarget';
import Memory_ from './memory';
import OAuth2CredentialProvider_ from './oAuth2CredentialProvider';
import OnlineEvaluationConfig_ from './onlineEvaluationConfig';
import Policy_ from './policy';
import PolicyEngine_ from './policyEngine';
import Runtime_ from './runtime';
import RuntimeEndpoint_ from './runtimeEndpoint';
import WorkloadIdentity_ from './workloadIdentity';
export namespace BedrockAgentCore {
  export const ApiKeyCredentialProvider = ApiKeyCredentialProvider_;
  export const BrowserCustom = BrowserCustom_;
  export const BrowserProfile = BrowserProfile_;
  export const CodeInterpreterCustom = CodeInterpreterCustom_;
  export const Evaluator = Evaluator_;
  export const Gateway = Gateway_;
  export const GatewayTarget = GatewayTarget_;
  export const Memory = Memory_;
  export const OAuth2CredentialProvider = OAuth2CredentialProvider_;
  export const OnlineEvaluationConfig = OnlineEvaluationConfig_;
  export const Policy = Policy_;
  export const PolicyEngine = PolicyEngine_;
  export const Runtime = Runtime_;
  export const RuntimeEndpoint = RuntimeEndpoint_;
  export const WorkloadIdentity = WorkloadIdentity_;
  export type ApiKeyCredentialProvider = ApiKeyCredentialProvider_;
  export type BrowserCustom = BrowserCustom_;
  export type BrowserProfile = BrowserProfile_;
  export type CodeInterpreterCustom = CodeInterpreterCustom_;
  export type Evaluator = Evaluator_;
  export type Gateway = Gateway_;
  export type GatewayTarget = GatewayTarget_;
  export type Memory = Memory_;
  export type OAuth2CredentialProvider = OAuth2CredentialProvider_;
  export type OnlineEvaluationConfig = OnlineEvaluationConfig_;
  export type Policy = Policy_;
  export type PolicyEngine = PolicyEngine_;
  export type Runtime = Runtime_;
  export type RuntimeEndpoint = RuntimeEndpoint_;
  export type WorkloadIdentity = WorkloadIdentity_;
}
