import AccountAuditConfiguration_ from './accountAuditConfiguration';
import Authorizer_ from './authorizer';
import BillingGroup_ from './billingGroup';
import CACertificate_ from './caCertificate';
import Certificate_ from './certificate';
import CertificateProvider_ from './certificateProvider';
import Command_ from './command';
import CustomMetric_ from './customMetric';
import Dimension_ from './dimension';
import DomainConfiguration_ from './domainConfiguration';
import EncryptionConfiguration_ from './encryptionConfiguration';
import FleetMetric_ from './fleetMetric';
import JobTemplate_ from './jobTemplate';
import Logging_ from './logging';
import MitigationAction_ from './mitigationAction';
import Policy_ from './policy';
import PolicyPrincipalAttachment_ from './policyPrincipalAttachment';
import ProvisioningTemplate_ from './provisioningTemplate';
import ResourceSpecificLogging_ from './resourceSpecificLogging';
import RoleAlias_ from './roleAlias';
import ScheduledAudit_ from './scheduledAudit';
import SecurityProfile_ from './securityProfile';
import SoftwarePackage_ from './softwarePackage';
import SoftwarePackageVersion_ from './softwarePackageVersion';
import Thing_ from './thing';
import ThingGroup_ from './thingGroup';
import ThingPrincipalAttachment_ from './thingPrincipalAttachment';
import ThingType_ from './thingType';
import TopicRule_ from './topicRule';
import TopicRuleDestination_ from './topicRuleDestination';
export namespace IoT {
  export const AccountAuditConfiguration = AccountAuditConfiguration_;
  export const Authorizer = Authorizer_;
  export const BillingGroup = BillingGroup_;
  export const CACertificate = CACertificate_;
  export const Certificate = Certificate_;
  export const CertificateProvider = CertificateProvider_;
  export const Command = Command_;
  export const CustomMetric = CustomMetric_;
  export const Dimension = Dimension_;
  export const DomainConfiguration = DomainConfiguration_;
  export const EncryptionConfiguration = EncryptionConfiguration_;
  export const FleetMetric = FleetMetric_;
  export const JobTemplate = JobTemplate_;
  export const Logging = Logging_;
  export const MitigationAction = MitigationAction_;
  export const Policy = Policy_;
  export const PolicyPrincipalAttachment = PolicyPrincipalAttachment_;
  export const ProvisioningTemplate = ProvisioningTemplate_;
  export const ResourceSpecificLogging = ResourceSpecificLogging_;
  export const RoleAlias = RoleAlias_;
  export const ScheduledAudit = ScheduledAudit_;
  export const SecurityProfile = SecurityProfile_;
  export const SoftwarePackage = SoftwarePackage_;
  export const SoftwarePackageVersion = SoftwarePackageVersion_;
  export const Thing = Thing_;
  export const ThingGroup = ThingGroup_;
  export const ThingPrincipalAttachment = ThingPrincipalAttachment_;
  export const ThingType = ThingType_;
  export const TopicRule = TopicRule_;
  export const TopicRuleDestination = TopicRuleDestination_;
  export type AccountAuditConfiguration = AccountAuditConfiguration_;
  export type Authorizer = Authorizer_;
  export type BillingGroup = BillingGroup_;
  export type CACertificate = CACertificate_;
  export type Certificate = Certificate_;
  export type CertificateProvider = CertificateProvider_;
  export type Command = Command_;
  export type CustomMetric = CustomMetric_;
  export type Dimension = Dimension_;
  export type DomainConfiguration = DomainConfiguration_;
  export type EncryptionConfiguration = EncryptionConfiguration_;
  export type FleetMetric = FleetMetric_;
  export type JobTemplate = JobTemplate_;
  export type Logging = Logging_;
  export type MitigationAction = MitigationAction_;
  export type Policy = Policy_;
  export type PolicyPrincipalAttachment = PolicyPrincipalAttachment_;
  export type ProvisioningTemplate = ProvisioningTemplate_;
  export type ResourceSpecificLogging = ResourceSpecificLogging_;
  export type RoleAlias = RoleAlias_;
  export type ScheduledAudit = ScheduledAudit_;
  export type SecurityProfile = SecurityProfile_;
  export type SoftwarePackage = SoftwarePackage_;
  export type SoftwarePackageVersion = SoftwarePackageVersion_;
  export type Thing = Thing_;
  export type ThingGroup = ThingGroup_;
  export type ThingPrincipalAttachment = ThingPrincipalAttachment_;
  export type ThingType = ThingType_;
  export type TopicRule = TopicRule_;
  export type TopicRuleDestination = TopicRuleDestination_;
}
